#INCLUDE "PROTHEUS.CH"
#INCLUDE "RWMAKE.CH"

#DEFINE CDIRPDF		"\boleto\"

#DEFINE NFIMLIN		170

Static cAliasCadGen	:= ""

Static lBoletoPDF	:= .F. as logical	//Verifica se o tipo de mensagem selecionado [ Imprimir / Envio] caso seja envio gera um arquivo PDF
// Static lEnvioBol	:= GetMv("ES_MAILBOL",, .F.) as logical	//Verifica se o tipo selecionado na mensagem e envio de [ Boleto ]
// Static lEnvBolNF	:= lBoletoPDF .AND. lEnvioBol as logical	//Verifica se o tipo selecionado na mensagem e envio de [ Boleto + Nota Fiscal ]

/*/{Protheus.doc} RFINR01
	(Rotina que centraliza as funcoes de impressao de Boletos)
	@type User Function
	@author Calabró
	@since 14/03/2019
	@version 1.0
	@param cCodEmp, character, (Empresa a ser considerada)
	@param cCodFil, character, (Filial da empresa a ser considerada)
	@param cNumTit, character, (Numero do titulo)
	@param cPrefixo, character, (Numero do prefixo do titulo)
	@return cFilePrint, character, (Caminho do arquivo PDF gerado, caso gere com sucesso)
	@example
	(examples)
	@see (links_or_references)
	/*/

User Function RFINR01(aParams as array)

Local cFilePrint	:= "" as character
Local cCodEmp		:= "" as character
Local cCodFil		:= "" as character
Local cNumTit		:= "" as character
Local cPrefixo		:= "" as character

Local lForceEnv		:= Empty(FunName()) as logical			//Verifica se ambiente foi inicializado
Local lRet			:= .T. as logical						//controle de retorno de processo

Local aAreas		:= {} as array

Default aParams		:= {}

If Len(aParams) > 0

	cCodEmp := aParams[1]
	cCodFil := aParams[2]
	cNumTit := aParams[3]
	cPrefixo := aParams[4]

	//Se nao existe ambiente, monto novo ambiente
	If lForceEnv
		RpcSetType(3)
		RpcSetEnv(cCodEmp, cCodFil,,,"FIN",,{"SE1"})
	EndIf
EndIf

// Continua se existir ambiente ativo
If !Empty(FunName()) .AND. !Empty(cEmpAnt)

	aAreas 	:= {SE1->(GetArea()), GetArea()}

	// Defino variaveis static de acordo com parametros
	lBoletoPDF := GetMv("ES_BOLPDF",, .F.)
	cAliasCadGen := AllTrim(GetMv("ES_BOLALIA",, "PE0"))

	DbSelectArea("SE1")
	DbSetOrder(1)
	If SE1->(DbSeek(xFilial("SE1")+cPrefixo+cNumTit)) .OR. !IsBlind()
		cFilePrint := ExecBoleto(cPrefixo, cNumTit, @lRet, IsBlind())
	EndIf

	// Finalizo ambiente se for job
	If lForceEnv
		RpcClearEnv()
	EndIf

	aEval(aAreas, {|x| RestArea(x) })
EndIf

Return cFilePrint

/*/{Protheus.doc} ExecBoleto
	(Rotina que executa a impressao de Boletos)
	@type Static Function
	@author Calabró
	@since 14/03/2019
	@version 1.0
	@param cNumTit, character, (Numero do titulo)
	@param cPrefixo, character, (Numero do prefixo do titulo)
	@param lRet, logical, (Variavel de retorno com sucesso (.T.) ou falha (.F.) da geracao do boleto)
	@param lJob, logical, (Variavel de controle para identificar se processo esta em job ou nao)
	@return cFilePrint, character, (Caminho do arquivo PDF gerado, caso gere com sucesso)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function ExecBoleto(cPrefixo as character, cNumTit as character, lRet as logical, lJob as logical)

Local cFilePrint	:= "" as character
Local cIndexName	:= '' as character
Local cIndexKey		:= '' as character
Local cFilter		:= '' as character

// Local nOpc			:= 0 as numeric

Local aPergs		:= {} as array
Local aRet			:= {} as array
Local aDimTela		:= MsAdvSize() as array		//Array com as dimensoes da tela

Local lExec		:= .F. as logical	

Local oTPnlRodap	:= Nil as object
Local oFont			:= TFont():New('Verdana',,-16,.F.) as object
Local oSay1			:= Nil as object
Local oSay2			:= Nil as object
Local oDlg		:= Nil as object

Tamanho  := "M"
titulo   := "Impressao de Boleto com Codigo de Barras"
cDesc1   := "Este programa destina-se a impressao do Boleto com Codigo de Barras."
cDesc2   := ""
cDesc3   := ""
cString  := "SE1"
wnrel    := "BOLETO"
lEnd     := .F.
cPerg    := PADR("RFINR01",10)
aReturn  := {"Zebrado", 1,"Administracao", 2, 2, 1, "",1 }
nLastKey := 0

DbSelectArea("SE1")

// Se nao for job, executo perguntas para filtrar titulos
// Senao preenche parametros para rotina utilizar envio de boleto automatico
If !lJob
	aPergs := MyPerg()
Else
	MV_PAR01 := SE1->E1_PREFIXO
	MV_PAR02 := SE1->E1_PREFIXO
	MV_PAR03 := SE1->E1_NUM
	MV_PAR04 := SE1->E1_NUM
	MV_PAR05 := ""
	MV_PAR06 := "Z"
	MV_PAR07 := ""
	MV_PAR08 := "ZZZ"
	MV_PAR09 := ""
	MV_PAR10 := "ZZZZZZ"
	MV_PAR11 := ""
	MV_PAR12 := "ZZ"
	MV_PAR13 := SE1->E1_EMIS1
	MV_PAR14 := SE1->E1_EMIS1
	MV_PAR15 := SE1->E1_VENCREA
	MV_PAR16 := SE1->E1_VENCREA
	MV_PAR17 := ""
	MV_PAR18 := "ZZZZZZ"
	MV_PAR19 := ""
	MV_PAR20 := ""
	MV_PAR21 := ""
	MV_PAR22 := .T.							// Traz registors marcados
	MV_PAR23 := GetMv("ES_BOLPDF",, .F.)	// Gera Boleto
	MV_PAR24 := GetMv("ES_DNFPDF",, .F.)	// Gera Danfe
	MV_PAR25 := GetMv("ES_GERXML",, .F.)	// Gera XML
	MV_PAR26 := .T.							// Envia docs. por e-mail
	MV_PAR27 := ""							// Caminho de destino para salvar documentos
EndIf

If Len(aPergs) > 0 .OR. lJob

	cIndexName	:= Criatrab(Nil,.F.)

	cIndexKey	:= "E1_PREFIXO+E1_NUM+E1_PARCELA+E1_TIPO+DTOS(E1_EMISSAO)+E1_PORTADO+E1_CLIENTE"

	cFilter		+= "E1_FILIAL=='"+xFilial("SE1")+"'.And.E1_SALDO>0.And."
	cFilter		+= "E1_PREFIXO>='" + MV_PAR01 + "'.And.E1_PREFIXO<='" + MV_PAR02 + "'.And."
	cFilter		+= "E1_NUM>='" + MV_PAR03 + "'.And.E1_NUM<='" + MV_PAR04 + "'.And."
	cFilter		+= "E1_PARCELA>='" + MV_PAR05 + "'.And.E1_PARCELA<='" + MV_PAR06 + "'.And."
	cFilter		+= "E1_PORTADO>='" + MV_PAR07 + "'.And.E1_PORTADO<='" + MV_PAR08 + "'.And."
	cFilter		+= "E1_CLIENTE>='" + MV_PAR09 + "'.And.E1_CLIENTE<='" + MV_PAR10 + "'.And."
	cFilter		+= "E1_LOJA>='" + MV_PAR11 + "'.And.E1_LOJA<='"+MV_PAR12+"'.And."
	cFilter		+= "DTOS(E1_EMISSAO)>='"+DTOS(mv_par13)+"'.and.DTOS(E1_EMISSAO)<='"+DTOS(mv_par14)+"'.And."
	cFilter		+= 'DTOS(E1_VENCREA)>="'+DTOS(mv_par15)+'".and.DTOS(E1_VENCREA)<="'+DTOS(mv_par16)+'".And.'
	cFilter		+= "E1_NUMBOR>='" + MV_PAR17 + "'.And.E1_NUMBOR<='" + MV_PAR18 + "'.And."
	cFilter		+= "!(E1_TIPO$MVABATIM) .And. "
	cFilter		+= "( E1_VENCREA >= E1_EMISSAO ) "

	IndRegua("SE1", cIndexName, cIndexKey,, cFilter, "Aguarde selecionando registros....")
	DbSelectArea("SE1")
	dbGoTop()

	nVlrSel := 0
	nQtdSel := 0

	//Envio de boleto em tela
	//Senao sera envio de boleto em job
	If !lJob

		// Se rotina estiver processando em tela, defino variaveis de geracao de boleto, Danfe e XML
		// de acordo com respostas do usuario
		lBoletoPDF := MV_PAR23

		@ 001,001 TO 400,700 DIALOG oDlg TITLE "Seleção de Titulos"

			oDlg:lMaximized := .T.

			// Informacoes do Browse
			@ 001,001 TO 170,350 BROWSE "SE1" MARK "E1_OK" OBJECT oBrw

			// Configuro lista com exibicao total da tela
			oBrw:oBrowse:Align := CONTROL_ALIGN_ALLCLIENT

			// Defino funcao ao clicar no cabecalho
			oBrw:oBrowse:bHeaderClick := {|| InvAllMarcas(@oBrw), AtuTotalizad(oSay1, oSay2) }

			// Defino funcao ao efetuar duplo clique na linha
			oBrw:OBROWSE:BLDBLCLICK := {|| InverteMarca(@oBrw), AtuTotalizad(oSay1, oSay2) }

			// Informacoes do rodape da tela
			oTPnlRodap := TPanel():New(0,0,"",oDlg,Nil,.T.,.F.,Nil,Nil,0, aDimTela[6] * 0.065,.T.,.F.)

			// Configuro rodape com exibicao total da tela, respeitando o tamanho do rodape
			oTPnlRodap:Align := CONTROL_ALIGN_BOTTOM

			oSay1 := TSay():New( 010, 010,{|| "Qtd Selec.: " + AllTrim(Transform(nQtdSel,"@R 999999999"))}, oTPnlRodap,,oFont,.F.,.F.,.F.,.T.,CLR_HBLUE,CLR_WHITE,120,020)
			oSay2 := TSay():New( 010, 100,{|| "Vlr Selec.: "+AllTrim(Transform(nVlrSel,"@R 99,999,999.99"))}, oTPnlRodap,,oFont,.F.,.F.,.F.,.T.,CLR_HBLUE,CLR_WHITE,120,020)
			DEFINE SBUTTON FROM 010, oDlg:NCLIENTWIDTH - 100 TYPE 01 ENABLE OF oTPnlRodap ACTION (lExec := .T.,Close(oDlg))
			DEFINE SBUTTON FROM 010, oDlg:NCLIENTWIDTH - 130 TYPE 02 ENABLE OF oTPnlRodap ACTION (lExec := .F.,Close(oDlg))

			// Se nao traz registros marcados, limpo campo de MARK
			If !MV_PAR22
				LimpaMark(oBrw)
			EndIf

			SE1->(dbGoTop())
			While SE1->(!Eof())
				If Marked("E1_OK")
					nQtdSel++
					nVlrSel+=SE1->E1_VLCRUZ
				EndIf
				SE1->(dbSkip())
			Enddo
			SE1->(dbGoTop())

		ACTIVATE DIALOG oDlg CENTERED

		If lExec
			dbGoTop()
			//Variaveis criadas para consolidacao dos fontes de boletos
			aRet := {}
			aPergs  := {}
		
			Processa({|lEnd|MontaRel(lJob)})
		EndIf
	Else

		MontaRel(lJob, @cFilePrint)
	EndIf

	RetIndex("SE1")

	Ferase(cIndexName+OrdBagExt())
EndIf

Return cFilePrint

/*/{Protheus.doc} MontaRel
	(Impressao do boleto com codigo de barras)
	@type Static Function
	@author Renato Calabro'
	@since 20/03/2019
	@version 1.0
	@param lJob, logic, (Variavel de controle para identificar se processo esta em job ou nao)
	@return cFilePrint, character, (Caminho do arquivo PDF gerado, caso gere com sucesso)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function MontaRel(lJob as logical, cFilePrint as character)

// Local cFilePrint	:= "" as character
Local cSfxNomArq	:= GetMv("ES_BOLSUFX",, "boleto_") as character
Local cSubConta		:= "" as character
Local cArqDanfe		:= "" as character
Local cArqXML		:= "" as character

Local nVlrAbat		:= 0 as numeric
Local nX			:= 0 as numeric

Local aDadosEmp		:= {} as array
Local aDadosTit		:= {} as array
Local aDadosBanco	:= {} as array
Local aDatSacado	:= {} as array
Local aBolText		:= { MV_PAR19, MV_PAR20, MV_PAR21 } as array
Local aAreas		:= {SM0->(GetArea()), GetArea() } as array
Local aDanfes		:= {} as array
Local aXML			:= {} as array

Local oPrint		:= Nil as object

Private cNroDoc		:=  " " as character
Private nVetor		:= 0 as numeric
Private nContB		:= 0 as numeric
Private nTotImpEnv	:= 0 as numeric

Private dVencRea	:= CTOD("") as date

Private aTitulo		:= {} as array
Private aCB_RN_NN	:= {} as array

cFilePrint := If(Empty(cFilePrint), "", cFilePrint)

lJob := If(Empty(lJob), .F., lJob)

// Posiciona o SIGAMAT na filial 01 para que conste os dados da MATRIZ no boleto
DbSelectArea("SM0")
dbGoTop()
SM0->(MsSeek(cEmpAnt+cFilAnt))
aDadosEmp    := {	AllTrim(SM0->M0_NOMECOM),													; //[1]Nome da Empresa
					AllTrim(SM0->M0_ENDCOB),													; //[2]Endereço
					AllTrim(SM0->M0_BAIRCOB),													; //[3]Complemento
					AllTrim(SM0->M0_CIDCOB)+", "+SM0->M0_ESTCOB + " - CEP: "+					; //[4]Cidade + Estado
					Subs(SM0->M0_CEPCOB,1,5)+"-"+Subs(SM0->M0_CEPCOB,6,3),						; //[4]CEP
					"TEL: "+SM0->M0_TEL,														; //[5]Telefones
					"CNPJ "+Subs(SM0->M0_CGC,1,2)+"."+Subs(SM0->M0_CGC,3,3)+"."+				; //[6]
					Subs(SM0->M0_CGC,6,3)+"/"+Subs(SM0->M0_CGC,9,4)+"-"+						; //[6]
					Subs(SM0->M0_CGC,13,2),														; //[6]CGC
					"I.E.: "+Subs(SM0->M0_INSC,1,3)+"."+Subs(SM0->M0_INSC,4,3)+"."+				; //[7]
					Subs(SM0->M0_INSC,7,3)+"."+Subs(SM0->M0_INSC,10,3)							} //[7]I.E

aEval(aAreas, {|x| RestArea(x) })

// Monta nome do PDF com estrutura: Sufixo do MV + num. titulo + prefixo do titulo
cFilePrint := cSfxNomArq + AllTrim(SE1->E1_NUM) + AllTrim(SE1->E1_PREFIXO)

oPrint:= FwMSPrinter():New(cFilePrint, 6, .T., CDIRPDF, .T.,,,,,,, .F.)
oPrint:SetPortrait()
oPrint:SetResolution(78)

nResult := 0
If !lIsDir(CDIRPDF)
	nResult := MakeDir(CDIRPDF)
EndIf

If Empty(nResult)

	oPrint:cPathPDF := CDIRPDF

	DbSelectArea("SE1")
	dbGotop()
	ProcRegua(RecCount())

	While SE1->(!EOF())

		If !lJob
			IncProc()
		EndIf

		If Marked("E1_OK")
			// Posiciona o SEA (Titulos enviados ao banco)
			DbSelectArea("SEA")
			SEA->(DbSetOrder(1))	// EA_FILIAL+EA_NUMBOR+EA_PREFIXO+EA_NUM+EA_PARCELA+EA_TIPO+EA_FORNECE+EA_LOJA
			If SEA->( DbSeek(xFilial("SEA") + SE1->(E1_NUMBOR+E1_PREFIXO+E1_NUM+E1_PARCELA+E1_TIPO) ))

				// Posiciona o SA6 (Bancos)
				DbSelectArea("SA6")
				SA6->(DbSetOrder(1))
				If SA6->( DbSeek(xFilial("SA6") + SEA->(EA_PORTADO+EA_AGEDEP+EA_NUMCON) ))

					cSubConta := SA6->(GetSubConta(A6_COD, A6_AGENCIA, A6_NUMCON))

					// Posiciona o SEE (Parametros de bancos)
					DbSelectArea("SEE")
					SEE->(DbSetOrder(1))	// EE_FILIAL+EE_CODIGO+EE_AGENCIA+EE_CONTA+EE_SUBCTA
					If SEE->(DbSeek(xFilial("SEE")+SA6->(A6_COD+A6_AGENCIA+A6_NUMCON)+cSubConta))

						IF !Vazio(SE1->E1_PORTADO)
							If ALLTRIM(SE1->E1_PORTADO) # SA6->A6_COD
								SE1->(DbSkip())
								Loop
							EndIf
						EndIf

						//Posiciona o SA1 (Cliente)
						DbSelectArea("SA1")
						DbSetOrder(1)
						DbSeek(xFilial("SA1")+SE1->E1_CLIENTE+SE1->E1_LOJA,.T.)
						
						DbSelectArea("SE1")

						// Informacoes dos bancos
						aDadosBanco  := {	AllTrim(SA6->A6_COD),;		// [1]Numero do Banco
											AllTrim(SA6->A6_NOME),;		// [2]Nome do Banco
											AllTrim(SA6->A6_AGENCIA),;	// [3]Agência
											AllTrim(SA6->A6_NUMCON),;	// [4]Conta Corrente
											AllTrim(SA6->A6_DVCTA),;	// [5]Dígito da conta corrente
											Alltrim(SEE->EE_CODCART) }	// [6]Codigo da Carteira


						// Informacoes do sacador
						If Empty(SA1->A1_ENDCOB)
							aDatSacado := {	AllTrim(SA1->A1_NOME)								,;		// [1]Razão Social
											AllTrim(SA1->A1_COD )+"-"+SA1->A1_LOJA				,;		// [2]Código
											AllTrim(SA1->A1_END )+"-"+AllTrim(SA1->A1_BAIRRO)	,;		// [3]Endereço
											AllTrim(SA1->A1_MUN )								,;		// [4]Cidade
											SA1->A1_EST											,;     	// [5]Estado
											SA1->A1_CEP											,;		// [6]CEP
											SA1->A1_CGC											,;		// [7]CGC
											SA1->A1_PESSOA										}		// [8]PESSOA
						Else
							aDatSacado := {	AllTrim(SA1->A1_NOME)								,;		// [1]Razão Social
											AllTrim(SA1->A1_COD )+"-"+SA1->A1_LOJA				,;		// [2]Código
											AllTrim(SA1->A1_ENDCOB)+"-"+AllTrim(SA1->A1_BAIRROC),;		// [3]Endereço
											AllTrim(SA1->A1_MUNC)								,;		// [4]Cidade
											SA1->A1_ESTC										,;		// [5]Estado
											SA1->A1_CEPC										,;		// [6]CEP
											SA1->A1_CGC											,;		// [7]CGC
											SA1->A1_PESSOA										}		// [8]PESSOA
						EndIf
						
						// Soma abatimentos do título
						nVlrAbat:=  0
						SumAbatRec(SE1->E1_PREFIXO,SE1->E1_NUM,SE1->E1_PARCELA,SE1->E1_MOEDA,"V",,@nVlrAbat)
						nVlrAbat   +=  SE1->E1_DECRESC
						
						IF SEE->EE_CODIGO == "237"
							// Nosso Numero + Digito Verificador
							If FindFunction("U_MyCalcNoNu")
								cNroDoc := U_MyCalcNoNu(SEE->EE_CODCART)
							Else
								cNroDoc := CalcNoNu(SEE->EE_CODCART)
							EndIf
						Else
							// Aqui defino parte do nosso numero. Sao 8 digitos para identificar o titulo.
							// Abaixo apenas uma sugestao
							cNroDoc	:= Strzero(Val(Alltrim(SE1->E1_NUM)),6)+StrZERO(Val(Alltrim(SE1->E1_PARCELA)),2)
							cNroDoc	:= STRZERO(Val(cNroDoc),11)
						EndIf

						nVlrBol := E1_SALDO - nVlrAbat
						nVlrBol += SE1->E1_ACRESC

						dVencRea := SE1->E1_VENCREA

						If SA6->A6_COD == "237"
							// Monta codigo de barras e calcula o nosso numero com digito verificador
							aCB_RN_NN := Ret_cB(Subs(aDadosBanco[1],1,3), aDadosBanco[3], aDadosBanco[4], cNroDoc, nVlrBol ,dVencRea/*U_GetNewVFI2('*1',E1_VENCREA)*/)
						Else
							// Monta codigo de barras
							aCB_RN_NN := Ret_cBarra(aDadosBanco[3], nVlrBol, SEE->EE_CODCART, "9")
						EndIf

						DbSelectArea("SE1")
						aDadosTit	:= {AllTrim(E1_NUM)+AllTrim(E1_PARCELA)	,;  // [1] Número do título
						E1_EMISSAO                              				,;	// [2] Data da emissão do título
						dDataBase                    							,;	// [3] Data da emissão do boleto
						dVencRea												,;	// [4] Data do vencimento
						nVlrBol               									,;  // [5] Valor do título
						aCB_RN_NN[3]                            				,;	// [6] Nosso número (Ver fórmula para calculo)
						E1_PREFIXO                              				,;	// [7] Prefixo da NF
						E1_TIPO	                           						,;	// [8] Tipo do Titulo
						E1_PARCELA}													// [9] Parcela

						// Rotina utilizada para envio de boleto automatico
						If lJob

							nTotImpEnv++
							Impress(oPrint,aDadosEmp,aDadosTit,aDadosBanco,aDatSacado,aBolText,aCB_RN_NN, cFilePrint)
						Else

							DbSelectArea("SE1")
							If Marked("E1_OK") .AND. nVlrBol > 0

								nTotImpEnv++
								Impress(oPrint,aDadosEmp,aDadosTit,aDadosBanco,aDatSacado,aBolText,aCB_RN_NN, cFilePrint)
							EndIf
						EndIf

						// Grava a data que foi enviada para o cliente
						GrvHistSE1(aCB_RN_NN, cNroDoc)
					Else
						GeraMsgErro("Subconta da agência e conta não encontrado no cadastro de parâmetros de bancos: " + xFilial("SEE") + SA6->(A6_COD+A6_AGENCIA+A6_NUMCON),;
									lJob,;
									{"&Cancelar"})
					EndIf
				Else
					GeraMsgErro("Agência e conta não encontrados no cadastro de banco: " + xFilial("SA6") + SEA->(EA_PORTADO+EA_AGEDEP+EA_NUMCON),;
								lJob,;
								{"&Cancelar"})
				EndIf
			Else
				GeraMsgErro("Dados de titulos enviados ao banco não encontrados: " + xFilial("SEA") + SE1->(E1_NUMBOR+E1_PREFIXO+E1_NUM+E1_PARCELA+E1_TIPO+E1_CLIENTE+E1_LOJA),;
							lJob,;
							{"&Cancelar"})
			EndIf
		EndIf
		SE1->(DbSkip())
	EndDo
Else
	GeraMsgErro("Não foi possível criar o diretório " + CDIRPDF + " para a geração do arquivo do boleto em PDF.", lJob, {"&Sair"})
EndIf

// Se nao for job, informo usuario na tela de quantos boletos foram impressos
If !lJob .AND. nTotImpEnv > 0
	msgInfo("Total de títulos impressos/enviados: " + AllTrim(Str(nTotImpEnv)))
EndIf

If !Empty(cFilePrint)
	//Se existe aquivo PDF antigo, apaga arquivo
	If File(FileNoExt(oPrint:cFilePrint)+".PDF")
		FErase(FileNoExt(oPrint:cFilePrint) + ".PDF")
	EndIf

	oPrint:Preview()
	//Armazeno caminho que encontra-se o boleto
	cFilePrint := FileNoExt(oPrint:cFilePrint) + ".PDF"
EndIf

// Laco para verificar se deve gerar outros documentos: Danfe e/ou XML
For nX := 1 to Len(aTitulo)

	// Verifica se deve gerar rotina de impressao de Danfe caso esteja compilada no repositorio
	If MV_PAR24 .AND. FindFunction("U_" + StrTran(AllTrim(GetMv("ES_FUNDANF",,"RFATR02")),"U_", ""))

		// U_RFATR01(SF2->F2_DOC, SF2->F2_SERIE, SA1->A1_YLAYDNF, "1", IsBlind())
		cArqDanfe := &("U_" + StrTran(AllTrim(GetMv("ES_FUNDANF",,"RFATR02")),"U_", "") + "('" + aTitulo[nX][2] + "', '" + aTitulo[nX][3] + "', Nil, '1', " + If(lJob, ".T.", ".F.") + ")")

		If File(cArqDanfe)
			AAdd(aDanfes, cArqDanfe)
		EndIf
	EndIf

	// Verifica se deve gerar rotina de impressao de Danfe caso esteja compilada no repositorio
	If MV_PAR25 .AND. FindFunction("U_" + StrTran(AllTrim(GetMv("ES_FUNXML",,"RFATR02XML")),"U_", ""))

		// U_RFATR01XML(SF2->F2_DOC, SF2->F2_SERIE, "\boleto\")
		cArqXML := &("U_" + StrTran(AllTrim(GetMv("ES_FUNDANF",,"RFATR02XML")),"U_", "") + "('" + aTitulo[nX][2] + "', '" + aTitulo[nX][3] + "', '" +;
					CDIRPDF + cFilePrint + "')")

		If File(cArqXML)
			AAdd(aXML, cArqXML)
		EndIf
	EndIf
Next nX

// Chama rotina de envio de e-mail - RFA01EnvBol se for definido para enviar por e-mail
If MV_PAR26
	RFA01EnvBol(aTitulo, aDanfes, aXML, lJob)
EndIf

// Se nao for job e parametro de para gravar arquivo na máquina local estiver preenchido,
// executo para cada documento gerado
If !lJob .AND. !Empty(MV_PAR27)
	AEval(aTitulo,{|x| CpyS2T(CDIRPDF + FileNoExt(x[1]) + ".pdf", Alltrim(MV_PAR27)) })
	// Excluo documentos apos gravacao em local escolhido por usuario
	AEval(aTitulo,{|x| FErase(CDIRPDF + FileNoExt(x[1]) + ".pdf") })
EndIf

//Limpa o Filtro da tabela SE1
SE1->(DBCLEARFILTER())

FreeObj(oPrint)
oPrint := Nil

Return cFilePrint

/*/{Protheus.doc} Impress
	(Impressao do boleto com codigo de barras)
	@type Static Function
	@author Calabro'
	@since 13/10/2003
	@version version
	@param oPrint, object, (Objeto com as propriedades de impressao do FwMsPrinter instanciado)
	@param aDadosEmp, array, (Array com dados da empresa logada)
	@param aDadosTit, array, (Array com dados do titulo posicionado)
	@param aDadosBanco, array, (Array com dados do banco)
	@param aDatSacado, array, (Array com dados do sacado)
	@param aBolText, array, (Array com as 3 observacoes adicionadas nos parametros de perguntas)
	@param aCB_RN_NN, array, (Array com dados dos codigos de barras)
	@param cFilePrint, character, (Caminho do arquivo PDF gerado, caso gere com sucesso)
	@return cFilePrint, character, (Caminho do arquivo PDF gerado, caso gere com sucesso)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function Impress(oPrint as object,;
						aDadosEmp as array,;
						aDadosTit as array,;
						aDadosBanco as array,;
						aDatSacado as array,;
						aBolText as array,;
						aCB_RN_NN as array,;
						cFilePrint as character)

Local oFont8		:= Nil as object
Local oFont9		:= Nil as object
Local oFont7		:= Nil as object
Local oFont9n		:= Nil as object
Local oFont11c		:= Nil as object
Local oFont11		:= Nil as object
Local oFont10		:= Nil as object
Local oFont13		:= Nil as object
Local oFont14		:= Nil as object
Local oFont16n		:= Nil as object
Local oFont15		:= Nil as object
Local oFont14n		:= Nil as object
Local oFont18		:= Nil as object
Local oFont24		:= Nil as object
Local oBrush		:= Nil as object

Local _cNum			:= SE1->E1_NUM as character
Local _cPrefix		:= SE1->E1_PREFIXO as character
Local _cParcel		:= SE1->E1_PARCELA as character
Local cCodCli		:= SE1->E1_CLIENTE as character
Local cLojaCli		:= SE1->E1_LOJA as character
Local cNomCli		:= ALLTRIM(SE1->E1_NOMCLI) as character
Local _cPortado		:= "" as character
Local cXFil			:= SE1->E1_FILIAL as character
Local cXTipo		:= SE1->E1_TIPO as character
Local cLogo			:= GetLogoBanco(SEE->EE_CODIGO) as character	//\system\bradesco.png"

Local nI			:= 0 as numeric
Local nPosVet		:= 0  as numeric

oFont7 := TFont():New("Arial",9,7,.T.,.F.,5,.T.,5,.T.,.F.)
oFont8 := TFont():New("Arial",9,8,.T.,.F.,5,.T.,5,.T.,.F.)
oFont9 := TFont():New("Arial",9,9,.T.,.T.,5,.T.,5,.T.,.F.)
oFont9n := TFont():New("Arial",9,9,.T.,.F.,5,.T.,5,.T.,.F.)
oFont11 := TFont():New("Arial",9,11,.T.,.T.,5,.T.,5,.T.,.F.)
oFont11c := TFont():New("Courier New",9,11,.T.,.T.,5,.T.,5,.T.,.F.)
oFont10 := TFont():New("Arial",9,10,.T.,.T.,5,.T.,5,.T.,.F.)
oFont12 := TFont():New("Arial",9,12,.T.,.T.,5,.T.,5,.T.,.F.)
oFont13 := TFont():New("Arial",9,13,.T.,.T.,5,.T.,5,.T.,.F.)
oFont14 := TFont():New("Arial",9,14,.T.,.T.,5,.T.,5,.T.,.F.)
oFont18 := TFont():New("Arial",9,18,.T.,.T.,5,.T.,5,.T.,.F.)
oFont20 := TFont():New("Arial",9,20,.T.,.T.,5,.T.,5,.T.,.F.)
oFont21 := TFont():New("Arial",9,21,.T.,.T.,5,.T.,5,.T.,.F.)
oFont16n := TFont():New("Arial",9,16,.T.,.F.,5,.T.,5,.T.,.F.)
oFont15 := TFont():New("Arial",9,15,.T.,.T.,5,.T.,5,.T.,.F.)
oFont15n := TFont():New("Arial",9,15,.T.,.F.,5,.T.,5,.T.,.F.)
oFont14n := TFont():New("Arial",9,14,.T.,.F.,5,.T.,5,.T.,.F.)
oFont24 := TFont():New("Arial",9,24,.T.,.T.,5,.T.,5,.T.,.F.)
oBrush := TBrush():New("",9)

oPrint:StartPage()   // Inicia uma nova página

// PRIMEIRA PARTE

nRow1 := -100

oPrint:Line (nRow1+0150,500,nRow1+0070, 500)
oPrint:Line (nRow1+0150,710,nRow1+0070, 710)

oPrint:SayBitmap(nRow1+0054,100,cLogo,380,090) 										// o arquivo com o logo deve estar abaixo do rootpath (Data\system)
oPrint:Say (nRow1+0115,513,aDadosBanco[1]+GetDVBanco(aDadosBanco[1])[2],oFont21 )	// [1]Numero do Banco

oPrint:Say (nRow1+0104,1900,"Comprovante de Entrega",oFont10)
oPrint:Line (nRow1+0150,100,nRow1+0150,2300)

oPrint:Say (nRow1+0170,100 ,OemToansi("Beneficiário:"),oFont8)
oPrint:Say (nRow1+0190,100 ,aDadosEmp[1]+" - "+aDadosEmp[6],oFont9)				//Nome + CNPJ
oPrint:Say (nRow1+0215,100 ,aDadosEmp[2],oFont9)								//End
oPrint:Say (nRow1+0240,100 ,aDadosEmp[3] + " - " + aDadosEmp[4],oFont9)			//Bairro + CEP + Compl

oPrint:Say (nRow1+0170,1060,OemToansi("Agência/Código Beneficiário:"),oFont8)
oPrint:Say (nRow1+0220,1060,StrTran(aDadosBanco[3]+"/"+aDadosBanco[4]+IIF(Empty(aDadosBanco[5])," ","-"+aDadosBanco[5]),'--','-'),oFont10)

oPrint:Say (nRow1+0170,1510,"Nro.Documento:",oFont8)
oPrint:Say (nRow1+0220,1510,"  "+aDadosTit[7]+aDadosTit[1],oFont10)				//Prefixo +Numero+Parcela

oPrint:Say (nRow1+0270,100 ,"Pagador:",oFont8)
oPrint:Say (nRow1+0320,100 ,SUBSTR(aDatSacado[1],1,40),oFont10)					//Nome

oPrint:Say (nRow1+0270,1060,"Vencimento",oFont8)
oPrint:Say (nRow1+0320,1060,StrZero(Day(aDadosTit[4]),2) +"/"+ StrZero(Month(aDadosTit[4]),2) +"/"+ Right(Str(Year(aDadosTit[4])),4),oFont10)

oPrint:Say (nRow1+0270,1510,"Valor do Documento",oFont8)
oPrint:Say (nRow1+0320,1550,AllTrim(Transform(aDadosTit[5],"@E 999,999,999.99")),oFont10)

oPrint:Say (nRow1+0420,0100,"Recebi(emos) o bloqueto/título",oFont10)
oPrint:Say (nRow1+0470,0100,"com as características acima.",oFont10)
oPrint:Say (nRow1+0370,1060,"Data",oFont8)
oPrint:Say (nRow1+0370,1410,"Assinatura",oFont8)
oPrint:Say (nRow1+0470,1060,"Data",oFont8)
oPrint:Say (nRow1+0470,1410,"Entregador",oFont8)

oPrint:Line (nRow1+0250, 100,nRow1+0250,1900 )
oPrint:Line (nRow1+0350, 100,nRow1+0350,1900 )
oPrint:Line (nRow1+0550, 100,nRow1+0550,2300 )

oPrint:Line (nRow1+0550,1050,nRow1+0150,1050 )
oPrint:Line (nRow1+0550,1400,nRow1+0350,1400 )
oPrint:Line (nRow1+0350,1500,nRow1+0150,1500 )
oPrint:Line (nRow1+0550,1900,nRow1+0150,1900 )

oPrint:Say (nRow1+0185,1910,"(  )Mudou-se"									,oFont8)
oPrint:Say (nRow1+0225,1910,"(  )Ausente"									,oFont8)
oPrint:Say (nRow1+0265,1910,"(  )Não existe nº indicado"					,oFont8)
oPrint:Say (nRow1+0305,1910,"(  )Recusado"									,oFont8)
oPrint:Say (nRow1+0345,1910,"(  )Não procurado"								,oFont8)
oPrint:Say (nRow1+0385,1910,"(  )Endereço insuficiente"						,oFont8)
oPrint:Say (nRow1+0425,1910,"(  )Desconhecido"								,oFont8)
oPrint:Say (nRow1+0465,1910,"(  )Falecido"									,oFont8)
oPrint:Say (nRow1+0505,1910,"(  )Outros(anotar no verso)"					,oFont8)

// SEGUNDA PARTE
nRow2 := -80

// Pontilhado separador
For nI := 100 to 2300 step 50
	oPrint:Line(0500, nI,0500, nI+30)
Next nI

oPrint:Line (nRow2+0710,100,nRow2+0710,2300)
oPrint:Line (nRow2+0710,500,nRow2+0630, 500)
oPrint:Line (nRow2+0710,710,nRow2+0630, 710)

oPrint:SayBitmap(nRow2+0610,100,cLogo,380,090)											// o arquivo com o logo deve estar abaixo do rootpath (Data\system)
oPrint:Say (nRow2+0685,513,aDadosBanco[1]+GetDVBanco(aDadosBanco[1])[2],oFont21 )		// [1]Numero do Banco
oPrint:Say (nRow2+0694,1800,"Recibo do Pagador",oFont10)

oPrint:Line (nRow2+0810,100,nRow2+0810,2300 )
oPrint:Line (nRow2+0910,100,nRow2+0910,2300 )
oPrint:Line (nRow2+0980,100,nRow2+0980,2300 )
oPrint:Line (nRow2+1050,100,nRow2+1050,2300 )

oPrint:Line (nRow2+0910,500,nRow2+1050,500)
oPrint:Line (nRow2+0980,750,nRow2+1050,750)
oPrint:Line (nRow2+0910,1000,nRow2+1050,1000)
oPrint:Line (nRow2+0910,1300,nRow2+0980,1300)
oPrint:Line (nRow2+0910,1480,nRow2+1050,1480)

oPrint:Say (nRow2+0730,100 ,"Local de Pagamento:"										,oFont8)
oPrint:Say (nRow2+0745,400 ,"PAGÁVEL EM QUALQUER BANCO ATÉ A DATA DO VENCIMENTO"		,oFont10)
oPrint:Say (nRow2+0730,1810,"Vencimento:"												,oFont8)
cString	:= StrZero(Day(aDadosTit[4]),2) +"/"+ StrZero(Month(aDadosTit[4]),2) +"/"+ Right(Str(Year(aDadosTit[4])),4)
nCol := 1810+(374-(len(cString)*22))
oPrint:Say (nRow2+0770,nCol,cString,oFont11c)

oPrint:Say (nRow2+0830,100 ,OemToansi("Beneficiário:")									,oFont8)
oPrint:Say (nRow2+0850,100 ,AllTrim(aDadosEmp[1]+" - "+aDadosEmp[6] )					,oFont9) 		//Nome + CNPJ
oPrint:Say (nRow2+0875,100 ,aDadosEmp[2]												,oFont9)		//End + Bairro
oPrint:Say (nRow2+0900,100 ,aDadosEmp[3] + " - " + aDadosEmp[4]							,oFont9)		//CEP + Compl

oPrint:Say (nRow2+0830,1810,"Agência/Código "+OemToansi("Beneficiário:")				,oFont8)
cString := StrTran(Alltrim(aDadosBanco[3]+"/"+aDadosBanco[4]+IIF(Empty(aDadosBanco[5])," ","-"+aDadosBanco[5])),'--','-')
nCol := 1818+(374-(len(cString)*22))
oPrint:Say (nRow2+0870,nCol,cString,oFont11c)

oPrint:Say (nRow2+0930,100 ,"Data do Documento:"										,oFont8)
oPrint:Say (nRow2+0960,100, StrZero(Day(aDadosTit[2]),2) +"/"+ StrZero(Month(aDadosTit[2]),2) +"/"+ Right(Str(Year(aDadosTit[2])),4),oFont10)

oPrint:Say (nRow2+0930,505 ,"Nro.Documento:"											,oFont8)
oPrint:Say (nRow2+0960,605 ,aDadosTit[1]												,oFont10)		//Numero+Parcela

oPrint:Say (nRow2+0930,1005,"Espécie Doc.:"												,oFont8)
oPrint:Say (nRow2+0960,1050,"DM"														,oFont10)		//Tipo do Titulo

oPrint:Say (nRow2+0930,1305,"Aceite:"													,oFont8)
oPrint:Say (nRow2+0960,1400,"N"															,oFont10)

oPrint:Say (nRow2+0930,1485,"Data do Processamento:"									,oFont8)
oPrint:Say (nRow2+0960,1550,StrZero(Day(aDadosTit[3]),2) +"/"+ StrZero(Month(aDadosTit[3]),2) +"/"+ Right(Str(Year(aDadosTit[3])),4),oFont10) // Data impressao

oPrint:Say (nRow2+0930,1810,"Nosso Número:"												,oFont8)
If SA6->A6_COD == "341" .Or. SA6->A6_COD == "422"
	cString := aDadosBanco[6] + "/" + Alltrim(substr(aDadosTit[6],1,8)) + "-" + Alltrim(substr(aDadosTit[6],9,1))
ElseIf SA6->A6_COD == "001"
	cString := Alltrim("1225233"+aDadosTit[6])
ElseIf SA6->A6_COD == "237"
	cString := '09/'+Substr(cNroDoc,1,11)+'-'+Substr(cNroDoc,12,1)
ElseIf SA6->A6_COD $ "637/@/033"
	cString := aDadosTit[6]+'-'+Modulo11(aDadosTit[6])
EndIf

nCol := 1854+(374-(len(cString)*22))
oPrint:Say (nRow2+0960,nCol,cString,oFont11c)

oPrint:Say (nRow2+1000,100 ,"Uso do Banco:"												,oFont8)

oPrint:Say (nRow2+1000,505 ,"Carteira:"													,oFont8)
oPrint:Say (nRow2+1030,555 ,aDadosBanco[6]												,oFont10)

oPrint:Say (nRow2+1000,755 ,"Espécie:"													,oFont8)
oPrint:Say (nRow2+1030,805 ,"R$"														,oFont10)

oPrint:Say (nRow2+1000,1005,"Quantidade:"												,oFont8)
oPrint:Say (nRow2+1000,1485,"Valor:"													,oFont8)

oPrint:Say (nRow2+1000,1810,"(=) Valor do Documento:"									,oFont8)

cString := Alltrim(Transform(aDadosTit[5],"@E 99,999,999.99"))

nCol := 1796+(374-(len(cString)*22))
oPrint:Say (nRow2+1030,nCol,cString ,oFont11c)

oPrint:Say (nRow2+1070,100 ,OemToAnsi("Instruções de responsabilidade do BENEFICIÁRIO. Qualquer dúvida sobre este boleto, contate o BENEFICIÁRIO."),oFont8)

oPrint:Say (nRow2+1120,120 ,"^ ^ VALORES EXPRESSOS EM REAIS ^^^^ ^",oFont10)
oPrint:Say (nRow2+1170,120 ,"JUROS POR DIA DE ATRASO..........." + Alltrim(Transform(Round(aDadosTit[5]/300,2),"@E 99,999,999.99")) ,oFont10)
oPrint:Say (nRow2+1220,120,"Boleto Ref. NF "+SE1->E1_PREFIXO + "-" + SE1->E1_NUM + " SUJEITO A PROTESTO APÓS VENCIMENTO",oFont10)

oPrint:Say (nRow2+1070,1810,"(-)Desconto/Abatimento"									,oFont8)
oPrint:Say (nRow2+1140,1810,"(-)Outras Deduções"										,oFont8)
oPrint:Say (nRow2+1210,1810,"(+)Mora/Multa"												,oFont8)
oPrint:Say (nRow2+1280,1810,"(+)Outros Acréscimos"										,oFont8)
oPrint:Say (nRow2+1350,1810,"(=)Valor Cobrado"											,oFont8)

oPrint:Say (nRow2+1420,100 ,"Pagador:"													,oFont8)
oPrint:Say (nRow2+1450,370 ,aDatSacado[1]+" ("+aDatSacado[2]+")"						,oFont10)
oPrint:Say (nRow2+1503,370 ,aDatSacado[3]												,oFont10)
oPrint:Say (nRow2+1566,370 ,aDatSacado[6]+"    "+aDatSacado[4]+" - "+aDatSacado[5]		,oFont10)		// CEP+Cidade+Estado

if aDatSacado[8] = "J"
	oPrint:Say (nRow2+1450,1750 ,"CNPJ: "+TRANSFORM(aDatSacado[7],"@R 99.999.999/9999-99"),oFont10) 	// CGC
Else
	oPrint:Say (nRow2+1450,1750 ,"CPF: "+TRANSFORM(aDatSacado[7],"@R 999.999.999-99")	,oFont10) 		// CPF
EndIf

oPrint:Say (nRow2+1625,100 ,"Pagador/Avalista"											,oFont8)

oPrint:Say (nRow2+1665+20,1500,"Autenticação Mecânica"									,oFont8)

oPrint:Line (nRow2+0710,1800,nRow2+1400,1800 )
oPrint:Line (nRow2+1120,1800,nRow2+1120,2300 )
oPrint:Line (nRow2+1190,1800,nRow2+1190,2300 )
oPrint:Line (nRow2+1260,1800,nRow2+1260,2300 )
oPrint:Line (nRow2+1330,1800,nRow2+1330,2300 )
oPrint:Line (nRow2+1400,100 ,nRow2+1400,2300 )
oPrint:Line (nRow2+1640+20,100 ,nRow2+1640+20,2300 )

// TERCEIRA PARTE
nRow3 := -180

For nI := 100 to 2300 step 50
	oPrint:Line(nRow3+1890, nI, nRow3+1890, nI+30)
Next nI

oPrint:Line (nRow3+2000,100,nRow3+2000,2300)
oPrint:Line (nRow3+2000,500,nRow3+1920, 500)
oPrint:Line (nRow3+2000,710,nRow3+1920, 710)

oPrint:SayBitmap(nRow3+1900,100,cLogo,380,090) 											// o arquivo com o logo deve estar abaixo do rootpath (Data\system)
oPrint:Say (nRow3+1970,513,aDadosBanco[1]+GetDVBanco(aDadosBanco[1])[2],oFont21 )		//Numero do Banco

//Linha Digitavel
If SA6->A6_COD == "237"
	cLinDig := MontaLinha(aDadosTit[4])
	oPrint:Say (nRow3+1934,740,cLinDig,oFont14n)										//	Linha Digitavel do Codigo de Barras
Else
	oPrint:Say (nRow3+1964,755,aCB_RN_NN[2],oFont15n)									//	Linha Digitavel do Codigo de Barras
EndIf

oPrint:Line (nRow3+2100,100,nRow3+2100,2300 )
oPrint:Line (nRow3+2200,100,nRow3+2200,2300 )
oPrint:Line (nRow3+2270,100,nRow3+2270,2300 )
oPrint:Line (nRow3+2340,100,nRow3+2340,2300 )

oPrint:Line (nRow3+2200,500 ,nRow3+2340,500 )
oPrint:Line (nRow3+2270,750 ,nRow3+2340,750 )
oPrint:Line (nRow3+2200,1000,nRow3+2340,1000)
oPrint:Line (nRow3+2200,1300,nRow3+2270,1300)
oPrint:Line (nRow3+2200,1480,nRow3+2340,1480)

oPrint:Say (nRow3+2020,100 ,"Local de Pagamento:"										,oFont8)
oPrint:Say (nRow3+2035,400 ,"PAGÁVEL EM QUALQUER BANCO ATÉ A DATA DO VENCIMENTO"		,oFont10)
oPrint:Say (nRow3+2075,400 ,"APÓS O VENCIMENTO, SOMENTE NO BANCO " + StrTran(Upper(aDadosBanco[2]), "BANCO ")		,oFont10)

oPrint:Say (nRow3+2020,1810,"Vencimento"												,oFont8)
cString := StrZero(Day(aDadosTit[4]),2) +"/"+ StrZero(Month(aDadosTit[4]),2) +"/"+ Right(Str(Year(aDadosTit[4])),4)
nCol	 	 := 1810+(374-(len(cString)*22))
oPrint:Say (nRow3+2060,nCol,cString,oFont11c)

oPrint:Say (nRow3+2120,100 ,OemToansi("Beneficiário:")									,oFont8)
oPrint:Say (nRow3+2140,100 ,AllTrim(aDadosEmp[1]+" - "+aDadosEmp[6] )					,oFont9)		//Nome + CNPJ
oPrint:Say (nRow3+2165,100 ,aDadosEmp[2]												,oFont9)		//End + Bairro
oPrint:Say (nRow3+2190,100 ,aDadosEmp[3] + " - " + aDadosEmp[4]							,oFont9)		//CEP + Compl

oPrint:Say (nRow3+2120,1810,"Agência/Código "+OemToansi("Beneficiário:")				,oFont8)

cString := StrTran(Alltrim(aDadosBanco[3]+"/"+aDadosBanco[4]+IIF(Empty(aDadosBanco[5])," ","-"+aDadosBanco[5])),'--','-')
nCol 	:= 1818+(374-(len(cString)*22))
oPrint:Say (nRow3+2160,nCol,cString ,oFont11c)

oPrint:Say (nRow3+2220,100 ,"Data do Documento:"										,oFont8)
oPrint:Say (nRow3+2250,100, StrZero(Day(aDadosTit[2]),2) +"/"+ StrZero(Month(aDadosTit[2]),2) +"/"+ Right(Str(Year(aDadosTit[2])),4), oFont10)


oPrint:Say (nRow3+2220,505 ,"Nro.Documento:"											,oFont8)
oPrint:Say (nRow3+2250,605 ,aDadosTit[1]												,oFont10)		//Numero+Parcela

oPrint:Say (nRow3+2220,1005,"Espécie Doc.:"												,oFont8)
oPrint:Say (nRow3+2250,1050,"DM"														,oFont10)		//Tipo do Titulo

oPrint:Say (nRow3+2220,1305,"Aceite:"													,oFont8)
oPrint:Say (nRow3+2250,1400,"N"															,oFont10)

oPrint:Say (nRow3+2220,1485,"Data do Processamento:"									,oFont8)
oPrint:Say (nRow3+2250,1550,StrZero(Day(aDadosTit[3]),2) +"/"+ StrZero(Month(aDadosTit[3]),2) +"/"+ Right(Str(Year(aDadosTit[3])),4)                               ,oFont10) // Data impressao


oPrint:Say (nRow3+2220,1810,"Nosso Número:"												,oFont8)
If SA6->A6_COD == "341" .Or. SA6->A6_COD == "422"
	cString := aDadosBanco[6]+"/"+Alltrim(substr(aDadosTit[6],1,8))+"-"+Alltrim(substr(aDadosTit[6],9,1))
ElseIf SA6->A6_COD == "001"
	cString := Alltrim("1225233"+aDadosTit[6])
ElseIf SA6->A6_COD == "237"
	cString := SEE->EE_CODCART + '/' + Substr(cNroDoc,1,11)+'-'+Substr(cNroDoc,12,1)
ElseIf SA6->A6_COD == "637/@/033"
	cString := aDadosTit[6]+'-'+Modulo11(aDadosTit[6])
EndIf
nCol 	 := 1854+(374-(len(cString)*22))
oPrint:Say (nRow3+2250,nCol,cString,oFont11c)

oPrint:Say (nRow3+2290,100 ,"Uso do Banco:"												,oFont8)

oPrint:Say (nRow3+2290,505 ,"Carteira:"													,oFont8)
oPrint:Say (nRow3+2320,555 ,aDadosBanco[6]												,oFont10)

oPrint:Say (nRow3+2290,755 ,"Espécie:"													,oFont8)
oPrint:Say (nRow3+2320,805 ,"R$"														,oFont10)

oPrint:Say (nRow3+2290,1005,"Quantidade:"												,oFont8)
oPrint:Say (nRow3+2290,1485,"Valor:"													,oFont8)

oPrint:Say (nRow3+2290,1810,"(=) Valor do Documento:"									,oFont8)

cString := Alltrim(Transform(aDadosTit[5],"@E 99,999,999.99"))
nCol := 1796+(374-(len(cString)*22))
oPrint:Say (nRow3+2320,nCol,cString,oFont11c)

oPrint:Say (nRow3+2360,100 ,OemToAnsi("Instruções de responsabilidade do BENEFICIÁRIO. Qualquer dúvida sobre este boleto, contate o BENEFICIÁRIO."),oFont8)

oPrint:Say (nRow3+2410,120 ,"^ ^ VALORES EXPRESSOS EM REAIS ^^^^ ^"						,oFont10)
oPrint:Say (nRow3+2460,120 ,"JUROS POR DIA DE ATRASO..........." + Alltrim(Transform(Round(aDadosTit[5]/300,2),"@E 99,999,999.99"))	,oFont10)
oPrint:Say (nRow3+2510,120,"Boleto Ref. NF "+SE1->E1_PREFIXO + "-" + SE1->E1_NUM + " SUJEITO A PROTESTO APÓS VENCIMENTO"	,oFont10)

oPrint:Say (nRow3+2360,1810,"(-)Desconto/Abatimento"									,oFont8)
oPrint:Say (nRow3+2430,1810,"(-)Outras Deduções"										,oFont8)
oPrint:Say (nRow3+2500,1810,"(+)Mora/Multa"												,oFont8)
oPrint:Say (nRow3+2570,1810,"(+)Outros Acréscimos"										,oFont8)
oPrint:Say (nRow3+2640,1810,"(=)Valor Cobrado"											,oFont8)

oPrint:Say (nRow3+2710,100 ,"Pagador:"													,oFont8)
oPrint:Say (nRow3+2720,370 ,aDatSacado[1]+" ("+aDatSacado[2]+")"						,oFont10)

if aDatSacado[8] = "J"
	oPrint:Say (nRow3+2720,1750,"CNPJ: "+TRANSFORM(aDatSacado[7],"@R 99.999.999/9999-99"),oFont10)		// CGC
Else
	oPrint:Say (nRow3+2720,1750,"CPF: "+TRANSFORM(aDatSacado[7],"@R 999.999.999-99")	,oFont10)		// CPF
EndIf

oPrint:Say (nRow3+2773,370 ,aDatSacado[3], oFont10)
oPrint:Say (nRow3+2826,370 ,aDatSacado[6]+"    "+aDatSacado[4]+" - "+aDatSacado[5]		, oFont10)		// CEP+Cidade+Estado

oPrint:Say (nRow3+2885,100 ,"Pagador/Avalista"											, oFont8)

oPrint:Line (nRow3+2000,1800,nRow3+2690,1800 )
oPrint:Line (nRow3+2410,1800,nRow3+2410,2300 )
oPrint:Line (nRow3+2480,1800,nRow3+2480,2300 )
oPrint:Line (nRow3+2550,1800,nRow3+2550,2300 )
oPrint:Line (nRow3+2620,1800,nRow3+2620,2300 )
oPrint:Line (nRow3+2690,100 ,nRow3+2690,2300 )

oPrint:Line (nRow3+2930,100,nRow3+2930,2300  )

oPrint:Say (nRow3+2950,1500,"Autenticação Mecânica - Ficha de Compensação"				, oFont8)

oPrint:FWMSBAR("INT25",68,2,aCB_RN_NN[1],oPrint,.F., Nil,.T.,0.020,1.5,.F.,"Arial",'',.F.,1,1,.T. )

For nI := 100 to 2300 step 50
	oPrint:Line(nRow3+3065, nI, nRow3+3065, nI+30)
Next nI

// Finaliza a página
oPrint:EndPage()

_cPortado := SE1->E1_PORTADO

// Guarda todos os titulos Gerados no vetor [ aTitulo]
// Verifica se o Envio e somente de Boleto
// Pesquisa no vetor1
nPosVet:=aScan(aTitulo, {|x| x[1] == cFilePrint})

If nPosVet == 0
	aAdd(aTitulo,{cFilePrint, _cNum, _cPrefix, _cParcel, cCodCli, cLojaCli, cNomCli, _cPortado, oPrint, cXFil, cXTipo })
EndIf

Return cFilePrint

/*/{Protheus.doc} CalcNoNu
	(Define nosso numero para calculo e impressao de boletos usado no boleto do bradesco)
	@type User Function
	@author Calabro'
	@since 13/10/2003
	@version version
	@return cNroDoc, character, (Nosso numero calculado com digito verificador)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function CalcNoNu(cCodCartei as character)

Local nCont		:= 0 as numeric

If Empty( SE1->E1_NUMBCO )
	cNroDoc := Right(NOSSONUM(),11)
Else
	cNroDoc := Substr(SE1->E1_NUMBCO,1,11)
EndIf

cNroDoc  := cCodCartei + cNroDoc		// Carteira + nosso numero

cCombina := "2765432765432"				// 13 posicoes
aResulta := {}

For nCont := 1 To 13
	
	nVal1 := Val( SubStr( cNroDoc,  nCont, 1 ) )
	nVal2 := Val( SubStr( cCombina, nCont, 1 ) )
	
	AAdd( aResulta, nVal1 * nVal2 )
Next

nTotProd  := 0
For nCont := 1 To Len(aResulta)
	nTotProd := nTotProd + aResulta[ nCont ]
Next

nResulta := Int(nTotProd / 11)
nResto   := nTotProd - ( nResulta * 11 )

If nResto >= 1
	
	_cDigito := Alltrim(Str( 11 - nResto))
	
	if _cDigito == "10"
		cDigVerif := "P"
	Else
		cDigVerif := Alltrim(Str( 11 - nResto))
	EndIf
Else
	cDigVerif := "0"
EndIf

cNroDoc  := Substr(cNroDoc,3,11) + cDigVerif

Return cNroDoc

/*/{Protheus.doc} Ret_CB
	(Montagem do código de barras)
	@type Static Function
	@author Calabro'
	@since 13/10/2003
	@version version
	@param cBanco, character, (Numero do banco)
	@param cAgencia, character, (Numero da agencia)
	@param cConta, character, (Numero da conta)
	@param cNroDoc, character, (Nosso numero)
	@param nValor, numeric, (Valor do titulo)
	@param dVencto, date, (Data de vencimento do titulo)
	@return aRet, array, (Array contendo os dados do codigo de barras:
							[1] - Codigo de barras
							[2]-Nosso numero convertido com zeros a esquerda)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function Ret_CB(	cBanco as character,;
						cAgencia as character,;
						cConta as character,;
						cNroDoc as character,;
						nValor as numeric,;
						dVencto as date)

Local cCodigoBar	:= "" as character
Local cValorFinal   := StrZero(nValor * 100,10) as character
Local cNN			:= StrZero(Val(Substr(cNroDoc,1,11)),11) as character
Local cFator      	:= StrZero(dVencto - ctod("07/10/97"),4) as character
Local cDigBar 		:= " " as character										// dígito verificador do código de barras

// Primeira parte - Posição 01 a 19
cCodigoBar := cBanco + "9" + cDigBar + cFator + cValorFinal

// Segunda parte - Campo Livre
cCodigoBar += SubStr(cAgencia,1,4)								//Tamanho 04 - Posição 20 a 23
cCodigoBar += "09"												//Tamanho 02 - Posição 24 a 25
cCodigoBar += cNN												//Tamanho 11 - Posição 26 a 36
cCodigoBar += "0118788"											//Tamanho 07 - Posição 37 a 43
cCodigoBar += "0"												//Tamanho 01 - Posição 44

// Adiciona dígito verificador a posição 5
cCodigoBar := calcDigBar(cCodigoBar)

Return {cCodigoBar,"",cNN}

/*/{Protheus.doc} calcDigBar
	(Cálculo do dígito verificador do código de barras)
	@type Static Function
	@author Calabro'
	@since 13/10/2003
	@version version
	@param cCodCalc, character, (Codigo de barras a ser calculadoo digito verificador)
	@return return, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function calcDigBar(cCodCalc as character)

Local nFator	:= 0 as numeric
Local nTot		:= 0 as numeric
Local nDigito	:= 0 as numeric
Local nResto	:= 0 as numeric

// Retira posição 5 para cálculo do dígito verificador
cCodCalc := SubStr(cCodCalc,1,4) + SubStr(cCodCalc,6,39)

n := Len(cCodCalc)		// quantidade de posições (43)
nFator := 2				// Fator inicial

// Varre as posições da direita para a esquerda
While n > 0
	
	If nFator == 10
		nFator := 2
	EndIf
	
	nTot += Val(SubStr(cCodCalc, n, 1)) * nFator
	
	nFator++
	n--
EndDo

// Resto da divisão por 11
nResto := Mod(nTot,11)

// Subtrai de 11
nDigito := 11 - nResto

If nDigito == 0 .Or. nDigito == 10 .Or. nDigito == 11
	nDigito := 1
EndIf

// Adiciona dígito verificador
cCodCalc := SubStr(cCodCalc,1,4) + AllTrim(Str(nDigito)) + SubStr(cCodCalc,5,39)

Return cCodCalc

/*/{Protheus.doc} Ret_cBarra
	(Funcao para fazer a composicao do codigo de barras)
	@type Static Function
	@author Calabro'
	@since 13/02/2004
	@version version
	@param cAgencia, character, (Codigo da agencia bancaria)
	@param nValor, numeric, (Valor do titulo)
	@param cCart, character, (Numero da carteira no banco)
	@param cMoeda, character, (Moeda a ser considerada no boleto: 9 - Real)
	@return aRet, array, (Array com dados do codigo de barra:
							[1]-Codigo de Barras
							[2]-Codigo de barras em linha digitavel
							[3]-Nosso numero)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function Ret_cBarra(	cAgencia as character,;
							nValor as numeric,;
							cCart as character,;
							cMoeda as character	)

Local cNosso		:= "" as character
Local cDigNosso		:= "" as character
Local cCampoL		:= "" as character
Local cFatorValor	:= "" as character
Local cLivre		:= "" as character
Local cDigBarra		:= "" as character
Local cBarra		:= "" as character
Local cParte1		:= "" as character
Local cDig1			:= "" as character
Local cParte2		:= "" as character
Local cDig2			:= "" as character
Local cParte3		:= "" as character
Local cDig3			:= "" as character
Local cParte4		:= "" as character
Local cParte5		:= "" as character
Local cDigital		:= "" as character
Local cX6SantSof	:= "" as character
Local cBanco		:= SA6->A6_COD as character

Local aRet			:= {} as array

cAgencia:= STRZERO(Val(cAgencia),4)
cNosso 	:= ""

If SA6->A6_COD == "001"
	
	// Nosso Numero
	If !Empty(SE1->E1_NUMBCO)
		cNosso := SE1->E1_NUMBCO
	Else
		cNosso := GetMV("ES_SQNUMBB",, "0")
		cNosso := StrZero(Val(cNosso)+1,10)
		
		// Gravo o numero sequencia do Banco do Brasil no Arquivo de Parametros
		PutMV("ES_SQNUMBB",cNosso)
	EndIf
	
	
	cFatorValor  := fator1() + Strzero(nValor * 100,10)
	cConvenio := "1225233"
	
	cCampoL := "000000" + cConvenio + alltrim(cNosso) + cCart
	
	cLivre 	:= cBanco + cMoeda + cFatorValor + cCampoL
	
	// campo do codigo de barra
	cDigBarra := CALC_Dp( cLivre )

	// Código Banco (3) + Moeda (1) + DAC código barras (1) + Fator Venc (4) + Valor (10) + cCampoL
	cBarra    := Substr(cLivre,1,4) + cDigBarra + cFatorValor + Substr(cCampoL,1,25)

	// composicao da linha digitavel
	cParte1  := cBanco + cMoeda + SUBSTR(cCampoL,1,5)
	cDig1    := DIGIT0001( cParte1 )
	cParte2  := SUBSTR(cCampoL,6,10)
	cDig2    := DIGIT0001( cParte2 )
	cParte3  := SUBSTR(cCampoL,16,10)
	cDig3    := DIGIT0001( cParte3 )
	
	cParte4  := " " + cDigBarra + " "
	cParte5  := cFatorValor
	
	cDigital := substr(cParte1,1,5) + "." + substr(cparte1,5,4) + cDig1 + " "
	cDigital += substr(cParte2,1,5)	+ "." + substr(cparte2,6,5) + cDig2 + " "
	cDigital += substr(cParte3,1,5)	+ "." + substr(cparte3,6,5) + cDig3 + " "
	cDigital += cParte4
	cDigital += cParte5

ElseIf SA6->A6_COD == "341"

	// Nosso Numero
	If !Empty(SE1->E1_NUMBCO)
		cNosso 		:= alltrim(SE1->E1_NUMBCO)
		cDigNosso  	:= CALC_diE(cCart + cNosso)
		cNosso		:= cNosso + cDigNosso
	Else
		cNosso   := GetMV("ES_SQNUMIT",, "0")
		cDigNosso:= CALC_diE(cCart + cNosso)
		cNosso	:= cNosso + cDigNosso
	EndIf
	
	cNosso := Alltrim(cNosso)
	
	If nValor > 0
		cFatorValor  := fator1() + Strzero(nValor * 100,10)
	Else
		cFatorValor  := fator1() + strzero(SE1->E1_VALOR * 100,10)
	EndIf

	// Carteira (3) + Nosso Número (8) + DAC [Agência /Conta/Carteira/Nosso Número](1) + Agencia (4) + Conta (5) +
	// DAC [Agência/Conta Corrente] (1) + 3 zeros
	// cCampoL := cCart + cNosso + "0174326264000"
	cCampoL := cCart + cNosso + AllTrim(SA6->A6_AGENCIA) + AllTrim(SA6->A6_NUMCON) + AllTrim(SA6->A6_DVCTA) + "000"

	cLivre 	:= cBanco + cMoeda + cFatorValor + cCampoL

	// campo do codigo de barra
	cDigBarra := CALC_Dp( cLivre )

	// Código Banco (3) + Moeda (1) + DAC código barras (1) + Fator Venc (4) + Valor (10) + cCampoL
	cBarra := cBanco + cMoeda + cDigBarra + cFatorValor + Substr(cCampoL,1,25)

	// composicao da linha digitavel
	cParte1  := cBanco + cMoeda + SUBSTR(cCampoL,1,5)
	cDig1    := DIGIT0001( cParte1 )
	cParte2  := SUBSTR(cCampoL,6,10)
	cDig2    := DIGIT0001( cParte2 )
	cParte3  := SUBSTR(cCampoL,16,10)
	cDig3    := DIGIT0001( cParte3 )

	cParte4  := " " + cDigBarra + " "
	cParte5  := cFatorValor

	cDigital := substr(cParte1,1,5)	+ "." + substr(cparte1,6,4) + cDig1 + " "
	cDigital += substr(cParte2,1,5)	+ "." + substr(cparte2,6,5) + cDig2 + " "
	cDigital += substr(cParte3,1,5)	+ "." + substr(cparte3,6,5) + cDig3 + " "
	cDigital += cParte4
	cDigital += cParte5

ElseIf SA6->A6_COD == "422"

	// Montagem do NOSSO NUMERO
	If !Empty(SE1->E1_NUMBCO)
		cNosso := Left(SE1->E1_NUMBCO,8)
	Else
		cNosso := GetMV("ES_SQNUMSF",, "0")
		cNosso := StrZero(Val(cNosso)+1,8)
		// Gravo o numero sequencia do Banco Safra no Arquivo de Parametros
		PutMV("ES_SQNUMSF",cNosso)
	EndIf

	// Complementa o digito do Nosso Numero
	cNosso := cNosso+Modulo10("1248"+"02341"+"109"+cNosso)
	cNosso := Alltrim(cNosso)

	// Composicao da informacao do codigo de barras
	cB001003 := "341"
	cB004004 := "9"
	CB006009 := Fator1()
	cB010019 := Strzero(nValor * 100,10)
	cB020044 := "109"+cNosso+"1248023416"+"000"
	cB005005 := CALC_Dp(cB001003+cB004004+cB006009+cB010019+cB020044)

	// Codigo de barras completo
	cBarra  := cB001003+cB004004+cB005005+cB006009+cB010019+cB020044

	// Composicao da Linha digitavel
	cDigital := Substr(cBarra,01,03)
	cDigital += Substr(cBarra,04,01)
	cDigital += Substr(cBarra,20,05)
	cDigital += DIGIT0001(Substr(cBarra,01,03)+Substr(cBarra,04,01)+Substr(cBarra,20,05))
	cDigital += Substr(cBarra,25,10)
	cDigital += DIGIT0001(Substr(cBarra,25,10))
	cDigital += Substr(cBarra,35,10)
	cDigital += DIGIT0001(Substr(cBarra,35,10))
	cDigital += Substr(cBarra,05,01)
	cDigital += Substr(cBarra,06,14)

	//Composicao / Formatacao da Linha digitavel
	//42297.00408 00002.782472 26173.001111 8 1001000008084
	//XXXXX.XXXXX XXXXX.XXXXXX XXXXX.XXXXXX X XXXXXXXXXXXXX
	cDigital :=;
	Substr(cDigital,01,05) + "." + ;
	Substr(cDigital,06,05) + " " + ;
	Substr(cDigital,11,05) + "." + ;
	Substr(cDigital,16,06) + " " + ;
	Substr(cDigital,22,05) + "." + ;
	Substr(cDigital,27,06) + " " + ;
	Substr(cDigital,33,01) + " " + ;
	Substr(cDigital,34,14)
	
ElseIf SA6->A6_COD $ "033/#/637"

	// Montagem do NOSSO NUMERO
	If !Empty(SE1->E1_NUMBCO)
		cNosso := Left(SE1->E1_NUMBCO,12)
	Else

		cX6SantSof := If(SA6->A6_COD == "033", "ES_SQNUMSA", "ES_SQNUMSO")

		// Gravo o numero sequencia do Banco Santander no Arquivo de Parametros
		cNosso := GetMV(cX6SantSof,, "0")
		cNosso := StrZero(Val(cNosso) + 1 ,12)
		PutMV(cX6SantSof, cNosso)
	EndIf

	cB001003 := "033"
	cB004004 := "9"
	CB006009 := Strzero(dVENCREA - STOD("19971007"),4)
	cB010019 := Strzero(nValor * 100,10)
	cB020020 := "9"
	cB021027 := "4845013"
	cB028040 := cNosso+Modulo11(cNosso)
	cB041041 := "0"
	cB042044 := "102"
	cB005005 := Modulo11(cB001003+cB004004+CB006009+cB010019+cB020020+cB021027+cB028040+cB041041+cB042044)

	// Codigo de barras completo
	cBarra  := cB001003+cB004004+cB005005+CB006009+cB010019+cB020020+cB021027+cB028040+cB041041+cB042044

	// Composicao da Linha digitavel
	_cBloco1 := cB001003+cB004004+cB020020+Substr(cB021027,01,04)
	//          XXX      X         X        XXXX
	_cBloco1 += Modulo10(_cBloco1)
	//          X
	_cBloco2 := Substr(cB021027,05,03)+Left(cB028040,7)
	//          XXX                     XXXXXXX
	_cBloco2 += Modulo10(_cBloco2)
	//          X
	_cBloco3 := Substr(cB028040,08,06)+cB041041+cB042044
	//          XXXXXX                  X        XXX
	_cBloco3 += Modulo10(_cBloco3)
	//          X
	_cBloco4 := cB005005
	//          X
	_cBloco5 := CB006009+cB010019
	//          XXXX      XXXXXXXXXX

	// Composicao / Formatacao da Linha digitavel
	// 42297.00408 00002.782472 26173.001111 8 1001000008084
	// XXXXX.XXXXX XXXXX.XXXXXX XXXXX.XXXXXX X XXXXXXXXXXXXX
	cDigital += _cBloco1+_cBloco2+_cBloco3+_cBloco4+_cBloco5
	cDigital :=;
	Substr(cDigital,01,05) + "." + ;
	Substr(cDigital,06,05) + " " + ;
	Substr(cDigital,11,05) + "." + ;
	Substr(cDigital,16,06) + " " + ;
	Substr(cDigital,22,05) + "." + ;
	Substr(cDigital,27,06) + " " + ;
	Substr(cDigital,33,01) + " " + ;
	Substr(cDigital,34,14)
EndIf

AAdd(aRet,cBarra)		// Codigo de Barras
AAdd(aRet,cDigital)		// Codigo de barras em linha digitavel
AAdd(aRet,cNosso)		// Nosso numero

Return aRet

/*/{Protheus.doc} CALC_diE
	(Para calculo do nosso numero do banco do brasil)
	@type Static Function
	@author Calabro'
	@since 13/02/2004
	@version version
	@param cNosso, character, (Nosso numero do boleto)
	@return _cDac, character, (Digito de auto conferencia - DAC - calculada)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function CALC_diE(cNosso as character)

// Local _cCodigo		:= "017432626" + cNosso as character
Local _cCodigo		:= AllTrim(SA6->A6_AGENCIA) + AllTrim(SA6->A6_NUMCON) + cNosso as character
Local _cDac			:= "" as character

Local _nSoma		:= 0 as numeric
Local _nItem		:= 0 as numeric
Local nVarAux		:= 0 as numeric
Local nX			:= 0 as numeric

For nX := 1 to Len(_cCodigo)
	
	_nItem := val(substr(_cCodigo,nX,1))
	
	// Quando estiver em uma casa par, multiplica por dois
	If mod(nX,2) == 0
		If _nItem * 2 >= 10
			_nSoma += (_nItem * 2) - 9	// Exemplo do calculo 6*2 = 12 logo 1+2 = 3 ou 12 - 9 = 3
		Else
			_nSoma += _nItem * 2
		EndIf
	Else
		_nSoma += _nItem
	EndIf
Next nX

nVarAux := mod(_nSoma,10)

// Se resto da divisão for zero, dac é zero
If nVarAux == 0
	_cDac := "0"
Else
	_cDac := alltrim(str(10 - nVarAux))
EndIf

Return(_cDac)

/*/{Protheus.doc} DIGIT0001
	(Funcao para calculo dos digitos verificadores da linha digitavel)
	@type Static Function
	@author Calabro'
	@since 13/02/2004
	@version version
	@param cVariavel, character, (Trecho do codigo de barras a calcular o digito verificador)
	@return cDigVer, character, (Digito verificador calculado)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function DIGIT0001(cVariavel as character)

Local cBase		:= "" as character
Local cValor	:= "" as character

Local nVarAux	:= 0 as numeric
Local nSumDig	:= 0 as numeric
Local nBase		:= 0 as numeric
Local nSegVar	:= 2 as numeric
Local nDigito	:= 0 as numeric
Local nDezena	:= 0 as numeric

cBase := cVariavel
nBase := Len(cBase)
nDigito := nBase

While nDigito >= 1
	nVarAux   	:= Val(SubStr(cBase, nDigito, 1)) * nSegVar
	nSumDig 	:= nSumDig+If (nVarAux < 10, nVarAux, (nVarAux - 9))
	nSegVar 	:= 3 - nSegVar
	nDigito	:= nDigito - 1
EndDo

cValor	:= AllTrim(Str(nSumDig,12))
nDezena	:= Val(AllTrim(Str(Val(SubStr(cValor,1,1))+1,12))+"0")
nVarAux := nDezena - nSumDig

If nVarAux >= 10
	nVarAux := 0
EndIf

Return Str(nVarAux,1,0)

/*/{Protheus.doc} Fator1
	(Calculo do FATOR1  de vencimento para linha digitavel)
	@type Static Function
	@author Calabro'
	@since 13/02/2004
	@version version
	@return cFator, character, (Fator de vencimento da linha digitavel)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static function Fator1()

Local cData		:= "" as character

If Len(AllTrim(SubStr(DToC(dVencRea),7,4))) = 4
	cData := SubStr(DToC(dVencRea),7,4)+SubStr(DToC(dVencRea),4,2)+SubStr(DToC(dVencRea),1,2)
Else
	cData := "20"+SubStr(DToC(dVencRea),7,2)+SubStr(DToC(dVencRea),4,2)+SubStr(DToC(dVencRea),1,2)
EndIf
cFator := Str(1000+(SToD(cData) - SToD("20000703")),4)

Return(cFator)

/*/{Protheus.doc} CALC_Dp
	(Calculo do digito do nosso numero)
	@type Static Function
	@author Calabro'
	@since 13/02/2004
	@version version
	@param cVariavel, character, (Variavel base para calculo do digito)
	@return cFator, character, (Fator de vencimento da linha digitavel)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function CALC_Dp(cVariavel as character)

Local cBase		:= "" as character

Local nVarAux	:= 0 as numeric
Local nSumDig	:= 0 as numeric
Local nBase		:= 0 as numeric
Local nBase2	:= 2 as numeric
Local nDigito	:= 0 as numeric

cBase := cVariavel
nBase := Len(cBase)
nSumDig := 0
nVarAux := 0
nDigito := nBase

While nDigito >= 1
	If nBase2 >= 10
		nBase2 := 2
	EndIf
	nVarAux := Val(SubStr(cBase, nDigito, 1)) * nBase2
	nSumDig := nSumDig + nVarAux
	nBase2 := nBase2 + 1
	nDigito := nDigito - 1
EndDo

nVarAux := Mod(nSumDig,11)
If nVarAux == 0 .or. nVarAux == 1 .or. nVarAux >= 10
	nVarAux := 1
Else
	nVarAux := 11 - nVarAux
EndIf

Return Str(nVarAux,1,0)

/*/{Protheus.doc} MontaLinha
	(Monta linha digitavel para impressao de boletos do banco bradesco)
	@type Static Function
	@author Calabro'
	@since 13/02/2004
	@version version
	@param dDataCalc, date, (Data a ser considerada no calculo)
	@return cLineDig, character, (Linha digitavel concatenada)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function MontaLinha(dDataCalc as date)

Local cDvLinh		:= "" as character
Local cLineDig		:= "" as character
Local cFatorVcto	:= CToD("") as character
Local cBloco		:= "" as character

dDataCalc := If(Empty(dDataCalc), CToD(""), dDatabase)

cFatorVcto := Str( ( dDataCalc - Ctod("07/10/1997") ), 4 )

// Código de barras
cCodBarras := aCB_RN_NN[1]

//Digito Verificador do Codigo de Barras
cDVercb := SubStr(cCodBarras,5,1)

// Primeiro Campo
// Codigo do Banco (3) + Moeda (1) + 5 primeiras posições do campo livre do Cod Barras --> Tamanho 9 +  dígito verificador
cBloco := Substr(cCodBarras,1,3) + Substr(cCodBarras,4,1) + Substr(cCodBarras,20,5)
cDvLinh := DV_LINHA(cBloco)

cLineDig := Substr(cCodBarras,1,3) + Substr(cCodBarras,4,1) + Substr(cCodBarras,20,1) + "." + Substr(cCodBarras,21,4) + cDvLinh + Space(2)

// Segundo Campo
// Posições 6 a 15 do campo livre --> tamanho 10 + digito verificador
cBloco    := Substr(cCodBarras,25,10)
cDvLinh    := DV_LINHA(cBloco)
cLineDig   += Substr(cBloco,1,5) + "." + Substr(cBloco,6,5) + cDvLinh + Space(2)

// Terceiro Campo
// Posições 6 a 15 do campo livre --> tamanho 10 + digito verificador
cBloco  := Substr(cCodBarras,35,10)
cDvLinh  := DV_LINHA(cBloco)
cLineDig += Substr(cBloco,1,5) + "." + Substr(cBloco,6,5) + cDvLinh + Space(2)

// Quarto Campo
// Dígito verificador do código de barras --> Tamanho 1
cLineDig += cDVercb + Space(2)


// Quinto Campo
// Fator de vencimento (4) + valor do documento (10)
cLineDig  := cLineDig + cFatorVcto + StrZero(Round(nVlrBol,2) * 100,10)

Return cLineDig

/*/{Protheus.doc} DV_LINHA
	(Calculo do Digito da Linha Digitavel)
	@type Static Function
	@author Calabro'
	@since 13/02/2004
	@version version
	@param cBloco, character, (Bloco do codigo de barras para calcular o digito verificador)
	@return cDigito, character, (Digito verificador calculado)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function DV_LINHA(cBloco as character)

Local cDigito	:= "" as character

Local nPeso		:= 2 as numeric 	//Inicia peso em 2
Local nCont		:= 0 as numeric
Local nX		:= 0 as numeric
Local nResto	:= 0 as numeric
Local nDezena	:= 0 as numeric

//Varre do fim ao início
For nX := Len(cBloco) to 1 Step -1
	
	//Se a soma der 10 ou mais, soma os algarítmos (exemplo: 2x7 = 14 --> 1+4 = 5)
	If Val(SubStr(cBloco, nX, 1)) * nPeso >= 10
		
		nVal  := Val(SubStr(cBloco, nX, 1)) * nPeso
		nCont += Val(SubStr(Str(nVal, 2), 1, 1)) + Val(SubStr(Str(nVal, 2), 2, 1))
	Else
		nCont += Val(SubStr(cBloco, nX, 1)) * nPeso
	EndIf
	
	If nPeso == 1
		nPeso := 2
	Else
		nPeso := 1
	EndIf
Next nX

nDezena  := Substr(Str(nCont, 2) ,1 , 1)
nResto   := ( (Val(nDezena) + 1) * 10) - nCont

If nResto == 10
	cDigito := "0"
Else
	cDigito := Str(nResto,1)
EndIf

Return cDigito

/*/{Protheus.doc} Modulo11
	(Calcula o modulo 11 para a string enviada por parametro)
	@type Static Function
	@author Calabro'
	@since 31/07/2014
	@version version
	@param cStr, character, (String a ser considerada no calculo)
	@param nMultIni, numeric, (Fator de multiplicacao inicial)
	@param nMultFim, numeric, (Fator de multiplicacao final)
	@return cRet, character, (Digito convertido por modulo 11)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function Modulo11(cStr as character,nMultIni as numeric, nMultFim as numeric)

Local cChar		:= "" as character

Local nX		:= 0 as numeric
Local nModulo	:= 0 as numeric
Local nMult		:= 0 as numeric

nMultIni := Iif( Empty(nMultIni), 2, nMultIni )
nMultFim := Iif( Empty(nMultFim), 9, nMultFim )

nMult := nMultIni
cStr := AllTrim(cStr)

For nX := Len(cStr) to 1 Step -1
	cChar := Substr(cStr, nX, 1)
	If isAlpha( cChar )
		Help(" ", 1, "ONLYNUM")
		Return .f.
	End
	nModulo += Val(cChar)*nMult
	nMult:= IIf(nMult==nMultfim,2,nMult+1)
Next nX

nRest := nModulo % 11

nRest := IIf(nRest==0 .or. nRest==1, 1, 11 - nRest)

Return Str(nRest,1)

/*/{Protheus.doc} RFA01EnvBol
	(Rotina que envia e-mail de boletos ou boletos + DANFE)
	@type Static Function
	@author Calabro'
	@since 12/07/2015
	@version version
	@param aTitulo, array, (Array com as informacoes dos titulos a serem enviados por e-mail)
	@param aDanfes, array, (Array com o caminho das DANFES em PDF geradas)
	@param aDanfes, array, (Array com o caminho dos XMLs gerados)
	@param lJob, logical, (Verifica se processo esta' em modo job ou via tela)
	@return Nil, Nulo
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function RFA01EnvBol(aTitulo as array,;
							aDanfes as array,;
							aXML as array,;
							lJob as logical)

Local cTitulo		:= "" as character											// registro
Local cArqPDF		:= "" as character											// Nome do arquivo
Local cCadWF		:= AllTrim(GetMV("ES_MAILBOX",, "")) as character			// Nome da conta Workflow cadastrada
Local cPopAdd		:= "" as character											// Endereço do Servidor POP
Local cSmtpAdd		:= "" as character											// Endereço do Servidor SMTP
Local cUser			:= "" as character											// email do destinatario
Local cPass			:= "" as character											// Senha do Servidor
Local cRecebe		:= "" as character											// Retorno -> Utilizado para verificar qual o tipo de email o usuario selecionou
Local cChaveNfe		:= "" as character											// Guarda a chave da Nota Fiscal
Local cHtml			:= "" as character											// Guarda o Texto feito em HTML
Local cNFEs			:= "" as character											// Pega o Numero da Nota Fiscal de Serviço
Local _cCliente		:= "" as character
Local _cLoja		:= "" as character
Local cLayHTML		:= AllTrim(GetMV("ES_RF01HTM",, "")) as character
Local cUsrAuth		:= "" as character
Local cPswAuth		:= "" as character
Local cProtocSec	:= "" as character
Local cFrom			:= "" as character

Local nCont			:= 0 as numeric												// Contador
Local nX			:= 0 as numeric												// Contador
Local nPos			:= 0 as numeric												// Posicao do vetor
Local nErro			:= 0 as numeric												// Erro da funcao
Local nPopPort		:= 0 as numeric												// Porta do Servidor POP     (110)
Local nSmtpPort		:= 0 as numeric												// Porta do Servidor SMTP    (587)
Local nConfirmou	:= 0 as numeric												// Retorno -> Verifica se o usuario confirmou ou cancelou através da rotina (MDTEC02)
Local nOpc			:= 0 as numeric	 

Local lPermite		:= .F. as logical											// Parâmetro que permite ou não envio de link de RPS com o campo Chave de Acesso em branco
Local lSSL			:= .F. as logical											// Informa se caixa possui protocolo SSL ativo

Local aFiles		:= {} as array												// Localiza todos os registros contigos na na pasta informada
Local aTotArq		:= {} as array												// Verifica a quantidade de registro na pasta
Local aBolEnv		:= {} as array												// Vetor que verifica se existe boletos a serem enviados
Local aFilBol		:= {} as array												// Vetor que armazena os registros que serão enviados e excluidos
Local aEmails		:= {} as array												// Array para o Parambox para adicionar mais e-mails
Local aAreas		:= {GetArea()}

Local oMailServer := TMailManager():New() as object								 // Objeto função de enviar e-mail
Local oMessage    := TMailMessage():New() as object								 // Atributo do Objeto

DbSelectArea("WF7")
DbSetOrder(1)		//WF7_FILIAL+WF7_PASTA
If WF7->( DbSeek(xFilial("WF7")+cCadWF))
	cPopAdd := AllTrim(WF7->WF7_POP3SR)
	cSmtpAdd := AllTrim(WF7->WF7_SMTPSR)
	nPopPort := WF7->WF7_POP3PR
	nSmtpPort := WF7->WF7_SMTPPR
	cUser := AllTrim(WF7->WF7_CONTA)
	cPass := AllTrim(WF7->WF7_SENHA)
	cUsrAuth := AllTrim(WF7->WF7_AUTUSU)
	cPswAuth := AllTrim(WF7->WF7_AUTSEN)
	cProtocSec := AllTrim(WF7->WF7_SMTPSE)
	lSSL := WF7->WF7_SSL
	cFrom := AllTrim(WF7->WF7_REMETE)
Else
	cPopAdd := ""
	cSmtpAdd := "wikitec.smtp.com.br"
	nPopPort := 0
	nSmtpPort := 587
	cUser := "teste@wikitec.com.br"
	cPass := "wikitec123"
	cUsrAuth := "teste@wikitec.com.br"
	cPswAuth := "wikitec123"
	cFrom := AllTrim(GetMv("ES_BOLFROM",,"noreply@nomedaempresa.com.br"))
EndIf

// Busca todos os arquivos do local em pdf e guarda no vetor
aFiles  := Directory(CDIRPDF + "*.PDF", "D") 

// Apresenta os dados dos arquivos encontrado na pasta
nCont := Len( aFiles )
For nX := 1 to nCont
	cArq := aFiles[nX,1]
	aAdd(aTotArq, cArq )
Next nX

nCont := Len(aTitulo)
nX := 1

While nX <= nCont
	
	cTitulo:= AllTrim(aTitulo[nX][1])+".PDF"
	nPos := aScan(aTotArq, {|x| Upper(x) == Upper(cTitulo)}) //Pesquisa no vetor
	
	If nPos == 0
		MsgAlert("Não foi possivel enviar o boleto [ "+cTitulo+" ] pois o mesmo não encontra - se na pasta [ "+CDIRPDF+" ] ")
	Else
		aAdd(aBolEnv,{cTitulo})
	EndIf
		
	nX++
	
EndDo

nX:= 1
nCont := Len(aBolEnv)
nPos := 0

While nX <= nCont

	cArqPDF := aBolEnv[nX][1]

	nPos:= aScan(aFilBol, {|x| x == cArqPDF}) //Pesquisa no vetor

	If nPos == 0
		aAdd(aFilBol,CDIRPDF+cArqPDF)
	EndIf

	nX++
EndDo

nCont := Len(aBolEnv)

// Verifica se exitem boletos a serem enviados
If nCont > 0
	
	// Posiciona na tabela de SA1 para
	// pegar os dados do cliente
	DbSelectArea("SA1")
	DbSetOrder(1)
	If DbSeek(xfilial("SA1")+aTitulo[1][5]+aTitulo[1][6])

		// Verifica se precisa utilizar protocolo de seguranca SSL para envio de e-mails
		If "SSL" $ cProtocSec .OR. lSSL
			oMailServer:SetUseSSL(.T.)
		EndIf

		// Verifica se precisa utilizar protocolo de seguranca TSL para envio de e-mails
		If "TLS" $ cProtocSec
			oMailServer:SetUseTLS(.T.)
		EndIf
 
		// Pega as configurações informadas do servidor
		nErro := oMailServer:Init( "", cSmtpAdd, cUser, cPass, , nSmtpPort )
		If nErro <> 0
			GeraMsgErro("Nao foi possivel inicializar o servidor SMTP: "  + oMailServer:getErrorString(nErro), lJob)
		EndIf

		// Valida as configurações do servidor para envio de e-mail
		nErro := oMailServer:SmtpConnect()
		If nErro <> 0
			GeraMsgErro("Não conectou: "  + oMailServer:getErrorString(nErro), lJob)
			Return
		EndIf
		
		// Autenticação do Servidor
		If nErro == 0 .AND. !Empty(cUsrAuth) .AND. !Empty(cPswAuth)
			nErro := oMailServer:smtpAuth(cUsrAuth, cPswAuth)
			If nErro <> 0
				GeraMsgErro("[ERROR]Falha ao autenticar: " + oMailServer:getErrorString(nErro), lJob)
				oMailServer:smtpDisconnect()
				Return
			EndIf
		EndIf
		
		// Limpa o objeto caso existe alguma informação
		oMessage:Clear()

		// Traz o e-mail do contato do cliente filtrado pela codigo do cliente e loja
		// atraves da rotina MDTEC02 -> filtro de contatos cadastrado para o cliente
		
		nConfirmou 	:= 1
		
		// Busca email do cadastro de cliente
		cRecebe 	:= Alltrim(SA1->A1_EMAIL) //Email

		If Vazio(cRecebe)
			GeraMsgErro("Cadastro de email selecionado em branco.", lJob)
			nConfirmou := 0
		EndIf

		// Se for email do cliente ou usuário selecionou um email de contato, nConfirmou == 1
		If nConfirmou == 1 .AND. !lJob

			aAdd(aEmails,{1,"e-mails:",Space(100),"","","","",80,.T.})
			While nOpc == 0 .OR. nOpc == 3 
				cAlert 	:= "Os dados do cliente para envio do Boleto estão corretos ? "+CRLF+CRLF
				
				cAlert 	+= "Codigo:  " + SA1->A1_COD +" Loja: "+SA1->A1_LOJA +CRLF
				cAlert 	+= "Cliente: " + SA1->A1_NOME +CRLF
				
				cAlert 	+= "Email: "   + cRecebe + CRLF
				
				cAlert 	+= "Titulo: "  + aTitulo[1][2]+CRLF
				cAlert 	+= "Prefixo: " + aTitulo[1][3]+CRLF
				
				nOpc 	:= Aviso("Aviso", cAlert ,{'Sim','Não','&Adic. E-mails'},3, "Envio de Boleto - EnviaEmail")
				If nOpc == 3
					ParamBox(aEmails ,"Parametros ",aRet)
					If Len(aRet) > 0 .And. !Empty(aRet[1])
						cRecebe += ";" + AllTrim(aRet[1])
					EndIf
				EndIf
			EndDo
		EndIf

		// Caso a Opção seja "Não"
		// Exclui os Boletos/O.S Gerados
		// nConfirmou == 0 indica que usuário não selecionou email do contato
		// nOpc == 2 indica que usuário cancelou
		If nConfirmou == 0 .Or. nOpc == 2
			
			// Exclui O.S e Boletos Enviada
			For nX := 1 to Len(aFilBol)
				If FErase(aFilBol[nX]) == -1
					GeraMsgErro("Falha ao tentar deletar o Arquivo ( FError"+str(ferror(),4)+ ")", lJob)
				EndIf
			Next nX
			
			// Retorna função - não envia email
			Return Nil
			
		EndIf

		_cCliente := Alltrim(SA1->A1_COD)
		_cLoja    :=Alltrim(SA1->A1_LOJA)

		oMessage:cFrom := cFrom

		// Rotina de Envio Automatico de Boleto
		
		oMessage:cTo := cRecebe //E-mail do Cadastro de Clientes

		oMessage:cBcc    := AllTrim(GetMv("ES_MAILCCO",, "")) //Email de Copia Oculta

		oMessage:cCc := GetMailCont(_cCliente,_cLoja)
		oMessage:cCc += cRecebe

		// Analisa as condicoes em que o envio pode ocorrer sem chaveNFE
		// Parâmetro que permite ou não envio de chave da nota em branco
		// .T. Envia link com chave em branco
		lPermite 	:= .F.
		cChaveNfe 	:= ""

		// Posiciona titulo para buscar informacoes do titulo
		DbSelectArea("SE1")
		DbSetOrder(1)		//E1_FILIAL+E1_PREFIXO+E1_NUM+E1_PARCELA+E1_TIPO
		SE1->(DbSeek(aTitulo[1][10]+aTitulo[1][3]+aTitulo[1][2]+aTitulo[1][4]+aTitulo[1][11]))

		// Localiza Chave Nfe
		__lRPS  := .F.
		DbSelectArea("SF2")
		DbSetOrder(1)
		If dbSeek(xFilial("SF2") + aTitulo[1][2] + aTitulo[1][3])

			//Se nota de serviço
			If Upper(AllTrim(SF2->F2_ESPECIE)) == 'RPS'
				
				__lRPS := .T.

				// Envio de Link de RPS apenas para filiais com Link Preenchido
				If !Empty(cChaveNfe) 
				
					//Se não permite envio de link de chave eletrônica em branco, e F2_CODNFE estiver em branco
					If !lPermite .And. Vazio(SF2->F2_CODNFE)
						cChaveNfe := ""
					Else
						cChaveNfe := StrTran(cChaveNfe,'SM0->M0_INSCM',AllTrim(SM0->M0_INSCM))
						cChaveNfe := StrTran(cChaveNfe,'SF2->F2_NFELETR',AllTrim(SF2->F2_NFELETR))
						cChaveNfe := StrTran(cChaveNfe,'SF2->F2_CODNFE',StrTran(Upper(AllTrim(SF2->F2_CODNFE)),'-',''))
						
						cNFEs := AllTrim(SF2->F2_NFELETR)
					EndIf
				EndIf
			Else
				cChaveNfe := SF2->F2_CHVNFE
			EndIf
		EndIf

		// Montagem do HTML para cliente
		// Verifico se existe pasta definida para buscar HTML custommizado por filial
		// Senao, utilizo layout padrao
		If !Empty(cLayHTML) .AND. !Empty(BuscaHTML(cLayHTML))
			cHtml := BuscaHTML(cLayHTML)
			cHtml := ConvMacros(cHtml)
		Else
			cHtml := MontaHtml(aTitulo)
		EndIf

		oMessage:cSubject := "Atenção: Ref. Boleto(s) e Link de Nota Fiscal Nº " + AllTrim(IIF(cNFEs == "" ,aTitulo[1][2],cNFEs))+" - "+AllTrim(aTitulo[1][3])
		oMessage:cBody := cHtml // -> Boleto + Nota

		// Para solicitar confimação de envio
		If GetMv("ES_BOLCNFM",, .F.)
			oMessage:SetConfirmRead( .T. )
		EndIf
		
		// Adiciona anexo de boleto
		For nX := 1 to Len(aFilBol)
			oMessage:AttachFile( aFilBol[nX] )
		Next nX

		// Adiciona anexo de Danfe
		For nX := 1 to Len(aDanfes)
			oMessage:AttachFile( aDanfes[nX] )
		Next nX

		// Adiciona anexo de XML
		For nX := 1 to Len(aXML)
			oMessage:AttachFile( aXML[nX] )
		Next nX

		If( (nErro := oMessage:Send( oMailServer )) != 0 )
			GeraMsgErro("Não enviou o e-mail: " + oMailServer:GetErrorString( nErro ), lJob)
			Return Nil
		Else
			// Grava log de envio e reenvio dos titulos - Flavio Macieira
			DbSelectArea("SE1")
			DbSetOrder(1)
			For nX := 1 to Len(aTitulo)
				If SE1->(DbSeek(aTitulo[nX][10]+aTitulo[nX][3]+aTitulo[nX][2]+aTitulo[nX][4]+aTitulo[nX][11]))

					If SE1->(FieldPos("E1_XDENBOL")) > 0

						RecLock("SE1",.F.)
							SE1->E1_XDENBOL := DATE() //Grava a data do Envio do Boleto
						SE1->(MsUnlock()) 
					EndIf
				EndIf
			Next nX

			// Exclui documentos enviados
			For nX := 1 to Len(aFilBol)
				// Verifica se o parametro para salvar arquivo esta' preenchido para nao apagar arquivo nesse momento
				If Empty(MV_PAR27)
					If FErase(aFilBol[nX]) == -1
						GeraMsgErro('Falha ao tentar deletar o Arquivo ( FError'+str(ferror(),4)+ ')', lJob)
					EndIf
				EndIf
			Next nX
		EndIf
	
		If( (nErro := oMailServer:SmtpDisconnect()) != 0 )
			GeraMsgErro("Não desconectou: " + oMailServer:GetErrorString( nErro ), lJob)
			Return
		EndIf

		AEval(aAreas, {|x| RestArea(x) })
	Else
		GeraMsgErro("Cliente não encontrado!", lJob)
	EndIf
EndIf

Return Nil

/*/{Protheus.doc} GetMailCont
	(Rotina que coleta os Emails do cadastro de Contatos)
	@type Static Function
	@author Calabro'
	@since 20/03/2019
	@version version
	@param _cCliente, character, (Codigo do cliente)
	@param _cLoja, character, (Codigo da loja do cliente)
	@return cRetMail, character, (E-mails relacionados ao cliente do cadastro de contatos)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function GetMailCont(_cCliente as character, _cLoja as character)

Local cRetMail := "" as character
Local cAlias   := GetNextAlias() as character
Local cQuery   := "" as character

cQuery	:= " SELECT U5_EMAIL  " + CRLF
cQuery  += " FROM " + RetSQLTab("AC8") + CRLF
cQuery  += " JOIN " + RetSQLTab("SU5") + CRLF
cQuery  += "   ON SU5.U5_CODCONT = AC8.AC8_CODCON " + CRLF
cQuery  += "  AND SU5.D_E_L_E_T_<>'*'  " + CRLF
cQuery  += "WHERE AC8.D_E_L_E_T_<>'*' " + CRLF
cQuery  += "  AND AC8_CODENT = '" + _cCliente + _cLoja + "' " + CRLF
cQuery  += "  AND SU5.U5_EMAIL LIKE '%@%' " + CRLF

MpSysOpenQuery(cQuery, cAlias)

DbSelectArea(cAlias)
dbGoTop()
While (cAlias)->( !EOF())
	
	If !Vazio(cRetMail)
		cRetMail += "; "
	EndIf
	
	cRetMail += Alltrim((cAlias)->U5_EMAIL)
	
	(cAlias)->(DbSkip())
	
EndDo

Return cRetMail

/*/{Protheus.doc} GeraMsgErro
	(Gera mensagem de erro em tela - se nao for job - e no console do server)
	@type Static Function
	@author Calabro'
	@since 20/03/2019
	@version version
	@param cMensagem, character, (Texto a ser considerado na mensagem)
	@param lJob, logical, (Variavel de controle para identificar se processo esta em job ou nao)
	@return Nil, Nulo
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function GeraMsgErro(cMensagem as character, lJob as logical, aBotoes as array)

cMensagem := If(Empty(cMensagem), FunName() + DToC(Date()) + Time() + " - Sem mensagem definida.", cMensagem)

aBotoes := If(ValType(aBotoes) == "A" .AND. Len(aBotoes) > 0, aBotoes, {"Sair"})

If !lJob
	Aviso("Inconsistência", cMensagem, aBotoes,, "Atenção:")
EndIf

ConOut(cMensagem)

Return Nil

/*/{Protheus.doc} MyPerg
(Funcao de perguntas para execucao da rotina)
@author Calabró
@since 31/03/2021
@version 1.0
@return aRet, array, (Array com parametros preenchidos)
@example
(examples)
@see (links_or_references)
/*/

Static Function MyPerg()

Local cTitulo	:= "Parâmetros para gerar boleto"

Local aPergs	:= {}								//Array com os tipos de Parambox
Local aRet		:= {}				 				//Array com o retorno do pergunte
Local aAreaAtu	:= GetArea()

// 1
AAdd(aPergs,{	1,;
				"De Prefixo",;
				Space(TamSX3("E1_PREFIXO")[1]),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 2
AAdd(aPergs,{	1,;
				"Ate Prefixo",;
				Space(TamSX3("E1_PREFIXO")[1]),;
				"",;
				"MV_PAR01 <= MV_PAR02",;
				"",;
				"",;
				50,;
				.F. })
// 3
AAdd(aPergs,{	1,;
				"De Numero",;
				Space(TamSX3("E1_NUM")[1]),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 4
AAdd(aPergs,{	1,;
				"Ate Numero",;
				Space(TamSX3("E1_NUM")[1]),;
				"",;
				"MV_PAR03 <= MV_PAR04",;
				"",;
				"",;
				50,;
				.F. })
// 5
AAdd(aPergs,{	1,;
				"De Parcela",;
				Space(TamSX3("E1_PARCELA")[1]),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 6
AAdd(aPergs,{	1,;
				"Ate Parcela",;
				Space(TamSX3("E1_PARCELA")[1]),;
				"",;
				"MV_PAR05 <= MV_PAR06",;
				"",;
				"",;
				50,;
				.F. })
// 7
AAdd(aPergs,{	1,;
				"De Portador",;
				Space(TamSX3("E1_PORTADO")[1]),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 8
AAdd(aPergs,{	1,;
				"Ate Portador",;
				Space(TamSX3("E1_PORTADO")[1]),;
				"",;
				"MV_PAR07 <= MV_PAR08",;
				"",;
				"",;
				50,;
				.F. })
// 9
AAdd(aPergs,{	1,;
				"De Cliente",;
				Space(TamSX3("E1_CLIENTE")[1]),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 10
AAdd(aPergs,{	1,;
				"Ate Cliente",;
				Space(TamSX3("E1_CLIENTE")[1]),;
				"",;
				"MV_PAR09 <= MV_PAR10",;
				"",;
				"",;
				50,;
				.F. })
// 11
AAdd(aPergs,{	1,;
				"De Loja",;
				Space(TamSX3("E1_LOJA")[1]),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 12
AAdd(aPergs,{	1,;
				"Ate Loja",;
				Space(TamSX3("E1_LOJA")[1]),;
				"",;
				"MV_PAR11 <= MV_PAR12",;
				"",;
				"",;
				50,;
				.F. })
// 13
AAdd(aPergs,{	1,;
				"De Emissao",;
				CToD(""),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 14
AAdd(aPergs,{	1,;
				"Ate Emissao",;
				CToD(""),;
				"",;
				"MV_PAR13 <= MV_PAR14",;
				"",;
				"",;
				50,;
				.F. })
// 15
AAdd(aPergs,{	1,;
				"De Vencimento",;
				CToD(""),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 16
AAdd(aPergs,{	1,;
				"Ate Vencimento",;
				CToD(""),;
				"",;
				"MV_PAR15 <= MV_PAR16",;
				"",;
				"",;
				50,;
				.F. })
// 17
AAdd(aPergs,{	1,;
				"Do Bordero",;
				Space(TamSX3("E1_NUMBOR")[1]),;
				"",;
				"",;
				"",;
				"",;
				50,;
				.F. })
// 18
AAdd(aPergs,{	1,;
				"Ate Bordero",;
				Space(TamSX3("E1_NUMBOR")[1]),;
				"",;
				"MV_PAR17 <= MV_PAR18",;
				"",;
				"",;
				50,;
				.F. })
// 19
AAdd(aPergs,{	1,;
				"Linha Obs 1",;
				Space(80),;
				"",;
				"",;
				"",;
				"",;
				80,;
				.F. })
// 20
AAdd(aPergs,{	1,;
				"Linha Obs 2",;
				Space(80),;
				"",;
				"",;
				"",;
				"",;
				80,;
				.F. })
// 21
AAdd(aPergs,{	1,;
				"Linha Obs 3",;
				Space(80),;
				"",;
				"",;
				"",;
				"",;
				80,;
				.F. })
// 22
AAdd(aPergs,{	4,;
				"Traz Marcados?",;
				.F.,;
				"Se sim, marque esta opção",;
				90,;
				'',;
				.F. })
// 23
AAdd(aPergs,{	4,;
				"Gera Boleto?",;
				.F.,;
				"Se sim, marque esta opção",;
				90,;
				'U_RFIR01VldPar("' + AllTrim(GetMv("ES_FUNBOLE",,"RFINR01")) + '")',;
				.F. })
// 24
AAdd(aPergs,{	4,;
				"Gera Danfe?",;
				.F.,;
				"Se sim, marque esta opção",;
				90,;
				'U_RFIR01VldPar("' + AllTrim(GetMv("ES_FUNDANF",,"RFATR01")) + '")',;
				.F. })
// 25
AAdd(aPergs,{	4,;
				"Gera XML?",;
				.F.,;
				"Se sim, marque esta opção",;
				90,;
				'U_RFIR01VldPar("' + AllTrim(GetMv("ES_FUNXML",,"RFATR01XML")) + '")',;
				.F. })

// 26
AAdd(aPergs,{	4,;
				"Envia docs. por e-mail?",;
				.F.,;
				"Se sim, marque esta opção",;
				90,;
				'',;
				.F. })

// 27
AAdd(aPergs,{	6,;
				"Salva docs. em?",;
				Space(230),;
				"",;
				"",;
				"",;
				180,;
				.F.,;
				Nil/*"Arquivos XLS|*.XLS|Todos os Arquivos|*.*"*/,;
				"C:\",;
				GETF_RETDIRECTORY + GETF_LOCALFLOPPY + GETF_LOCALHARD + GETF_NETWORKDRIVE})

ParamBox(aPergs, cTitulo, @aRet,,,,,,,FunName()+"1", .T., .T.)

RestArea(aAreaAtu)

aSize(aPergs, 0)
aSize(aAreaAtu, 0)

Return aRet

/*/{Protheus.doc} GrvHistSE1
	(Atualiza historico e numero do banco - E1_NUMBCO - nosso numero - no titulo)
	@type Static Function
	@author Calabro'
	@since 22/03/2022
	@version version
	@param param, param_type, param_descr
	@return return, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function GrvHistSE1(aCB_RN_NN as array, cNroDoc as character)

DbSelectArea("SE1")
RecLock("SE1", .F.)

	If SEA->EA_PORTADO == "001"

		SE1->E1_NUMBCO	:=	aCB_RN_NN[3]				// Nosso número (Ver fórmula para calculo)
		SE1->E1_HIST	:= "BOLETO BB GERADO"
	ElseIf SEA->EA_PORTADO == "341"

		SE1->E1_NUMBCO	:= Substr(aCB_RN_NN[3],1,8)		// Nosso número
		SE1->E1_HIST	:= "BOLETO ITAU GERADO"
	ElseIf SEA->EA_PORTADO == "237"
		
		SE1->E1_NUMBCO 	:= Substr(cNroDoc,1,12)
		SE1->E1_HIST 	:= "BOLETO BRADESCO GERADO"
	ElseIf SEA->EA_PORTADO == "422"

		SE1->E1_NUMBCO 	:= Left(aCB_RN_NN[3],8)
		SE1->E1_HIST 	:= "BOLETO SAFRA GERADO"
	ElseIf SEA->EA_PORTADO == "637"

		SE1->E1_NUMBCO 	:= aCB_RN_NN[3]
		SE1->E1_HIST 	:= "BOLETO SOFISA GERADO"
	ElseIf SEA->EA_PORTADO == "033"

		SE1->E1_NUMBCO 	:= aCB_RN_NN[3]
		SE1->E1_HIST 	:= "BOLETO SANTANDER GERADO"
	EndIf

SE1->(MsUnlock())

Return Nil

/*/{Protheus.doc} RFIR01VldPar
	(Verifica se a funcao enviada por parametro esta' disponivel no repositorio)
	@type User Function
	@author Calabro'
	@since 22/03/2022
	@version version
	@param cRotina, character, (Nome da rotina a ser verificada)
	@return lRet, logical, (.T. - rotina disponivel no repositorio, .F. - rotina nao disponivel)
	@example
	(examples)
	@see (links_or_references)
	/*/

User Function RFIR01VldPar(cRotina as character)

Local lRet		:= FindFunction(cRotina) as logical		// TODO: VERIFICAR MSG DE NAO COMPILADA

If !lRet
	Aviso( "Rotina não disponível", "Essa rotina não encontra-se disponível para utilização" + CRLF +;
			"Por favor, entre em contato com o administrador e solicite mais informações para contratação " +;
			"e disponibilização deste recurso", {"&Cancelar"} )
EndIf

Return lRet

/*/{Protheus.doc} GetSubConta
	(Busca o codigo da subconta dos dados bancarios que sao usados para gerar arquivo CNAB com o banco)
	@type Static Function
	@author Calabro'
	@since 22/03/2022
	@version version
	@param cCodBanco, character, (Codigo do banco)
	@param cNumAgenc, character, (Numero da agencia)
	@param cNumConta, character, (Numero da conta)
	@return return, return_type, return_description
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function GetSubConta(cCodBanco as character, cNumAgenc as character, cNumConta as character)

Local cQuery	:= "" as character
Local cAlias	:= GetNextAlias() as character
Local cSubConta	:= "" as character

cQuery := " SELECT R_E_C_N_O_ SEERECNO" + CRLF
cQuery += "   FROM " + RetSQLTab("SEE") + CRLF
cQuery += "  WHERE SEE.EE_FILIAL = '" + xFilial("SEE") + "' " + CRLF
cQuery += "    AND SEE.EE_CODIGO = '" + cCodBanco + "' " + CRLF
cQuery += "    AND SEE.EE_AGENCIA = '" + cNumAgenc + "' " + CRLF
cQuery += "    AND SEE.EE_CONTA = '" + cNumConta + "' " + CRLF
cQuery += "    AND SEE.EE_CODEMP <> ' ' " + CRLF
cQuery += "    AND SEE.D_E_L_E_T_ <> '*' " + CRLF

MpSysOpenQuery(cQuery, cAlias)

If (cAlias)->(!EOF())
	DbSelectArea("SEE")
	SEE->(DbGoTo((cAlias)->SEERECNO))
	cSubConta := SEE->(If(!Empty(EE_SUBCTA), EE_SUBCTA, Space(TamSX3("EE_SUBCTA")[1])))
EndIf

Return cSubConta

/*/{Protheus.doc} GetDVBanco
	(Funcao para buscar o digito verificador do banco a partir de um array)
	@type Static Function
	@author Calabro'
	@since 24/03/2022
	@version version
	@param cCodBanco, character, (Codigo do banco a ser procurado)
	@return aDadosBco, array, (Array contendo os dados do banco encontrado)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function GetDVBanco(cCodBanco)

Local nPos			:= 0 as numeric

Local aBancos		:= {} as array

// Carrega lista de bancos com seus DV
// Dados extraidos de http://www.eurodidattica.com/html/bancos.htm

// Estrutura de aBancos:
// [1] - Codigo do banco
// [2] - DV do banco
// [3] - Nome do banco
AAdd(aBancos, {"654",	"8",	"Banco A.J.Renner S.A."})
AAdd(aBancos, {"M40",	"0",	"Banco ABB S.A."})
AAdd(aBancos, {"246",	"1",	"Banco ABC Brasil S.A."})
AAdd(aBancos, {"356",	"5",	"Banco ABN AMRO Real S.A."})
AAdd(aBancos, {"222",	"4",	"Banco AGF Braseg S.A."})
AAdd(aBancos, {"298",	" ",	"Banco Alfa S.A."})
AAdd(aBancos, {"215",	"1",	"Banco América do Sul S.A."})
AAdd(aBancos, {"M34",	"0",	"Banco American Express S.A."})
AAdd(aBancos, {"625",	"4",	"Banco Araucária S.A."})
AAdd(aBancos, {"213",	"5",	"Banco Arbi S.A."})
AAdd(aBancos, {"230",	"5",	"Banco Bandeirantes S.A."})
AAdd(aBancos, {"028",	"0",	"Banco Baneb S.A."})
AAdd(aBancos, {"029",	"9",	"Banco Banerj S.A."})
AAdd(aBancos, {"038",	"8",	"Banco Banestado S.A."})
AAdd(aBancos, {"719",	"6",	"Banco Banif Primus S.A."})
AAdd(aBancos, {"740",	"4",	"Banco Barclays e Galícia S.A."})
AAdd(aBancos, {"184",	"8",	"Banco BBA - CREDITANSTALT S.A."})
AAdd(aBancos, {"107",	"4",	"Banco BBM S.A."})
AAdd(aBancos, {"048",	"5",	"Banco Bemge S.A."})
AAdd(aBancos, {"739",	"0",	"Banco BGN S.A."})
AAdd(aBancos, {"641",	"6",	"Banco Bilbao Vizcaya Argentaria Brasil S.A."})
AAdd(aBancos, {"496",	"0",	"Banco Bilbao Vizcaya Argentaria S.A."})
AAdd(aBancos, {"394",	"8",	"Banco BMC S.A."})
AAdd(aBancos, {"318",	"2",	"Banco BMG S.A."})
AAdd(aBancos, {"116",	"3",	"Banco BNL do Brasil S.A."})
AAdd(aBancos, {"752",	"8",	"Banco BNP Paribas Brasil S.A."})
AAdd(aBancos, {"231",	"1",	"Banco Boavista Interatlântico S.A."})
AAdd(aBancos, {"218",	"6",	"Banco Bonsucesso S.A."})
AAdd(aBancos, {"262",	"3",	"Banco Boreal S.A."})
AAdd(aBancos, {"237",	"2",	"Banco Bradesco S.A."})
AAdd(aBancos, {"225",	"9",	"Banco Brascan S.A."})
AAdd(aBancos, {"M17",	"8",	"Banco BRJ S.A."})
AAdd(aBancos, {"M10",	"1",	"Banco BVA S.A."})
AAdd(aBancos, {"263",	"1",	"Banco Cacique S.A."})
AAdd(aBancos, {"412",	"X",	"Banco Capital S.A."})
AAdd(aBancos, {"40",	" ",	"Banco Cargill S.A."})
AAdd(aBancos, {"266",	"6",	"Banco Cédula S.A."})
AAdd(aBancos, {"221",	"6",	"Banco Chase Fleming S.A."})
AAdd(aBancos, {"376",	"X",	"Banco Chase Manhattan S.A."})
AAdd(aBancos, {"244",	"5",	"Banco Cidade S.A."})
AAdd(aBancos, {"745",	"5",	"Banco Citibank S.A."})
AAdd(aBancos, {"241",	"0",	"Banco Clássico S.A."})
AAdd(aBancos, {"M36",	"0",	"Banco CNH Capital S.A."})
AAdd(aBancos, {"753",	"6",	"Banco Comercial Uruguai S.A."})
AAdd(aBancos, {"756",	"0",	"Banco Cooperativo do Brasil S.A. - BANCOOB"})
AAdd(aBancos, {"748",	"X",	"Banco Cooperativo Sicredi S.A. - BANSICREDI"})
AAdd(aBancos, {"109",	"0",	"Banco Credibanco S.A."})
AAdd(aBancos, {"721",	"8",	"Banco Credibel S.A."})
AAdd(aBancos, {"505",	"3",	"Banco Credit Suisse First Boston Garantia S.A."})
AAdd(aBancos, {"229",	"1",	"Banco Cruzeiro do Sul S.A."})
AAdd(aBancos, {"003",	"5",	"Banco da Amazônia S.A."})
AAdd(aBancos, {"M38",	"0",	"Banco Daimlerchrysler S.A."})
AAdd(aBancos, {"733",	"1",	"Banco das Nações S.A."})
AAdd(aBancos, {"707",	"2",	"Banco Daycoval S.A."})
AAdd(aBancos, {"291",	"7",	"Banco de Crédito Nacional S.A."})
AAdd(aBancos, {"022",	"1",	"Banco de Crédito Real de Minas Gerais S.A."})
AAdd(aBancos, {"300",	"X",	"Banco de La Nacion Argentina"})
AAdd(aBancos, {"495",	"2",	"Banco de La Provincia de Buenos Aires"})
AAdd(aBancos, {"494",	"4",	"Banco de La Republica Oriental del Uruguay"})
AAdd(aBancos, {"024",	"8",	"Banco de Pernambuco S.A. - BANDEPE"})
AAdd(aBancos, {"456",	"1",	"Banco de Tokyo-Mitsubishi Brasil S.A."})
AAdd(aBancos, {"214",	"3",	"Banco Dibens S.A."})
AAdd(aBancos, {"001",	"9",	"Banco do Brasil S.A."})
AAdd(aBancos, {"031",	"0",	"Banco do Estado de Goiás S.A. - BEG"})
AAdd(aBancos, {"027",	"2",	"Banco do Estado de Santa Catarina S.A."})
AAdd(aBancos, {"033",	"4",	"Banco do Estado de São Paulo S.A. - Banespa"})
AAdd(aBancos, {"047",	"7",	"Banco do Estado de Sergipe S.A."})
AAdd(aBancos, {"034",	"5",	"Banco do Estado do Amazonas S.A."})
AAdd(aBancos, {"035",	"3",	"Banco do Estado do Ceará S.A."})
AAdd(aBancos, {"036",	"1",	"Banco do Estado do Maranhão S.A."})
AAdd(aBancos, {"037",	"0",	"Banco do Estado do Pará S.A."})
AAdd(aBancos, {"039",	"6",	"Banco do Estado do Piauí S.A."})
AAdd(aBancos, {"041",	"8",	"Banco do Estado do Rio Grande do Sul S.A."})
AAdd(aBancos, {"004",	"3",	"Banco do Nordeste do Brasil S.A."})
AAdd(aBancos, {"743",	"9",	"Banco Emblema S.A."})
AAdd(aBancos, {"242",	"9",	"Banco Euroinvest S.A. - Eurobanco"})
AAdd(aBancos, {"370",	"0",	"Banco Europeu para a America Latina (BEAL) S.A."})
AAdd(aBancos, {"265",	"8",	"Banco Fator S.A."})
AAdd(aBancos, {"M22",	"4",	"Banco Fiat S.A."})
AAdd(aBancos, {"224",	"0",	"Banco Fibra S.A."})
AAdd(aBancos, {"200",	"3",	"Banco Ficrisa Axelrud S.A."})
AAdd(aBancos, {"626",	"2",	"Banco Ficsa S.A."})
AAdd(aBancos, {"473",	"1",	"Banco Financial Português S.A."})
AAdd(aBancos, {"725",	"0",	"Banco Finansinos S.A."})
AAdd(aBancos, {"252",	"6",	"Banco Fininvest S.A."})
AAdd(aBancos, {"M35",	"0",	"Banco Ford S.A."})
AAdd(aBancos, {"346",	"8",	"Banco Francês e Brasileiro S.A."})
AAdd(aBancos, {"489",	"6",	"Banco Francês Internacional (Brasil) S.A."})
AAdd(aBancos, {"233",	"X",	"Banco GE Capital S.A."})
AAdd(aBancos, {"624",	"7",	"Banco General Motors S.A."})
AAdd(aBancos, {"734",	"X",	"Banco Gerdau S.A."})
AAdd(aBancos, {"612",	"2",	"Banco Guanabara S.A."})
AAdd(aBancos, {"M41",	"0",	"Banco Honda S.A."})
AAdd(aBancos, {"228",	"3",	"Banco Icatu S.A."})
AAdd(aBancos, {"258",	"5",	"Banco Induscred S.A."})
AAdd(aBancos, {"604",	"1",	"Banco Industrial do Brasil S.A."})
AAdd(aBancos, {"320",	"4",	"Banco Industrial e Comercial S.A."})
AAdd(aBancos, {"653",	"X",	"Banco Indusval S.A."})
AAdd(aBancos, {"204",	"6",	"Banco Inter American Express S.A."})
AAdd(aBancos, {"630",	"0",	"Banco Intercap S.A."})
AAdd(aBancos, {"722",	"6",	"Banco Interior de São Paulo S.A."})
AAdd(aBancos, {"232",	"1",	"Banco Interpart S.A."})
AAdd(aBancos, {"249",	"6",	"Banco Investcred S.A."})
AAdd(aBancos, {"341",	"7",	"Banco Itaú S.A."})
AAdd(aBancos, {"42",	" ",	"Banco J. Safra S.A."})
AAdd(aBancos, {"M11",	"2",	"Banco J.P.Morgan S.A."})
AAdd(aBancos, {"217",	"8",	"Banco John Deere S.A."})
AAdd(aBancos, {"757",	"9",	"Banco KEB do Brasil S.A."})
AAdd(aBancos, {"M09",	"9",	"Banco Lloyds TSB S.A."})
AAdd(aBancos, {"600",	"9",	"Banco Luso Brasileiro S.A."})
AAdd(aBancos, {"212",	"7",	"Banco Matone S.A."})
AAdd(aBancos, {"720",	"X",	"Banco Maxinvest S.A."})
AAdd(aBancos, {"392",	"1",	"Banco Mercantil de São Paulo S.A."})
AAdd(aBancos, {"389",	"1",	"Banco Mercantil do Brasil S.A."})
AAdd(aBancos, {"755",	"2",	"Banco Merrill Lynch S.A."})
AAdd(aBancos, {"746",	"3",	"Banco Modal S.A."})
AAdd(aBancos, {"738",	"2",	"Banco Morada S.A."})
AAdd(aBancos, {"243",	"7",	"Banco Multi Stock S.A."})
AAdd(aBancos, {"151",	"1",	"Banco Nossa Caixa S.A."})
AAdd(aBancos, {"M04",	"4",	"Banco OK de Investimento S.A."})
AAdd(aBancos, {"M01",	"1",	"Banco Opportunity S.A."})
AAdd(aBancos, {"M19",	"1",	"Banco Ourinvest S.A."})
AAdd(aBancos, {"208",	"9",	"Banco Pactual S.A."})
AAdd(aBancos, {"623",	"8",	"Banco Panamericano S.A."})
AAdd(aBancos, {"611",	"4",	"Banco Paulista S.A."})
AAdd(aBancos, {"650",	"5",	"Banco Pebb S.A."})
AAdd(aBancos, {"613",	"0",	"Banco Pecúnia S.A."})
AAdd(aBancos, {"643",	"2",	"Banco Pine S.A."})
AAdd(aBancos, {"658",	"0",	"Banco Porto Real S.A."})
AAdd(aBancos, {"735",	"8",	"Banco Pottencial S.A."})
AAdd(aBancos, {"638",	"6",	"Banco Prosper S.A."})
AAdd(aBancos, {"M39",	"0",	"Banco PSA Finance Brasil S.A."})
AAdd(aBancos, {"747",	"1",	"Banco Rabobank International Brasil S.A."})
AAdd(aBancos, {"M18",	"9",	"Banco Rede S.A."})
AAdd(aBancos, {"216",	"X",	"Banco Regional Malcon S.A. Com.e de Cred.ao Cons."})
AAdd(aBancos, {"633",	"5",	"Banco Rendimento S.A."})
AAdd(aBancos, {"741",	"2",	"Banco Ribeirão Preto S.A."})
AAdd(aBancos, {"453",	"7",	"Banco Rural S.A."})
AAdd(aBancos, {"422",	"7",	"Banco Safra S.A."})
AAdd(aBancos, {"353",	"0",	"Banco Santander Brasil S.A."})
AAdd(aBancos, {"498",	"7",	"Banco Santander Central Hispano S.A."})
AAdd(aBancos, {"502",	"9",	"Banco Santander de Negócios S.A."})
AAdd(aBancos, {"008",	"6",	"Banco Santander Meridional S.A."})
AAdd(aBancos, {"351",	"4",	"Banco Santander S.A."})
AAdd(aBancos, {"607",	"6",	"Banco Santos Neves S.A."})
AAdd(aBancos, {"702",	"1",	"Banco Santos S.A."})
AAdd(aBancos, {"250",	"6",	"Banco Schahin S.A."})
AAdd(aBancos, {"211",	"9",	"Banco Sistema S.A."})
AAdd(aBancos, {"637",	"8",	"Banco Sofisa S.A."})
AAdd(aBancos, {"366",	"2",	"Banco Sogeral S.A."})
AAdd(aBancos, {"M07",	"7",	"Banco Sterling S.A."})
AAdd(aBancos, {"347",	"6",	"Banco Sudameris Brasil S.A."})
AAdd(aBancos, {"205",	"4",	"Banco Sul América S.A."})
AAdd(aBancos, {"464",	"2",	"Banco Sumitomo Brasileiro S.A."})
AAdd(aBancos, {"618",	"1",	"Banco Tendência S.A."})
AAdd(aBancos, {"737",	"4",	"Banco Theca S.A."})
AAdd(aBancos, {"M37",	"0",	"Banco Toyota do Brasil S.A."})
AAdd(aBancos, {"634",	"3",	"Banco Triângulo S.A."})
AAdd(aBancos, {"M27",	"9",	"Banco Tricury S.A."})
AAdd(aBancos, {"247",	"X",	"Banco UBS Warburg S.A."})
AAdd(aBancos, {"493",	"6",	"Banco Union - Brasil S.A."})
AAdd(aBancos, {"M33",	"6",	"Banco Volkswagen S.A."})
AAdd(aBancos, {"M03",	"3",	"Banco Volvo (Brasil) S.A."})
AAdd(aBancos, {"655",	"6",	"Banco Votorantim S.A."})
AAdd(aBancos, {"610",	"6",	"Banco VR S.A."})
AAdd(aBancos, {"480",	"4",	"Banco Wachovia S.A."})
AAdd(aBancos, {"219",	"4",	"Banco Zogbi S.A."})
AAdd(aBancos, {"62",	" ",	"Banco1.Net S.A."})
AAdd(aBancos, {"021",	"3",	"BANESTES S.A. Banco do Estado do Espírito Santo"})
AAdd(aBancos, {"235",	"6",	"Bank of America - Liberal S.A. (Banco Múltiplo)"})
AAdd(aBancos, {"479",	"0",	"BankBoston Banco Múltiplo S.A."})
AAdd(aBancos, {"744",	"7",	"BankBoston N.A."})
AAdd(aBancos, {"294",	"1",	"BCR Banco de Crédito Real S.A."})
AAdd(aBancos, {"749",	"8",	"BR Banco Mercantil S.A."})
AAdd(aBancos, {"070",	"1",	"BRB - Banco de Brasília S.A."})
AAdd(aBancos, {"104",	"0",	"Caixa Econômica Federal"})
AAdd(aBancos, {"477",	"4",	"Citibank N.A."})
AAdd(aBancos, {"175",	"9",	"Continental Banco S.A."})
AAdd(aBancos, {"487",	"1",	"Deutsche Bank S.A. - Banco Alemão"})
AAdd(aBancos, {"751",	"X",	"Dresdner Bank Brasil S.A. - Banco Múltiplo"})
AAdd(aBancos, {"210",	"0",	"Dresdner Bank Lateinamerika AG"})
AAdd(aBancos, {"399",	"9",	"HSBC Bank Brasil S.A. - Banco Múltiplo"})
AAdd(aBancos, {"168",	"6",	"HSBC Investment Bank Brasil S.A. - Banco Múltiplo"})
AAdd(aBancos, {"750",	"1",	"HSBC Republic Bank Brasil S.A - Banco Múltiplo"})
AAdd(aBancos, {"63",	" ",	"Ibibank S.A. - Banco Múltiplo"})
AAdd(aBancos, {"492",	"8",	"ING Bank N.V."})
AAdd(aBancos, {"472",	"3",	"Lloyds TSB Bank PLC."})
AAdd(aBancos, {"488",	"X",	"Morgan Guaranty Trust Company of New York"})
AAdd(aBancos, {"148",	"1",	"Multi Banco S.A."})
AAdd(aBancos, {"030",	"2",	"PARAIBAN - Banco do Estado da Paraíba S.A."})
AAdd(aBancos, {"254",	"2",	"Paraná Banco S.A."})
AAdd(aBancos, {"409",	"0",	"UNIBANCO - União de Bancos Brasileiros S.A."})

nPos := aScan(aBancos, {|x| x[1] == cCodBanco})

Return If(!Empty(nPos), aBancos[nPos], Array(3))

/*/{Protheus.doc} MontaHtml
	(Funcao para montar o HTML a ser considerado no e-mail)
	@type Static Function
	@author Calabro'
	@since 16/01/2022
	@version version
	@aparam aTitulo, array, (Array contendo os dados do titulo)
	@return cHtml, character, (Conteudo Html gerado)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function MontaHtml(aTitulo as array)

Local cHtml		:= "" as character
Local cChaveNfe	:= If(!Empty(SF2->F2_CHVNFE), SF2->F2_CHVNFE, If(!Empty(SF2->F2_NFELETR), SF2->F2_NFELETR,"")) as character

// Texto em Html que ira no corpo do E-mail
// Boleto + Nota Fiscal
cHtml += "<html>"
cHtml += "	<head>"
cHtml += "		<title>Email_Notificacao</title>"
cHtml += "	</head>"
cHtml += "	<body>"
cHtml += "		<table border = '0' width='100%'>"
cHtml += "		<tr>"
cHtml += "			<td>"
cHtml += "				<font face='Arial' size='2' color='Black'>"
cHtml += "					 Aten&ccedil;&atilde;o: Ref. aos documentos e Link de Nota Fiscal Nº "+ AllTrim(SF2->F2_DOC) + " - " + AllTrim(SF2->F2_SERIE)
// Se Envia Boleto com link da Nota
If !Vazio(cChaveNfe)
	cHtml += "				</font>"
	cHtml += "				<br><br>"
	cHtml += "				<font face='Arial' size='2' color='Black'>"
	If !Empty(SF2->F2_NFELETR)
		cHtml += "					Link de Consulta NFe: <a href='"+cChaveNfe+"' title='Consulta Nota Fiscal Eletronica'>Consulta NFe</a>"
	Else
		cHtml += "					Link de Consulta NFe: <a href='https://dfe-portal.svrs.rs.gov.br/Nfe/Consulta' title='Consulta Nota Fiscal Eletronica'>Consulta NFe</a>"
	EndIf
	cHtml += "				</font>"
	cHtml += "				<br><br>"
	cHtml += "				<font face='Arial' size='2' color='Black'>"
	cHtml += "					Chave de acesso da NFe: "+cChaveNfe+" "
	cHtml += "				</font>"
EndIf

cHtml += "				<br><br>"
cHtml += "				<font face='Arial' size='2' color='Black'>"
cHtml += "					D&uacute;vidas, favor entrar em contato atrav&eacute;s do telefone: (011) ####-#### ou no e-mail teste@" + Lower(AllTrim(SM0->M0_NOME)) + ".com.br."
cHtml += "				</font>"
cHtml += "				<br></br>"
cHtml += "				<font face='Arial' size='2' color='Black'>"
cHtml += "					<b>Setor de Cr&eacute;dito e Cobran&ccedil;a</b>"
cHtml += "				</font>"
cHtml += "				<br></br>"
cHtml += "				<font face='Arial' size='2' color='Black'>"
cHtml += 					FWFilName(cEmpAnt, cFilAnt)
cHtml += "				</font>"
cHtml += "				<br></br>"
cHtml += "			</td>"
cHtml += "		</tr>"
cHtml += "		</table>"
cHtml += "		<div align='center'>"
cHtml += "			<table width='100%'>"
cHtml += "				<tr>"
cHtml += "					<td height='20px'></td>"
cHtml += "				</tr>"
cHtml += "				<tr>"
cHtml += "					<td width='93%' class='style4'>"
cHtml += "						<p align='right'><font size='1'>Powered by <a href='http://www.wikitec.com.br/'>Wikitec/Protheus</a></font>"
cHtml += "					</td>"
cHtml += "					<td class='Mini'>"
cHtml += "						<a href='http://www.wikitec.com.br/'>"
cHtml += "							<img width='60' height='18' alt='' "
cHtml += "								src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATYAAABcCAIAAABrxg52AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEJsAABCbAXSJnEsAAC"
cHtml += "								TQSURBVHhe7Z0HXBVXvsfzcbNvn9eoiZuyKfuSzdtNNptN2V2T7GbzsrveCvYYo2BvsXAb1UJvItJBQKzYu4AgKKL0jqICogJ2URFpgnTy/mfuude5M7fMvVyuGOb7+X/84J0zZ2bOnN8"
cHtml += "								5/1PnhZ9YWFgGMaxEWVgGNaxEWVgGNaxEWVgGNQMl0d6+PpX19eEfWVhYDMWUEq191F5S3ZBcXBuTUr3+yOX1RyrB/A9XBsdd3pN+I73s4flrjfXNHTg0CwsLA0wg0fqWzsM5t30PVs4P"
cHtml += "								KeS7Zom8i4SeBUKPfDXzLLDwLuG7ZCyPLAmNv5JZXtfe2YPPZ2Fh0U6/JHqzri0yqXpucLHALdfC56zAPY/vkslzTtdmIGCFVi09c1ZElsTl32183InjYmFh0YSREn3Q2L41tWaKT46iw"
cHtml += "								tStTLrx3bLhLIFHnji6NK30fm8v21plYdGMMRItqWr4MaJY5A2VZzbPOYMiPwPMJQMUDlWr9/5Ld+uf4NhZWFhIGCbR7p6+g9m3JnjlgrRAYFTJGWVE87V4yYaz52oa8GVYWFiUGCDRru"
cHtml += "								6+DYlXBW45Avdcisz6bRkiryKrwOKSq4/wxVhYWAiYSrSvry8yqUromU84txSBmcTOCD0Lp63NLbxcjy/JwsLCXKIHsm6ibqGB0ic2kVfhzIDiC9ca8VVZWIY8jCSaVVZn6ZkLLi5FUQN"
cHtml += "								h0C5dFFb0oLEdX5uFZWijX6K1j9oXhpWg/iGanAbIoF3qs78cX56FZWijR6J9P/0UFHdZ5FNCUdGAGrjTIveczLI6fBMsLEMYPRI9f63Rwj2T75pFUdFAG1SkKyJL2LlHLCy6JNrX95P7"
cHtml += "								nnKRZ2G/5icYZy4ZIq/ClJJafCssLEMVXRKtuNk8yStrAEZBGZnIs0Aec46dbc8yxNEl0Y0p1WZuhZKN75LJd8koZaccsQxttEq0ua1LEl0C3iZFOeYzlwyhe174sav4hlhYhiRaJVp+o"
cHtml += "								2mCt8FLWExrQo/8JeFFnV29+J5YWIYeWiV6NPe2yLuYohkzGzSDp/nmVNc+xvfEwjL00CrRkPgrUIlRNGNmE7hmWbhlprMDpCxDGM0S7e7pc9p+/ln15aoM3Gy4h72ZN/FtsbAMPTRLtL"
cHtml += "								2zZ8mG4mcuUTAL37ORx6vwbbGwDD00S7TlSddk72zzzJvXbRa+5yISWYmy/By4U9d49vKN3LLqhOzzu04W7EktBDtRUF5Qfg1+PF9160FDC32TIK0SneKdM0gkuiHJBBLt7uk9VVQRcuC"
cHtml += "								UPGy/TfBecfDeHwN2bYzP7Op+ZlMj2to7ww6mLQ3YBTezImiPw4ZDYYdOX6i6jQ8rgV+coo5AAAgGtjxwNwRrbtW1j0ztw6aAvakQUnnKHrfNCVdv3ceHDaG5rX39nhPLiKgg3Rw2HIw8"
cHtml += "								ml5xnTrrq6+vL7P0il3EQdV9wnNFx6W3d3bjEEoKK645RR1WBTOtwZP67Uy+Xad5LB0S7VRJZfD+U/Lw/TZB1HOZGMR/KL3EoH2ha+ubDp4ugXPHSQM/nef13ver3p7iOFogGc61GT5uB"
cHtml += "								dirlra/neoEP74/ffVfFnr/n03AlNWRXtsSTxZWtLSh9V5aJfqd789KoqdLKkcKpMN54uE8yXAe/CEdzpeN4ElSCoxZUgNpd/bKjfzyGrCSyzfqGlrwAUM4nH6WAzfDl+H7gb8Fsi8Xry"
cHtml += "								XnAJAxXx48XGCrDEOYQH7gdDEOoQmv7UnDhfbkUzhC28XrduDDjOnp7V3qv5O4w6c3CVHN8txCKdpan3R8Mscdbkx1ReIsyZmzl3EIJf8Srx8uVH8ckxpHaOe86Si+GAnI8V8sXjtSIEP"
cHtml += "								aUOUBQ00gf2uy47krjDpHSipv2EYcAvlxuJDrpBxIHCJNkMEvcBvoXzikyJPELUEARTCu+CWhfI7X1vbOrsHfFgVH1wSzFw6cLiFSWTx8HJReSuNLV0YfwSEYk1l61cJxAxR7r423BYM/"
cHtml += "								vhUHbk/OxYeZAf6MJHgfB7SHilLl/QhkH1g595I02tDSCvGjO1eFQcHkoQfTcAhNwENxRA6kU1ZAxrV0CMeHGbP7ZMFIoXw4V0K+SY7I3j7iIKgXByKAMgvyrvp9ooseyzmPQyj5eLb7c"
cHtml += "								L6cFMy0tgJuD9wHfDEl4EaiZITcj4RBOcUQ40pGCcTxWaU4Xi08am512RT/9hQnomwl1IhOR3UmU0PliBSS9FrtQ80S7erutdtSOhh6dIUe+bvO3MC31Q9SiyqUiUVKCL4U6igcghn3Hz"
cHtml += "								V/Pt9zuAjqKEVZSBSBQrvXJ9rnldXgQAyAPD1OEkjkadL98KTf2vjjEATwsl8bb4cuQQ7Gl0UcPoNDaGJNTBwHalHSKVAWTFq5AR9mxs379X9Z4A2lBjkeuJPXJtjnXqzGgZTA4/zPdys"
cHtml += "								p9wn1RlLuBRxCyWfzPFEtQQpmWoNyAbxKfDECaOPMdN8Ev1NCGmNc8RgLWWIO9aHIVN2pE9iGomKI8tYMNb704znu9+qbNUsUCI67IvTIo2jGzIY2B3TLOnnuHr6nflB9pw7ldVCUeip8"
cHtml += "								aO3S0NKGAzEgJj4TzqJKHeoWgS20r3AgBty49+jNyaBz9fvhSaWh+3AIApDoGxOJ4oAczCwShUY7qnZIkaCqgC+zDT+AQ5AYzBItu3aXuDf10tA40ydRyGbfLPfH1TXl3KdG1OR0o9S0A"
cHtml += "								jnUH+0dWhxdIC7vthBN0DX7MjSSQTUOTeKrd00wu6il7YnIHso29czBFb8+3jaj9AoOxICpqyORRMmRKEwgh3fDXO1pxZXKF6OKBPk2O1LycQiCZyXRU0WXXhGhFhE5Enjwz+Z53HvUjA"
cHtml += "								ORYC7RP1q7IvcPPTvhg2g2bflb91lgNhwLxx/X78IXI0jOv8jRVijouQ2a8aQjeDbaHN229o4pq6PQ01Gugg01rHDtqnj1KlM8FxQicJ9gKICYY+EkC9sP0WqV6PnrTSL3nGc+R3dRWFF"
cHtml += "								XjyE9aNpZFX2U6u2gBBJHHD6NQ+ijvrn1T7PcNEuUJ3l9gn1hxTUcVB9+O4+jt0IuOLk2o4Syi9VqPbrPRKKgt6+X+qHuDVIMcHsvCbV2UzGX6JTVkRwNbghT4+g+kWszZoJj0L5UfDGC"
cHtml += "								hOzzHIEmLxcJRqonQorxpJABLtbcwVGrEx2XgQSmMUJ0LdkHVi6WDuHQkt9wJB0CRx1NV9jG+Ey/nSlQ+UPifLnED1LyJb7kj9Zu6edQ5aFVovXNnUvCi57tHECBSVe6xCbn0UtTEO2yA"
cHtml += "								GrvgjaO5198WSSlCkZpIIPNidk4qD6sPTZRpc6TjF3k/UC9c/iZSNRvVwpKKEpWE8jn+WylD6IoYC7Rm/cf7Usr3HWyYHeqZttzqjDyaPr701fTnlo+w23TvrQiSniy7TiRB1d80qG2Wc"
cHtml += "								exHJAorWbjSr5YshbkoTtCsu06mb/jRL62UvjWg4Y/zHAezqfnDdQ6+HSuZ+C+1Eu0wSo6j9s6Ci9dg6KwTFkQaJVoX19faMIVC5+zFNmYzVAF7pJpwi3qcy5W/Yae3QVyS4cwcFFwIJ2"
cHtml += "								4b0lAzQzy6WTjyxauje3u0b8up7W9c+wiH1Tikk6HDD3fd1t3j9pghvkleqHqtoZU4kt/P8MZGlo4EA3mEmVCW0fX3xbS0kfoALkchzAEDRJFTUrb1OIKHMIUhB04RZS5lCoU6XOW55Zr"
cHtml += "								tQ9xOMPRKlHgbHXDBM9nNscIKvBlkcWtHSabWlDX2PLFYl/KiwfX5Q8z1ly6ob946+jqhoaohvJYZTwJeEGNDJqj4M2+O43agQExr99zAodQYmaJQvny/ZpoahJBPuOJo49m4ECaMK1Eo"
cHtml += "								bn7+XwvmkTtfXYcxyEMQYNEeRJI/ycdXThEv2nv6Pr7j360dENv6nvnjR2d/bqQLol2dfc6bTsvRHsXUfUz0MYn9i46nEOdatNPprtspFWDNiOF8pOF+icwVFy7S/W+wBUke4NcGw53Rc"
cHtml += "								ll/UNEe04WjBJAe4zUGcMVjxRI4rOp/RBmlujmxKwRqKGo1ksESvtuTRTkQhxIE8+jRMGXwSH6TVrxpV9bqAaQlcaVvP/Dmuo7D3AgY9ElUaDg8iOBaybf1dydRlAuLAorqm8x8Q6AHtu"
cHtml += "								OoWyk3sqC96d7JoCCuKxzHDTmrjyRJ/nrQm8kWlWGJhQbxiAql5h4ar8fT/qhlQu9MjenRKtuP/jzXNqICF/6m0mORZeu40BaeB4l+viJyT4Y7xObRNwtNV+5bY7HIfqBHol29/b57i8X"
cHtml += "								eRVRJDSgxndFe5olFt3FN2E6kvMvviyk1hKQuPN8tutuQ0LL3C7iIDnTwAvwjk2a47VVLSfxZTPcYvA5Wujq7pnptomaaQTy/0gC27uoNZU5JbosYBf1rqDQ4Un9d6fgENoZyhKFFhDqp"
cHtml += "								qZd4rffOZ27aoJ1lHokCly/32odWGjOrl2hZ5HLzgud3abfD6X2YeNvpzpRczzqSvVpadM1Mb21veMfS/2ensgVjxbJjuddDNqXin5UVcsCGeSthpZWfJombtc1oL4itYYo6lSgDLgrMJ"
cHtml += "								tEIR/DE9EKL/m/bdY/YdCUGsoSrblT9+c57vSeBQuHMErnn3HolyiQeu6eEGo214H95pLChJ4FswMLbz80YMYPc3p6e/8jCaCkJuTLMRayG/d1fTfxyq37Y8g5mCf9YKbz3YdNqUWXOCg"
cHtml += "								GpUR5kjcm2CmGs7RRVHn9dVAdWQyoEWuzNUnDgI15JNr4+MlXS9ZSJDGcJx4jkjOc1zGUJZpbVv0yyhtkLxfN1HfbnIBD9A9GEgU2JldB+3Cgt6WHunrK2vzigfzKqD34q1SJosQ9cLoE"
cHtml += "								h9DE1sRslO4qXfFl39oEwO/36pvemeJI1hu0V8MO6GqO7jtVRM8xr1ralmsaNDOPRF02xXHQXFxSJoM04ctcGDelhrJE0YolSvxc8Ui+OCGbuoTAOJhKFNzOsIQriu/eU3RlIjsD+hS5Z"
cHtml += "								ycNQBOUzJ7UAuqcAaLMWxl1CIfQxFxvcpsThZeEIL+0s7t7vEM4WfMcoe1szy1d2j0cp8gjlMwHsX0y111jB6MZJJpfXvPaeFv6Jf620Lu+ienUy6Es0dCDadQXyhVDmauae9BPmEoU6O"
cHtml += "								7pCz9WJfQqGoivAIM+J/sWJBUOrD6Bc1duEQMeZLcE5cjJq7RWMpD/vlziSyyhUrwAONdmfxqeCue1PVFtIIcn+XiO+417mj9k3NHVbekQRq3GeVIoAshr0FQMtEQ7FfdDy2GjhdKUgjI"
cHtml += "								ciAHPo0Tb1CchGUdfX5/9BrV+REX8732/CtIEB+ofBkgU6Oru3XyiRuhmyq9I8F0zRV5FswOLcsrNsdNfbX3T2MU+1IpUIP9isa+2YhXalm9MtHs66gWNNAt5zV08XyQp7yJamf1U8zYj"
cHtml += "								+NJMLU24xpY2eHl0yWkb9TGhRKesjsSHlXT39K7ffYKIXL3AEsjtI3T5FHSeO4nCW+g0xYYbvb19S9btpGYnnvSfy9eZamqEYRJVkF3xcKp3hsgzv/9OL3jOAo+8VTsuVt01ZuMCI4A0X"
cHtml += "								eQXS51XzZO8NdmBvgxSAeq2Jb9jnvQ/koA2pV965ea9P8xYo5Y7+bLgA6cURynklVWPQptiqHWccviytJJKHEIdU0kUYvh4tpvfzmTv7UlgPrFJntuOiexD0U4UNIfiH0vXQUGG42LGcy"
cHtml += "								ZR5IjKXTfH++44rkgQvea+JSHkQNrdh9Rkae/sGq/JLRLahYLHhAP1D2Mk2tDU8tUS/8+W7eA5ZxKt02yei2Fr1vguGQL3HKFn4cLws4dybg3E+IoO1u85AblHLU25KFljEjJxCBJQ1cz"
cHtml += "								32U5+x/C317ZEfPinn6CwRCvU1DU8zTlafVsCzMa4TFRlkVXBk/zR2rX6tuY5KCaTKDLUhFY32hAxTzJaJEvJN8DFVfCcSVRhakmh3+AGvLYn4UiVtLZ3/t+K9SiAWszS+T7bNLZcjMAY"
cHtml += "								ia6MOvwrvuwjK+ek/JrAuKrx7pkCt1yRV6HAPU9nvZoBYha65wrdsi08cuYEFew8ff3uowEZXNHNsewL9AkMHKHdKk2bpNypa/h8nufTdwDq4kngrePDBC6b4ojmqFJ4PMnvpq/W2NciC"
cHtml += "								dlHcYogH4MLqq1dZFKJgsEdko16FFx0xw0HcSyG8FxKlJoaegwtFg9RW3APgES/taFJlC+VahrlNg6DJVpYce2NSY5QaUQeQbkE/Maa2sfbTl2TxJyb6Z8P1amlb6mFTwk0L4Ue+cg8C0"
cHtml += "								TexRY+Zy28S8Z7ZE/yyvireO+/ZDE3H5jJs6VTdefBh1YuqA4hJSvkpx/cNnbQFlvll9eg7aFU9R5P8ocZzpdvqm0EcTj97Giy5rniUQLxqeJL+LASKFZ5aK8wtQocXvzKKK37J5laojq"
cHtml += "								NK35zkv3dh404FkN4PiVqmEEkctqOE9okKjZkCw7dGCbRzq6e8Y7hHJEDVxpIGSQArVbVPk4tvRd7+npI/BWPveWyTWdlm0odtp5fd6gyPLHqQNbN/MsNyYVXRgpsRvBWnL2sZ9rnwNHV"
cHtml += "								3fNvSeDTHlqF8aSfzvW4SeuJDTlwCu1/pwwG2W6iUwS0QPBhghv36v/3hzWk6hFqWrF3LNUpgqLho1mu6rUoVFyS7ce1bk1mXonajBTKNiVk4VgMYYhIVLENAplBJ9GdKXmQlUfwJKe1d"
cHtml += "								G+o6OrubW7ramrrau1Q2zShuxv18kPV4bbFBDOMjWZ54G6iFlXWjWBcKDgkUGfiEEomrYwg1bdoQF+jP4y20iRpD14nNFDxMSXH8y6gFeFkB5sneXuyg45J6iZuiyJ3QGnUo4TxpO9OW1"
cHtml += "								165RaOiDFDQqIiB+aO7rORaG1908ez3DgWDuLgvf1pCQfvP8WxXPn1UpP1ShvBjpQ8tCMGrTNz76lCHIKgoaXt3WmrnkoUPFi+5NAZDfOQXDbHE+9JGSFf9gnUyeqTCiOPpKs1WcEE8r8"
cHtml += "								u8GrVPoZuQomO4NlAC3y0UALFBPyLcq26BrDx0dIzQ1/NcyhR1LZkbPYckf0r4+03H6NO0hxcbdGVUYehIPn9jDXX+7GEHIBK4zeTHcdYyDNKqfsgm42K67WQTamVCU/qGKk2HniioFyt"
cHtml += "								Y4kn/d301RqnJaQUlCPBqzRPjP4n51/EhwnsIg7C+8YBFMaX/eCqa2WMqSTK4cu+XrYurfhSalEFNJLh3x3JedOco9XuGRt46dKYeA2d2zp4ziTKFb8+wS46LmNbUg5TO55zqqiCXnJpl"
cHtml += "								ihPOs9H81wUI2AqUfAARwtkUMRCVYB/Mpaenl6BPJhjucqTNHRhZpoeP4Fajp6yXGkQeRNnj63H4MenmZgv5cqC8DF1oMJ8Z6r6ZF2hXThp47Kmx21CuxC1bIfkIYa2Lg6hCZNJVGALdS"
cHtml += "								M+rARq7/GO4RQlIONJoWmtYxsUOs+ZRFGX+yp8uH9ok6jANsSs46Idnd0TV0ZAFfpvcQDcE/61H6zbncIR2kJsTTq/TTJwdPf0oqWe6p26kNBvTXZQbfDV09uH1gGS6z2eRFux0t7RNXl"
cHtml += "								VpHrHku0ivx2qZaiQ49+bpr4OjlB+1nldS0lMKFGNEwALKq69PtGOup0vmEA2x1vXTGMKz51ETTVHF+TwzQp/6gviSb9e5mfW2UWxyXmQXmMs7dJpn+gwjvJrd1GLSGRL754xG9Akpox/"
cHtml += "								QJ02xkKmWn5Vc/fhJ3Pdn2YUotLL1K4o353JUO48jY0n+Wye533lrrN5ZdWEJkleJU/yzlSnWtqEFTIDLVFg7c5kauc2GLS6RbbQYseB9DFkJdrZ3QPuCbmnUBG/Wefo3q5r+GyBN8fCw"
cHtml += "								SbQZJ1UXd09fPB1hXa+sU8rJVP57gyB1iN1Q1eueARPvFW50ebxvIuj1NaISqAdru2rWwBkhZfI8+kISRdX4t7amIQsotImS1Q6edUG3WWtGST6sOkxsYG6mh6Q8WWfL/C+9YDRDoxDVq"
cHtml += "								KQZ5eu30WX6Gvj7QxqKehATaK9vX2QL723Jy5et3O+77bVG4/uOpG/InAPuLgfzHTWvejZULYey4I657PFa/dklfseyZfHpluFJi6ISlmzLyfwWNHxczV1zQM78ajiei11bi0YXyZR9sX"
cHtml += "								57zlB9nI5AtlMtxgdc6+v3n6Atlp/+rbQPCSVlpau30nxqyEHu287pjiqDTNIFEgtKn9tAu0qYHz5skC1nd21MWQlCrhvS6TcKpTOo/gSkBIO0T+eSjSz9IqlQ/gYS1t4HhAP+leEXjMa"
cHtml += "								nOCJo+J07dFoKE1tHeuP5r34nc8vpvu/OCNg2KwNw+ZEoX9nbxg2N3qYdfjIOWF/st22eOPJwqravoGpXdu7uiY6RUA2Iicu/He8QxgcBSn+4LKRnPQgV//d1E00yfT09qIWOzk38KSqr"
cHtml += "								Yy+WbFOXaKQqrKDOteRA+aRKCAO3ks8LKmSByP6pU8w+L7jUJZobEoedbM4QjJe203TG4olujUx541JDqhNQskN4OYRtmbTUcqUGqM5Wnj1K+c9v7QOHTYjCNsPAWo2I3DYzOBh1mFgnF"
cHtml += "								khP8akVtzu1zCPNmzDD1JfHl/214XeDS2t9U2P4S0+7Ufhil+xkJ/Qt4TSOSZOTYd89H0B8Orrm1qJNWikQzzJW5Mciiv17OhpNonW1jf90cqVUs8TJ8rHLvR+2KhnbfdQlujpkspRIvX"
cHtml += "								hbjCBfJpzNA7RP5BEcy5Wv2qpZSBbYahUkIYfYvrtE21A5SnbnvaiFSE/0CFFmRoscNiM4GGzIt4Xb96bTZ3y2n+2JGYTExhI/ZlcyesT7IouXS+rvkOUTcp058vGLvJR9f1oIyH7/Gjy"
cHtml += "								Brk8yZuT7Mtq7hRUXHvVUk6+EGTff0sCGh/r6dA2m0SBXScLRvBpY8WQ8wQyV307pAxliV66Xqvp8xZStIDJFM3RF550dvFkwZCaahegG0/6zlSn81cNnhqm4s6jlikB8cNmhaMakipFf"
cHtml += "								WYd/ivrkKBjRTguEwFSfBN8B3Ligib5ksPpZ1EnNsqsWKKQPjPdN+HTtHP3YaNaTuXacHjiXSfz96YWUiYzQVNioV8sPk075pRob1+flQdt91AwLvqmaNZ5XR/XGcoShXKW+JI6TUECWb"
cHtml += "								SBM0A08gIkPXJvSLlHqwnkvkalEdDQ2i70PYSamowqT01mFfJLq5CQJD2NN4OAjPUZbXNneJ3r955cvC6WlOFQTUv53pZGoNk83pG8wBd9Udt1S7zLpnjiFaoSGSKUBO3XH6E5JQpcvnm"
cHtml += "								PqBCo7i60gMZJAlWr2OkMZYkCjpGH6EUbhy/7ZoU/kw+I6OYFNIGG0mWszXgSgW2IcS3SJRtTwF9FjitFeAaZVeh/zwpOKTXlUOr3LtHUHEksyEY7o5L81V9byJl8CQJAw62kCQyQz/i2"
cHtml += "								If+yCVBLZJ5kjIU8jbZajY6ZJQpAzMStqhfZXJsRAnnAnpM4EI3nTqLvfb/KhFPEj2aco2+mobjQ2p3JOJCxvLAsYBc1B2gzVPas0r1ru0Z2Z1W8aBVijH9Lt1kRnznG1jbq2kvaIIL2n"
cHtml += "								SQen5QjuTbvTHUk1n8qf+RJPp/vybBsAq8EbWWkipBr8/pE9Jl9NT+FJ/n9D2v0tmwB80sU6ha0uIfutvGk736/+kKV5q/sPHcSfWuyI5P0Z0hLW8fYRd6UG1Zc6NUJdrtPFuBwRvECMV"
cHtml += "								6nngO0GU/8skAam5xTcb2WPJFVN/XNTz53jB1mDVUoTW/G2ewNnoe0LrA0lEzw86Hwo/j5lP/ypUsDGA0PArcePPpolpt6kkJs1Aih/Y9P0In5JQrkl9e8OcVRg7srkIPTobGoes4kOs7"
cHtml += "								mJb50VfTRm/cfMc/JuglC3pMmb5QnBY/JZVPcnTqma+Xrm1sh3aAdlFuGNtN6wSnqiOaoNRqERB+rWPnVkrVW7jHQNE0tvgTPCQ63tkfdnHZxmHUoVWb9MauQd5ZG36o3zaYNcPP0vEU1"
cHtml += "								vmxHMtOpcF09PbM8N0PupEZCNp4EVIRP0MkzkSjgtjUeubv0kosr3pGsoXx83iSKnoUzbsWfZrn9/Ue/b23WG2CS4IVrt9NHoe43NKPGEb0iBYM6gCeFo+KgPckF5VCI1zW2gGQaWlobm"
cHtml += "								lvh71sPGvLKa/anFbltjp/gFPH5Au8xFjIoEN+Z6nT55r0XEnMuaI6XbsSk0y8W+74iknEsnDgWjujJoVklkn2xyHvh2tgNR9LhlZy7cqOJNJbwjeveYVZhVJn1x2YEQqPUVP1GrU86LB"
cHtml += "								00rfZQGbFtcakh38/x352iIU88NTSCdSyHUd59VhJtaW3X8sFM6YdWrvQP2g5micZnl6qthVAZlDhQDMFVoDw1wGw5AlmyphHy2OO5Lwlo38XBRlyLJ+FwbUYLJB9ZQ9Gw9svFvl8t8f3"
cHtml += "								QymW0QPqSYgQe/oX7AUOR2MC1oBZ8ofFx26fzPOhfmKcaVzxKKDtdUvmgoSWvrBrca7ctCdNdN6Ipb0S8kAocSyfICm9Osv/WJmCB7/a1O5OCDmf+t3UwGtukyKyfZh3G9aTuImM0K6OP"
cHtml += "								qE1/VzcOXw5OKaQSDs2A5Pwy9JEP+vIRhYHmx9tCYwGH1smzkiiQnH/xFQu5hqcQyJeu30VxmgazRNPPXR5Nn1rQD+OI7A6cwRudk4EmgF048TkSzSoFIwbeUKWqvr0g/IKM1iDiikV2o"
cHtml += "								WjqAvpgCZK4tnhReQPveHnAbspUPLgnaHNfrL4DinWOiYPoPp7tgcbo+XLOhNUckf1/jV9NVZdJzCr07aVRNfeN2QiLzs6UfEpuIBsUPba0TaV0U1vf9Ik2nweM2AcZtIdD6+QZShRYjj"
cHtml += "								5nSPPYuWIo8o/nqVUjg1mit+43fDrHQ8crNtSgQD+UrtmJ6+zqkSimUlJemXHGtfnLAh8k0Y6ubrvwA8p4aYUNSFdga2EfWqdvFhjQ0NKWV1az/XiuU9ThH1yiX7Vea5qOXIrNDBk9Lyz"
cHtml += "								tIqNREL0oOnggE1MfHIwnGSWUGpHPpCH7UXpS2nJgUNgJ7Tz0zZ5XUd/0GKpcukTDDuqa6bV641G6RCc4RuDDjLl1v/7j2W4aMjdf9i+bAHK/EUj0nSnUr0KCRBPVdzNlSG1986f08Wqh"
cHtml += "								vXesMRIFPLceQ+9Xa+VmmMEbPKhpcxwFTzq6XDcnvGJpR2QAY6+oqGwFcqEtUYsCnd3d4PW+jVJZigpOiB18V/SHFJwEaGcauj050Nvba6GYrkARWP9tRtAvZwbtyNA/vZshWxNzwI1Hb"
cHtml += "								5FoMBAmVTQ85npvNWL5/KXrtW9PdhwOTSBISRyhBP0tsv/zXI+rWja2ptPc2o72E1XEozKRg+59+pyijnAsV5FP4Vg4TXAyWKIA+EfozlHKPI0N7ocyaPH4SQeap6V+nxwLx2NGSRRiQ7"
cHtml += "								WoyEEtNsuV9E0VGdLY0jbHaytqKCrzdj9MDoVFXFYpjloLKfllAtvQkcRGJegsvVrFDjCR61D4Fa+Nt/3OOfpC9W0sUQWXbtxbE3N0nCxk7GJfMGhSLvHfmVZcafRKzsnr4wZIolA5hx4"
cHtml += "								/iy9jCnaeyB8nDf7Q2vXdaSvB3p+++hubQMfIQ3pnkGvjVHHl1DVRf1vkq4jwd9+v+nyBNyS63o/Sk+nr6wvYc+KrZf5fLPZV2NjFa7nSoEraJ/fJJOVe/Hq5P7xBfNaStV/96HfgtIbm"
cHtml += "								ExMC9p74x/KAsYt9VPfw92X+25PzyM1RKI59Yo+PXeKnCgP3aWEfRtlwmDl+u1O+XEp66iV+fNsQhrNHNNLV3Qve6XTXjX9fuu6LJThaIwzuZJpz9PVazZ/VIgPVaUL2eSv3TX9b6POyE"
cHtml += "								LRni/prUG+TusGPItSWeUUk+2Cmyz+X+8/z3habkld150EnUTeoSVQBCPJBQwu4tf3ffGWC39EBlGiyKSUKwINX3rhXXHm96NK10qs329pNMEHsQUOzIsJzV24yXB5Np6G5tb4JW11jSz"
cHtml += "								uDaTFQEUFIxSlQyuj+cLhemlufkGMj99iTUYUBgwcH1wwfMApoh6tig5h17JNoEHDzD5seq2I21OC52mn7oevmXn0TtJUiDp9x3ZKwNGD38kA1c90cH7gvFWqI5Pyyimt36Y+pQaImZLL"
cHtml += "								/wNSiM4N/ZR28N8f0a19YWAYbAytR6dbTw6xC+zs1l24zQ8YsCM+5bJpPrLKwDGYGVqKb0y78YmaghkXb/TTrsP8Vb2p+YoK9CFlYBjkDK9GaB01j5hu1QFS3WYVOXc9oAh0Ly/POwEq0"
cHtml += "								t69vot8RtMcCRWP9MWIC4O4sk424sLAMZgZWosDhgqvDrEKMX8lNN+uwj2y33jPdejQWlsHMgEu0sbWD53WAWM9NE5sRNiPoxdkR0Sf1DByzsPxsGHCJAhmXbo1esIHo2qVJzlCbFWHhe"
cHtml += "								7jlicnWy7OwDHLMIVHAL65g2Mx+b7xgHf4/y2NKrzOdPcfC8jPATBLt7um123GmXyq1Dv/1oqijBbo+UsTC8vPDTBIFOrt77HakI4kausJ7RhD4t++JtyQU69onkoXlZ4n5JAr09PZtTC"
cHtml += "								19e2k0mhXIqDoNRAM2VqF8r4MFVxmtgWZh+ZlhVokqgMbkgsjk0fPCwXfVNRgDGrYO/ch2e3BicWs72z/EMkR5BhJVUHnnkdeRvA+kmzWodEbgizMCJ/of3Z9bWdtg5FowFpafB89Moiw"
cHtml += "								sLExgJcrCMoj56af/B5eDjVaOXy33AAAAAElFTkSuQmCC' />"
cHtml += "							</p>"
cHtml += "						</a>"
cHtml += "					</td>"
cHtml += "				</tr>"
cHtml += "			</table>"
cHtml += "		</div>"
cHtml += "	</body>"
cHtml += "</html>"

Return cHtml

/*/{Protheus.doc} BuscaHTML
	(Funcao para buscar modelo HTML da filial posicionada)
	@type Static Function
	@author Calabro'
	@since 22/01/2022
	@version version
	@param cLayHTML, character, (Caminho no servidor que encontra-se o arquivo HTML)
	@return cConteudo, character, (Conteudo HTML retornado)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function BuscaHTML(cLayHTML as character)

Local cConteudo		:= "" as character

// Verifica se arquivo existe na pasta
If File(cLayHTML)
	// Faz a leitura do conteudo do arquivo
	cConteudo := MemoRead(cLayHTML)
EndIf

Return cConteudo

/*/{Protheus.doc} GetLogoBanco
	(Busca logo do banco na pasta bolto do servidor)
	@type Static Function
	@author Calabro'
	@since 21/04/2022
	@version version
	@param cCodBanco, character, (Codigo do banco a ser considerado para buscar o logo)
	@return cPathLogo, character, (Caminho onde o logo se encontra)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function GetLogoBanco(cCodBanco as character)

Local cPathLogo		:= "" as character

// Defino o caminho que encontra-se o logo do banco
cPathLogo := CDIRPDF + cCodBanco + ".png"

// Se nao encontrou, busco o logo a partir da BASE64
If !File(cPathLogo)
	cPathLogo := ConvB64ToLogo(cCodBanco)
EndIf

Return cPathLogo

/*/{Protheus.doc} ConvB64ToLogo
	(Converto uma imagem BASE64 para o formato png)
	@type Static Function
	@author Calabro'
	@since 21/04/2022
	@version version
	@param cCodBanco, character, (Codigo do banco a ser considerado para buscar o logo)
	@return cPathLogo, character, (Caminho onde o logo se encontra)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function ConvB64ToLogo(cCodBanco)

Local cPathLogo	:= "" as character

Do Case

	// Logo do Santander
	Case cCodBanco == "033"

		cPathLogo += "iVBORw0KGgoAAAANSUhEUgAAARMAAABPCAYAAADIkiGAAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAQnAAAEJwBJs06NAAAJSBJREFUeF7tnQmYXNVx76u7Z5/RNmhFICTsmABiE3kGvmDWxGCDTYLxAhjMiwQY5z2W8BBgsB2zB0IkyGfDByIYHMCOsYMd/EVgI4yN"
		cPathLogo += "w2L21diGkQQIzUiaGY1m7Z7ufvWre8/V7Z6evRkkcf7fnLnbWarq1KlTZ7m3E3mFeHh4eIwTyfDo4eHhMS54Y+Lh4VEWeGPi4eFRFnhj4uHhURZ4Y+Lh4VEWeGPi4eFRFnhj4uHhURZ4Y+Lh4VEWeGPi4eFRFnhj4uHhURZsM8YkLzn953f2e3hsr9gmjEm/hp61a+Xd"
		cPathLogo += "6/85uKHgHsHDw2P7wDbjmWy+/d+k9pKlgQFRB6VCDwQPD4/tA9vMW8OrEwmp0mPNqlXSeOSRZlAkYY88PDy2A2wTnkn32tVSp8d6DT2LF0uup1syakxsHsXDw2O7wDZhTHIbW6MhTXVTk3Tce7fklbIE/zw8PLYLbBOttSKfkV49ZjVAUPeScyTdskb6/TDHw2O7wTZh"
		cPathLogo += "TJLVzJaoh5KqMKNSo6Hvxu/YPYY6Wcn4ZWMPj20c28QELHMk7XX1NkOCdcOgYF4mv/ycVO19gJ6p15LISEoq7dzDw2Pbw7bhmdTWScdhhxgxKQ1V6qGk9dj2fy+SnkRvOBnrDYmHx7aMCTUmDFnYR4InsnX4EjxrXHqheSZ9waUNdbK/ekR673/AJmMnCm6fCyHaOIfz"
		cPathLogo += "pgGaXXBwfNg9i2c3g7CjIZSB4zOjpyYfj9II9cbpQ4GO7ICYUGOS0eKSakiazztPEnqeSldKmklWFfDkT58ocvgnglWdbL81V5aKu5d+XSo0zUShwlV0OPlr9CQS0q8hqzS74ABPDL84kohJY5s43tEmj1UuaZWB4xOPsTKR9xsLhwDyQm/cQgJ6w/UOpxshJnzOpPXR"
		cPathLogo += "R6X3qKNk2uomSe02P1TNjKTyldL2ytOS2fcgU1CMCeCYWHaVTDv/solRXKQRVja9Lsav463Vkn/9JUlsbpeOde9JZTovtdMbRRpqJD9lqsgeu8vkXeZLatpMS2MGaQdTGONLQ7atRfq2dEtaw+Tdtf50iOpRGngidJqZTe3Sl90s/Ru6pH72zpLfaarNCe5wwJhMFDIa"
		cPathLogo += "1p25JN+uxa4/66x8n17n8lkLPAPu+YZUhR03aXhXQ9eaJosTj1sukGd/Pm1HQP59b72e33jpJfl3FizIN4d0OHo2hIFzAs8Jbx/+V/l3rrs+n+3uCvLKWXbbN5QH5NG9cmW+6bBD8u9On228Uidtr7xqdehRGujQhsM/YbIiILe2FbeET3c8TOgwxzyOH/9c3T3t4W67"
		cPathLogo += "TXLPPmWW2z0DUy6/TLo40aFOmx6YkGX+pOuSwDNhhiIV+S3lQypfIYl00iZ+e/9luazbfU/JX3ud1DY1Wbn0zMznuDmC+HQwzwl1j/1SEpcslWx32ujc3mFj/BDZV1+Xyb9+Qqo2ro/4BTtkD1sudPWIPPab4DURDcgsX7WDjnEUE2pMmHitbX3PzhFuy8XftMbrDAqo"
		cPathLogo += "mjdfJt+4zNR4sgaaJEvFifvuldanf2vDoXIjkdeBloa01nr3Tcul48ILrGwAHQQUoToMUOtMhWtu7phfsEAqG3XoswPD8eoxMnxY5DWhxgS4np0NajWPPCxd9//Art1MN/MNtf/w95LRRolXAjA8oOesrwUTnLnyks1EWaVmmX3uMek+/wKb+IU+0UBJBAxa7xFHS/qL"
		cPathLogo += "J0j25FOk8+hPSs9++5qi8MxRlPyMxtlxOx8Pj0FR3lY5DPK1lZLUBkoDTOowhl6e1Ro8Ft7D6UkEC8NZHUTUXX+NDXeIS8AfqXzxJelQ76TcgzPnqnd893Y7z3Ch9EFjh54mly+TWa3NMvPRh2XKDx6QGffeIzv/8iGZ88QTMr27S6a//Jwk7r7VjEvNJ44mteRylZJP"
		cPathLogo += "QLmHx4cDE2pMWELtPuIoK5SenzmRhqYmab7mOvM4qjQGO12rdOxTc9LfSL/2/hgRmiSGBeOT//FP35dxOgYt9b0fWlkAGvGiZq1cKQ3nnS+pqTOj4Rj7K5i3YSUjWaNh4QEy6bSzZdYLL8rkkz5ncVg29fD4MGFCjQnzI5NP/ttgqKO9vpsTSV11pSTaWmwSlF0bWItK"
		cPathLogo += "HdzMXn6dGRyMCLtiMSi9Dz1UMDFYDtjkakuLpJUmN7EI+vbbS1LHHKNGJGNGjmXjKg2VaviYZ+Ga3bkYFoZneSULj6QypM+/9fwhR31tePLhQNn2mdDAWcGgMSXCNkSTyq5ZLdUztVevrdGnSUmvXS0tuy2w75fQcPFQGE70nbtEZtx0uzZKJYeNPSGazz5bUrfdZvMX"
		cPathLogo += "lRqvs3GOTPnFg9KwaJE9xxAEG83y2uD79X9lgUEYKdJNv5fO3fcMzUCA1KlfkUn//j0zEhgQtSpjhjOAZoQ0IzwxM1KvvCLpl96QLa+/JhVvvimJdW9bPMPkBsnMnqvu0RyZtOdeIn/+MZFddpKqmbsVeGfkzWYyjFiubaNs/uMfJbH2bcmo15fa2Ca5t9+V3HvNaqzT"
		cPathLogo += "KqMqSc6ZJcn58ySx555St9ceUrXXPtKvXhbpjb5Q/uSLQYRWVrjSF14QcMFQVeuictVKqf7IHlKRZdYoQDYZzHBVTa6zfTcOeHMVyUAG0MpGxPaXn5fkE7+T7Lp1RqPjPaJx17lSPWtnye2xq+Tm7ymT9v4zGwJXxXVET50s02uUz3eaJL+m2eQpze9JRccGSaxvDeLG"
		cPathLogo += "5FmjHUX9gftLcsGf2yP0Lq/eZHwxIA5kwVwdesCcGDS0/u5/JPnyy5L9w1uSW/MHqdzQYnH766dKZoGWo6i+eUX0rhk5Mxyepl5shLD10Vmhu07X2l9T+p/8dZR3xMNHPyLdu82ThkOPkKkHHxTs83G0p7WEAsXI23wgst78p1ekZl2brcr1Na+T/KYNIi3NOrbvtKgm"
		cPathLogo += "81kN0v9n+8r0b19hbXjU7cgWiMcJ9lSks8F+BM63NK/Oty1fln9nv31tHwZ7RHiez+VsX0LLsqui/Rqsvbv9GpueenzAHhLyIg6BvScuHXk3X39NtP/Ele32iowW3aubov0jLlAG9DrexgNLr5mRH+edj6+K9iA4/hxv8SOBZ8Tj3I5330VuEchzy7PP2p4Y0rm4Lg+3"
		cPathLogo += "P8ZkGLvmnHvw2fqj+yyfONxeGejdcuOyKA314NK6fOOBZ01nLAkycQjrnv08phshrS6No5N7nLtrVyZH9riwt6W4Lti7wbO4LF2e8fQu8Ix7xN/wmU/lW196yvIs5r8AKgf0APqRv9NtV47L05XBOfesjPAeofXuW8MMAxgvmjdlW3jr9XzLyadE9MVlEK9HjsiQenP1"
		cPathLogo += "ZG0sBvLmeVMYnzzitMSDy3PN0Z+MaBotSpvhMQBL1vvcc7JpyWLZOGu+5M6/QKpffMmsct/mwGI77HT2BYKdjS/y0mexWlO8h4ReOHPJuTbUAXgybjK2YunXpV29nPbPftomZunxButZhgPeU3r67AKaKKP35z+2lR56jPHAvCfNPNnbLG2nnCpdhx4llY/9xqw/Aard"
		cPathLogo += "CpIVpUe8LvO8NLgVLY6dq98MLmLIbN5gH5YiHxcXkJfbH8PkN/lmKEMDcckbPvOfP1k2nXWmxRsODAdJS52QP3m4wD1kOGnOdP2/FWwj7371NVm//19Iv+oGc2XkAU2kgx7oNDmE145OJ4uajesl19Vm8ePIvrlG6vUZQ2GXn4vjZEk+BCcHJ6fcf/237brecv8P7N5g"
		cPathLogo += "wPvp27hG3j78cMmd/hXTbZcX+bq0rhwnF3MU9HowOH0nffreH8hG9Y5T991r16wqshgQxNhaj+RGGeyBot5av36ZeTbmPYeIPOHN7dJgZ1vz4egC+XGED1ZP6+bvrP81/RgWD4aS37CwF/UUfFmeBpI+8EDJ3fE9I94I1GBifOOtYOijCmXunrpmc1eutPkSmHBLqxmt"
		cPathLogo += "oLbv/3uQbzoQCPGnfP4r+l+hSkygVOJThuWnCtF/0KHSoUaF4QpzM7iPjr5hoXGhKX388cE1la+BMjqPP0k61KBAf5Cvuo4ctHSrsNBNLQUqyhDGYX5l06dOtT0zxq8G+Ac0QIZ78AdfDCN44hTHKWgpxD1bSxvGdzKigds5eWugHIaMjj6egcrbV0jrDdcaf0PJjvIi"
		cPathLogo += "3krA+Npzvp2TF0OcLS8/LemFe0tC69h4D/mGFsevo9ddQ6Orc8D/ujBdAbJZ0yXg8qNhcATkZXLV4ORgzzUvJ+MebZR0htSVq1vK44gselvWSMfeB0vdr5/QuwrkCy1h3iAu44hK4oXPS8ENIzsefVQ2nnqyGRDaA7Q54xrv4LiOAz4S114nbVdcZvlAP6XRqZaQVKBn"
		cPathLogo += "GpycXX6OxvzCj9oxGI6PDsW0jRgImNWZNrXoneodYE1BPEOIhaH+n/yXncfBxGbuM58KFIZrDdM09P7DxZLoyUi2SoPmxtPaBbsEu2IHAWl5FbBSjQo7VzvuvBlpjniDm1WCYucLv2YVaEoHXVqh1nDUoGzQXpuelR6WuQXGzyjCUHtK8Eagn/xNYS6/VGp+9UggIxRR"
		cPathLogo += "g2vUvYtPlez9P5GaZ5+VqS8/Z0GeelyqblxmyjqUQpaExmc/TM2D90v1M08G34Z55VWp0/wpp/vMJRYtanAajC719vjKHXMTg0Lppl6Zv8KbQ/lZQieYN6HHmpnzzZAwYZ3q65aeo04wo2begMbBu6HeehYskMzl35D6x1cZjRUhjRWrVkla6QdQAvcjUVbKJnSTp3ZY"
		cPathLogo += "Tp6Wt8qzYvky6T36k6ZPTqbQQyNuXXqp1RMNCRNC/eHtsjDQ/oUl5v1AAwH6kXEfmxSvuFZSq1ZKg5ZBWfCCjHOLz7AyyH9QaHn5Te3S+4VTbEEC+ZmHpenYayV33yW5l56S+jXrrP6Sem37m/Q58nObOiu/dYMZbOh3eufgZALdGPqe6643+SIP5GK6oXLqU92sP/FU"
		cPathLogo += "jaE0jWU1MhzujBqMq3h3xY0VbRwdm9OIj80Y+zEWjIP0jPNJ78bKLpAvYCzIOJCxpBt7lgouj3jg3R/GtyMBtBCXI/MwEQ/h3ACBe8br4jPym1atsvg2xh5qbBnOEzhe47S68TDvu3SvWWfRieeOBNKSzngPaYGONVd8k2gFaF21MqLVxd1yz31Rnm4uyeVN6HnmyQHj"
		cPathLogo += "aULLD1fY88HmTBz9zDVQP7yL5AJy4WhyUQaMhzAtaeJH6tniKigjDq6ZW0NexHVlQ3MxNi69KHge07/4XJoh5IMAX8zbkHdx/sydAfhw+sO8g4sL7y6Noz9ejjsnML9DPMcvoXjOBPmgc+QJ/cQ1/V18quXNc2h39JAv91u+eILRa3Ud1jc6D4I0gWIyn2R5h/mSP3QB"
		cPathLogo += "RzNAJlxH84NB8lFhJMY+QuDW583qbf76pZJV98r1GGaBNQywiGpl6Y3arr7K7uGG2cy+ntYsWiTZc4Me0oYQoQXv03x71qy2np8VAPI3a21PB8Isrj7Hq+CI9eXdn7YlZxk9w313A0tO78Nx6kWXSn7pRUG/rPw4uKFYpQ7j+o86ysbOnd+/28aW0G70FwHrTs8Mttx6"
		cPathLogo += "SyCnkE56wrbDDpF5K38plfPmECVwSzU+R4LxXZUI7o8Q1gPF6CZtnHfLm9l/jZg88CCZrD1dHEbjs28EF4MA+ZJPItlg80m23yYMeIPsvUEu+aqcpNpapFflCQ3UIUd477/+GplyzbWSrWY1IkYn8gqv85mk0QPgaySIxzNeg9Ogx9YjdcwQYOp550tCPZ/ouQZL+/s3"
		cPathLogo += "7NxtU6Be7TMYPAvBef7SSyL6yZPgnkWhr9fyiqeNEMZPqTT7NX83J4gnjMc3419vM3niBSNLRgFupTKn9xtvuU1Yh3GePXJK8L4b+6WoIbfaFYOrN+iiLdvKKQhlUpLOUcDV1YiAa4+b3/Yfd5ghcQIApsRhKEDIbPaOe6Trt4/asAADYYZJMfMfrzYDgIIZ9Bz0XvaP"
		cPathLogo += "FheDwmcAzK0cCvrcyg/jUSnM33TecaspvKvskkDuCF//qIgp/3S9pNVNxYVHmTAsNATgKoSX3piIe2/GXHslwJYr7W+rOlNBKDH0529fEdxU+kjP/pmp311hilFQidASouD+KID7G29UoGBiWnmlG+HOlOOPDcbo9iAAy4ZjLTuQZVAew9SOF563TgZdoQ45dqr7vtNF"
		cPathLogo += "/8/KtOXikGcrM0w/AKH8hwM8FfMOotTkHc57pT51jN0iPukIvVu2TvDCA0Pbyib13xTcp/57VS8mX3ixpYu2DJSgmY7A5TsAYXy2BjggH3Qt+bUlpheAHFzdxSWQnzZTJqmRhh50ClrQ/O7Xf6+xU4FhHgLBN3lUD0gZo93aCicl+BkOJfkcDNYLacPIfDHwJuhhaWSl"
		cPathLogo += "Kg+4+zCGsWj/+/NtzZvxKONS9gYglOSddwRCCUHc7D13SdejDxlT6ddeLhDkUIhoUbpgLr3kHOkcxZfu2SfDDPu0z/2tzPrDi1KhPahNhGmFkR8Bb4vAOSsMyc+fLGv/+ljpfnt1WEkBUFg8ACrY5grsbtDYkzpur9t7r6GN3PsIjC0yTU4LVl2cfKEt39k2rDKOBPCb"
		cPathLogo += "eea5KC/KYIxf9+2LVYmDzX10FhMNPEbKll12jerEId8T+JjEMbqf/LXRTTxnpBNfPTP4JgkdyAj0qrgM4Ca4N7+xOtB3DbQljjVfOH5E+p78X4sK8kbHepqY78KclCr1/cWoatJcvv/8WaSI5ploIxsJaJAsQW7++c+UUb6whr2lekQav3x6MJFFXhrwVCAs++2r7Xnv"
		cPathLogo += "409EFTpikJfmQ7r++/5zxGnpaWx4pYpCQ2vUYc9OrTrq1OFA1357WT7m/WiAenp16J3yyMO2GS/3yvOmhM5DYRUo89YfChonCsNOYHhkheeDREFjDpU50R00qHIg+Ztg+Zt8KQk51B/wcf1PfWqT+oD4R/v6k8MXzqYxqzuVDeD/5GOPNF5A3BMdDZz3UPXaG2ZWrHNS"
		cPathLogo += "nUKfWP1seWzVoKE1DJVr1xfoFUh1bwnPJh4xTRoeRO5d9ZAdYSLuTZSCy5wjAeOzWXtxvjzFNRVqjV0bcN0dt0Qv9jkDlXvsN/bZga477xwgtJGCBt/+k/8wAzgi0NNYwHMKjAo7ORtOO13mvPCqJFetslUoQAOhV0EJMCg4pmv3WWS7fBkSWs+lYCdqMap3WWDH+N6A"
		cPathLogo += "DwbBpxfjcgdB0xkfqOO+374QDYcpgxIScxZY/nQqeLsTDTdsqK8YWvjQ6IZ8ro6N/l0D+p2OjAVu6bX77TeDHELZm3ehbaT6iKMlOUio0CAaei8M3nAvBrTFPeSJwuhL/FOwYWospOKdsPz73neXBZWhbQ0R0mDrjzxGKr94QpQvisd5z5dOsw1CFn+00AqiwVe5vQFj"
		cPathLogo += "AXMpCgwDdDYceaTs9LMHbdmRJTp4cg0RevmSyeYbr47ebLaK7egpoB+eU3PdVvMP2DV5HwHPmfD7NSYjMH22pOpGbNo/cDDki6B1zBaE6knBfMZ4gXwqOrd+39gNnzEozpMrFazNaMBbwsA5RDJWbPPDnPGS5zZo1XzzClutwQMIXqILrHL+nHMLCGIyiskv7iHk0cLl"
		cPathLogo += "heoGJYwd9iFgpdaN8yuPOcY+QcCKgIMrr/LmFbZXw427q7IDfbhcX9oUYkzr+dsRnNmYeNUeHPGhyUjoIg76hz4WmJHQ8xwbgk6qv6EuosENnwH/rdwSwdoDRzqwML5D7cxZpXV9DO1ntIi33REhu8eeNnQYE5RxmhVsbVh8djCjnq5UIoIcp3/84GDMGIK4TnBOyGNC"
		cPathLogo += "OCwZD6wqzPgpRXrE8vNyXON3ltmqT0SnVhrHxB/fCuIqstPcd9sCcLeno33cBm5bwFBzBvDHl+cAHYlJY+N6+6zldoNkMJBgRQovFPRkerbyPQ57YlKYNceMlNMbApsNk4vPEBkmsCmO4K7zmq5vl11NN5mPKsB42s8IEWj7CEEvM/nEE4Pdg3Zn7LCvrD36kPRrpowf"
		cPathLogo += "GUawHJZiPFgmID7MVOr00+263OC7K6xGVf/daZGBpafA8PS9FbwBy3mlNqh4k0N2iZdet/MBlb4DAd6rDj4k4pBGQwPKd6y36+0BvF0N3fDiDCIdBXMSgbc6dtCeqj8WbF/HWAHml1JnLpHpK+4cdZh27z22QghcBz2RGJ1N0AZfdcxRNu4FYzUoNCzSdi8+x6worr5z"
		cPathLogo += "91MfGbhcNyZoxVMxGzRMOe6zNt9RTjDUYcs/SpZYuNDuwVOx/WcJsHL3j0U8O5nlf/dCeBaDI7GI1Pe/TxkFVK4ER1PxRF+xp5I/YGFwJ2wsDBPST4S8a50Mx1th7hMLaOMzDfFBKvS0P/5MUO/2ZKBeFcugFA9sRCN/PgFB52yT1CpXvJ++B+61ZwTzXlRO5OnuDRbQ"
		cPathLogo += "8aGW28vSrobAqOoKS8w7G1OUWQgz4kLlGi0omPmQzXfcNkAhxwNooidxbikvFOLxuHmZktBK6NEBFjGoNFMGdMQFRTw1z/kRKnZJgsxjD9uRvsDNC1U01lsaeojq3XY35TOZhc977rnLXh5jX4srw97UdEZPD6RPp/MlZ+yLoWY+PBsHiuoRpbRNhnrer8wVe1/2Bm9I"
		cPathLogo += "rkHP8TKdDKG/4i8ONr6pE5oe97puX2HPaY7Fb2PH02ZywZusnJcTo1mBaThgn62xQ4OY+Od/sZ2moGDOK2z0yMD4zG81Q0VsGg3IkG/JcHTvnmFU8jevkAxzigp2ULvPmRKPQAeM4Yh23arF4Rwdd8PwUihfKyuNUeVvH25RRir/8kipevD+4KYKuHgSaCSgUSGY7iXn"
		cPathLogo += "2FIq7j4C7/3TO+NimspwbnXV8mU2UWpbx6OmMBDBy3s19uYmHxfCuNGICMFHa9jOXKgOFbka2yvT89BDkrjjHivT9seoLJj3qdjnQOMPvvhafZ+6rubmh7Jixr71lLNsByjlBEoYcE6ZBEpkF2VsPeH9xYB63Gqico2NdoQ/6s6U/oEHjfYInGfor4Pdr9A/ad8DpF89"
		cPathLogo += "2ahONCR+9Yh1IsZ3UWWT1n0wPNm5xToE67XHoGPjBQ20cuF+tr/IAZ4qNq6XtiuvVOlUFngBGJZg70wglKqOrqDONXAsBRvaL73I9AGgQ5xvPOE4+/og2yZq0zUFBpAyrWNXHUHaTBVQV31r37XnYDQGs1wYVYnsiXD7JyYf9znJ/3CFCaqwmY0MTilpcD3f+a42Vnae"
		cPathLogo += "ZqTqsV8GEcYIlI/GXLXiFqk77/xAIbSSh/J+MDZUSs9Jp0pz4yxpX/K/7TsmfCWOd02omHh6zjPvrJZN3/imtB17rPGAqrs3gKsO/4TUzpsXGCFNT6OpPvkUMwrxHcMVjzwsG790oiQ2tVuetktXlQQlRR6dT/9WOv7PebacPhaDPWoobQVQWpQYQ/Xuu27dB6TgnN8V"
		cPathLogo += "Qk4FlKlis8s5s/Y95UA7np2mSv+5Z0WmHCm6TmTz8qsH+FNc9yd77TWI/K232z3rtYtpmwAEjTUp9eHWeQd4gPfmS8+zOA7Epd4A30dpP22xnYPBZsbQz0lf/TvTWbdpk3ZR/+Jrsv6j+0u3yjeXLfp5XPREgWe85dU/SudNy+VtHU5uufra4MEHhFEZE5iwTUam8DmZ"
		cPathLogo += "8oXF9mX2zsMOsYwsMyrdhWFAAyFW3/U3SI8q3+annw4ejACuPBtTalnumu+21jz1uDQs/qopswle6R2KGnapdrz8vCRa37NeIcnLfMefJD3zF0hLMiHrNP1qDetmzLHzdzT07rZAqq+60uK7ntq58Q033mBG1wyQlk8DaTzySKnGO1GezQBrGgxL6oc/lQ3Tp0n7EYfJ"
		cPathLogo += "uiu/Je2qGBgzyksddKj9iBO9FfGHQiKQxPhQymCFilu76CDJN84xGQOTk4a0yqlVad342U9bQD5r6+ql7xc/1aQaQxvLzhd9TbrCeTb4oBTS5y+43OK3ffkMabnhWnn3n26QDV/6G2lL1EpOjY298q/x4dw6HzIYAcg/PvoYK+wXBrTUqSedJL2H/5WZibi+1V53szQn"
		cPathLogo += "qoxm6Cds1LrbkFKP9fMn2wegMITFBrMAKl8+HVn7o/vM4BiPoUHhN6Z6Vb7rVZ7onpPxu/vvZzq4Lqne38K9JX3+BTJZjU/1XnuSekQItGnoTna0GHNOuKP2RuzCA+zN16R6AvazECoIAo1mMNeuGMwJ9Dz2C+lb8b0hG30cCBtrbkqtZXHOdxp2fuEFafj4X9o4cjSC"
		cPathLogo += "Sq192/JCEalQF8iB+zj5KDe0Fv9AF+W76zodWlUcqA1PE8YnfYkx66abpINvj+q5yUeDa1hJNRpTvnmFJFQxMGbRYrJ6OQyNXBkfFHiDtW75t8zDgBbHuwMfqOJ7MvBmntTsGXbftsvXzJLGlQ9YQyRtvI45z99zl301r/aSpVKlxpU84JbfKSI+BuWD4t6GFMr7zDv/"
		cPathLogo += "1QwDtAHogX8MRV5pTvJmsQbqjnvU6eajP2nx4XuwQTbGyryTk74kfZd/w+45rTXd0oCM+CVFZCwaGl58yWRMOa6TwRCl99/Xzj8ojLy1FcH1+mTAuG+qegLzurvMqLAzlF4a4Y+kAOLyUaSUe7N2GFiZqmRUFONZXmef3Lxa5l58kVZO8MFhVlqK5zmGg6s8R7M75z4B"
		cPathLogo += "fpyXEI+LIaPnnbRyZTS0gob40iH3eDV/zpPBR3/MdVeQHkUjP4Zo7j7KmlFDMnXlj0yZuCbuUHD0jBVDpWVVatqXz5bOS841fl1ZBOhDJtBPoD5rdttd/+uzZNBY+NxB4zNP2seQAPySjvSuYyDQKJBB6tJLpP7G6+2euf8jAIZn8JmxwRHnJQ73RjOdJt7D1DVN0qm6"
		cPathLogo += "jecQNOEALh20unpir0jjvbeZPDAsgw1zAAaXofaMK6+wj1khI/Tb0eTKMsOhAR1ExnTW8IxXTEc+aX4g81Io5m1kEh0dissYHVQINqscXtJ7YVTmPv+C1D6+SqqXXmRM2rNYQJHiAQHx9i352HUJuPukN6XTIUN21SrzRHgZr2HmbvbcaNFGzNg1Pjk2FFD2+uM+azRn"
		cPathLogo += "zl1iNFMeAndCJyfzILTy3J4A/lPxNXffZW8Y8/U4FM9WZRROLgazKyor7aWn3/t9maaGB8XkmxQoHKAMehvKz2ov1fjfK61X58tgfHULI20/9FUDJVtBz5dJVtqr8T1qXMk3o0OSnmqbugygdJVCrrfHhoZ9Yd725bPZcwO+Y2mYDWBOZ+drl0nl/T8JjLjej+ZCwgbG"
		cPathLogo += "vT4tOzV3bjTwQh7WINWgzH72SftRs3a9j5QsaFrX4/NtYFx+vhWS2qnRhlZ4c9DIRG5/YqC/29s4Q3rgV+knblZDOAdaGkqLeQtq3ONyhfdEbZU9Q3ci/Qnzqpg333Y9V9Bhalynk1DkqIJ/OlTb8zFphuTVuyKu5a80Su2UQLYhGAray6VaFHpYc9znTEYVqlMdhx1S"
		cPathLogo += "YKBsGBoGaGQOjjrHwE956Smp3C34VKYD6XJVW3mkjtGL/uqaqJ0U6Og4UbafuohAbiocp0iAiczOZ56X3MMrJbm5WdK/b5JaddVcZbijQ1iFBt4mrvr4vpKbMkuqDl0ksv8BMmmf4K1TwHDGanIo5RkOoRfh6KBBd69dLb1vNkliU7N9lDfd2iZ1qVpbIs3PnS2ZGTNl"
		cPathLogo += "2sJFNsEICdAcDWtiHslgsIrWYB8Peu1VSacDiVVOmSH1i/a3IRr5sWIEPcQHVD4xuRchFm8AlCSMAIpaSkbxfB1N8OK8Opv3AJoeo8Dw1njVYDJa/666EmmNF9Bfs/seUotSh6KIygyvmYx26XmlYsvqt6Qil7A3eKfO21mq1AMIqjRY3bJJaQXUwJ/xXoIX7rt8hwNe"
		cPathLogo += "VrCsr5nE8olkofkzseomUw0xfpz8oZ+f1ujTG0b/TtPsB9nI2cUhzwE0laDfEOoPdQmsPvVe+2uvS74l2ARZQ8aK7IwZtuUA/TPE6HOATzx1V368rt8PlN2YRMLTXFEcVmjYm0JFO4VA0tmuFunb0i25ja2S7u/hrqGqIvjhouT0RnuhKlHTYB6PyxdZOkWjwukxI4Uf"
		cPathLogo += "Ixi3xr2YuMKXQlifBvhjxYaGZm+CjsCQAMoEGA3XgKPyYlXi9jHAacB3mH+8HI1C+b1KWY1KeIA8LD9oCy6L4WgBUf7F8UOScMlx/20pnx8c0zjxBg9sCKwYII8wD07YO5EyXy/UiRA0AOqU/1nlqDavcdSnZ9hKwwBmtMN80QtW4tz3ftn/YzKgPmNFF0CT29BCoxTI"
		cPathLogo += "1BA7L04P/XqPMuNDaDP8nJCn1oPb1YwxQrZcpzWUrJtiuLriVPOKz/s5/XBGARqiskoYR1c2KN4aMd42Uwrl90yA5eiy3SqYQDQBUyNlplDRSRP+4JCeo8Q8jSvjWFFQDrSFdeoqzsF6eEMYgbOQN+vJtt4eHnERhecYMsePK3trmQHM0wjPAfEsDgPpmDDsPifD0ATv"
		cPathLogo += "jmfnxbhjQTquQ0TP45lzCOPwHER0hgYgotUQnBTPLcXz4YTn7j7paUSR/kTxFC6dHfUkbshiMH7NgITPY9Gc18JekfjnEQro1vhcO3Df8Wu0RR1TSINLp0BXBhjZGOJ6CArodLAst5aDYWSYVCAXECu3OIv3A++PMfHw8PjQIWbGPDw8PMYOb0w8PDzKAm9MPDw8ygJv"
		cPathLogo += "TDw8PMoCb0w8PDzKAm9MPDw8ygJvTDw8PMoCb0w8PDzKAm9MPDw8ygJvTDw8PMoCb0w8PDzKAm9MPDw8ygJvTDw8PMoCb0w8PDzKAm9MPDw8ygJvTDw8PMoCb0w8PDzKAm9MPDw8ygJvTDw8PMoCb0w8PDzKAm9MPDw8ygCR/w8F3sX3EolfgwAAAABJRU5ErkJggg=="

	// Logo do Bradesco
	Case cCodBanco == "237"

		cPathLogo += "iVBORw0KGgoAAAANSUhEUgAAAbQAAAB0CAMAAADadTd0AAAAxlBMVEX////MCS9NTlPKAB7++fo/QEZKS1A8PUNISU7Ozs/j4+NCQ0liY2fJAA/KACPMAy3efYp5eXzKABr35eavsLLY2NmEhIeQkZQ4OT/KAB3IAADJABVWWFxsbXH54+dRUlfJycrklJ7s7Oy0tLae"
		cPathLogo += "n6Gpqau+vr/z8/PwxsuJio3opq7YXm5xcnXV1daVlZijo6XaaXfrtLvQK0XhipXccn/01trSO1DlmqPWU2Xxy88uMDffgY3OGjjqsLfloqjOFTfQKUPUSVzesCLPAAAQeElEQVR4nO2dCXeiPBfH6wJBURipC26VoqJOq23HLtP3mc7y/b/Uy5rchIRFWy09/M+Zc+Zo"
		cPathLogo += "DCQ/cnNzb0gvKh+tP8+PL6/1i1LvqA+HVtG12nh883Duhn4lfTw0X9pY+37upn4dnQiaO+CMX6/nbuxX0cmgudhG+3O39ovohNAqlfH9uZv7NXRSaBWjpPYeOi20Svv3uRv8FXRiaJXR5blb/AV0amjaz3O3+Avo1NAq7adzN7n4Ojk0rfRFjtbJoVXGZSDyWJ0B2vrc"
		cPathLogo += "bS68Tg9Nuz53mwuvM0C7OXebC6/TQ9P/nrvNhdfBXX84NP3cbS68cne5Vhu320ZNrxnt9rimHQCvVrqPRypXd2vG6O/j7/VVvV6/cP9drX9/+zEy8oIroR2r7H2tD42bh3h/19ePNSMXthLascqMrP33u7CzH57bObCV0I5VRmTj5+Ql8dO/7NhKaMcqUzdr47fUih40"
		cPathLogo += "rYR2ImXpZeMfr5vrl1dXl/CL+3YJ7TTK0Mntb+yPXl/u/2ptX9rfe7wX9W2UyUSW0I5Veh+PmB0C6/uxtz4L+ej+wu1n4FY+1bJQK6Edq9QublObTOvX2pgzd2lG7T9vH8FlljVbCe1YpTJ7gaWvx6KxpGujvQvjMsNYK6Edq7QOhnnmtT5MLKu5y4LXcQntw5Xcv1RE"
		cPathLogo += "/n7kqjYc1sYj1wMZG2Rii0qPXJflW6rnX0I7Vsn9O7oiJdcPxMN33f312/Xjs87EjIf/1n9T7WMJ7Vgld+9/aT+/fP19r7WHGJyeIQwphmbfdrgaLBur9212kmxlEklunO6yOZTUu5qRbUxcvt3UeD5lbmhNU+FLlcyp825tTlHTlCOhgkHTh6OfOd5NWt+3s8b6E6Ch"
		cPathLogo += "qlCyNDtRD4K7kAoFTWv/EAf1BXp7bmcabodBc7GZuyMbm03FhKZr7XtqH3D9af3w/WW///Ztv3/5/rB+EmzIf7oZZcB2KLRqFZ2EWiGh1YZ7plv/uA7+sKb5qg2Nsevx/7i5XnPQXd2kxx8Ph1Y1TzGxFRCaPg6RXeJ3278bvNFYM9p/HuOp7KcfnNLvBa2KTuBFFg+a"
		cPathLogo += "/tfr0vr626/RY1RGFw0eXTNG/2Jz30tKPvQYaOrdR3UE9y6KAu3mov52Mx5ruhHlqh8SI1P6sH3DZLWvftQ+Cppc/cC+iN9FQaBVtF+G4XsT7WjKek6bpbT2LyazfZ/EORs0xfSFkCpT9rH5gZ0Ru4uiQIu2oepaWOJylMKs4gdC6GNC9glZ7EzQlEHw0arXnajQPn68"
		cPathLogo += "K1JEaBGHf2GJ74mhfYLtF2UkX8TUckHztAPU1MWHdIPgLooGDb/8d5MxQKW3byCNvdCJzA3tYirzP6e0srqLrkV7l6umNe/eLZZzK9GqNp2lW2a7it0FD1q953QXi67TS6oxKDNv2AllVtuwIpFHbDfmy8Udp4AYWnRSi9B3jP+kBgfbTxHs/NAsiXy+CT9b9CN1/Qb2"
		cPathLogo += "kaSqqoRInzibiel/6H+udkSGdTlDYZmpxdxFHNp8ioLSKkKiGq2OhKLLKp05F1xvNzHxvbXu4mW2gyosQD10YgLha2SXGfdYeaLO5KmLth7kh8b7vKOGwWTJw2iZSvC9HHXcrakqlAujSMqcc82GSjwdGU2aidAWJnSLFEnmYHNkSYGXVc1WrJQ1ofwrWTVvaVMwryKF"
		cPathLogo += "LjDdkm+FAGohtHV6KhoInskjWirkh2aTz/FCrRP1jDf2LBM3L/h2aVLAQqFpzBLdmVQJ2bTE0LayylQoow5bYQfFrqww6xR7yiljDki39CZSrIBs9vHNp0LL5odgGeCVwR/8oZYfWoOYR+w9Qmg26fkIGtu9YVmVsUN3sZWhadkCaNwHQZ1QralPlHgZeUJdE1sF5sLL"
		cPathLogo += "xAt5Nx9No8Lej8zjdeJCmUON7JJ84/si+aFtSCvNyIwQaIOLKfk+GVpVnjH9Fy+CLPJbCO2OU9a7fAtWOOXxoKF1+fXI06jAQBRi8MxACrQwa52+54PRCMcs63z7mBsa6FrSfgJttwWtTIFWVaE9W6VFYAA0h9/Xbo0bUuFS4pWgoM0F9eCncZdwU+Y2BVpo5x7zQtM1"
		cPathLogo += "DOUf1z7mhFZfgFao2IYAaFM4ZadAi9pN1yESgWaLmMEaBQ8BhNYT1IO9YifxQUJ2IjT9+UBolSE+vuA/7m8zQZM7DcuVs+wg0P+yyunwCZwBKGiy6y5LkkoFwogZumiKQYQi0OCDoZrVGSKuAmEyB7eq+Jf2XUAITeZOVxGN2MMhM+UDYyzue+NQaOSlar4Tky32KEuS"
		cPathLogo += "3+HUYDCJuRKMEgJNkdTb3dxqNJwl5a1hO8RWISsK26MYmgUeJ3XuuXGNFiaErDhZ1JlbW6u7cdeAMoC2YCyAogRclT7vnhQ0m7YUypNETiK0drB9bp8bGjn+6u0IaDyZYKEVg6ZICCFJCaEhcwOciCbpYWJhbepqitna9CeML46htci4kiMHtB/dAR685CIKfjKa7tod"
		cPathLogo += "Q6Ptp/tcdna7zdQdtVJoYinriTb+pbYtaGvkRGhG4FC85PQeXQ2j4PExIy0uVbJAWXaYoL7VXDWdcGq4GzArMjII5Nvwoy4ViL71O6hHu+wRNGBITRK+wnbZtBkkZOr1ZGFod/CSyixqj9UyOa0iafo++JnkJEHTgiToQ1oimkMlmtSuD5/T4pI2FAcamtKiF2CxRTSY"
		cPathLogo += "K5QYR+gCtmC9EbQF/lAB3qcT9aU6Z26fhkYExzHlx4YDDY5EmO8lA90f1uKuD6empxxhLBYaP9Z8GDSFiQXRxv+WXyHQLW53tGUBWCIZLLZ40IivQy23oxpCkuT2BbnaHswXTjkFHDKkqBUldJnc20/o+2BqEiy2vPBwqJhfj80jP/p44EhT1R0cPxBalnw2sUxhHnUL"
		cPathLogo += "1lQwtQpdwBARGAASrBMPAJktJmPTBwUXItzdLn3SKJUKlJJHrupOEgnQtCC2IQhG6dehXmKrscgREbxBc7AjoprA6kBo1GQH5aVmlq7mVpOwQD0Wjkw99XFoJIwmU/EPHKkJJzXoMEjqLraXHXS9yt0NWCUFTOrHYAiqiyRo+tAvz3cfwWFJ7GoM57wFmbgj9oigPi4L"
		cPathLogo += "oDGxqUi9xQSR1AwpLgXQQGpV7cLfDUDRABpxWWQqQLxT6HJTyvdUJGnapaZa8DV328QKhH6opwN6uu4tJECrGL6Z44f5ATQ20BUFwJ4E+xQyrtOC3jYRleiQcKAEQONO+84MxZZdFDRgihCV0HRisUfAVzaBcA2hLZuzUSwvpUImwRWcRVPar2zor0BTJonQ9D9+ea4n"
		cPathLogo += "kgAtOhBctCEoXxjLtjbU0jiKGXVEfR7UxEluMNDgSpgyRfHUTD8t3BU9NpzgmYymdrxiJZbS8QSzGcyDCPzHavKrToa/yeqeZ+XE0IZhIvRFtFbIHTC2gRuOzQaAJsUqavCTGyJoJvXjVQxaaoxSCWcoXtbAHZzRag/FfkDLAdCYhO1tZmjB7MS1j0Jo+q/g01fhJq78"
		cPathLogo += "qRloHMI5H3Qkk666EEdlQxIfAC0yZkvulcMFOfD4+fuToLuRsMJJeRM0cCB5hzuKoOlh9OtK/OLTAdCApxc9ggBabJEGJzM/cEvFMD8CGnaQHJNnImUWmpIKjRlpOaBV2t4rarxIlgjaaJ3G7BBodvwL0grSY6FAVFZBna7VaFjOnPiEITQ4KVI+3gFzGriF1YbZXusj"
		cPathLogo += "6LLNY+/ZlyWe06aZzaPHps5fXwugjYKtxutxwhauA6CB6EU0hSdAA89rB7sYZJIPoUHPfgt/Drou7j1WVZ4QvIVVt2Uy3AILvuIlc6F64klvRiqcpZ4jonl7VvfxocaFpodZ633i+07HQYsWwmJoBA/00SwW2pIT+A8QxdZpwDpP5l2eLPoW7PktosxkMBOr7AeM7Hgz"
		cPathLogo += "Q8Fgy236iT3GozvUcKhqaLiqCaBpNT8UcvWcHGM+zjymQyPWEZq9GDQwoOiVbDwiAiJeykVGrZZwtAUVwU233EkNhrmoL+DOz12Gs7Hae5IY0x48/a5xoWn+YXX1b2mvFR7niKSbRzBZcZsdQoMreRifAH43J/bIWROKtAJrq8CvgGYW8YYaXMdY8AsYlHQynUL338VV"
		cPathLogo += "uMAOstne/tU4NP+gmPreOOLwFyE0EJNLd0Tw80wNILLHKoR2AeDALAEvyk+6n41UJAk0J/BEwOKZjVMFAik+6nsYS3FpZ4BWGf74padDq+jr9f0ow4lmRy2u8fwjhkZ6WAWfguxKCA36hBKe1aY8aKAzzRzvWoG7DqKbMMylcnIzcIcIAis1cKueC5MFWgVv50+EVjHS"
		cPathLogo += "R1l2aJH3ZDeoMFYVhZ5eFmjAxExj6zTKDkbv4Nstyn+IoEG/T2bt2hwPvi2zuIotuwbwiVCq+PbsqAnQsyeWGO7M8/BngoaVDC2jMkb5Z54URAeMScwq05wW7cndzuCoijqDCu+q6qDb7TDhL5zyhI86Faywl1UTQ2v8T92BOW8eizzT+79kNLuzej1rOTWjbagW7AEU"
		cPathLogo += "DE935Qc/vPjM0Pwjc6qs8JwihkZN95255Szo/ToY2oB+HBRm6xeERu1sk+Sd07Ntu+csWu5Kmkxz7pylILWztJq23WxswEMRZceYZbochGtkEtWBgWH3QervdlMEf+NvQvi80PiKbwuPQbPgCFJUZt8jgJawATUqivMq9N43RUWewu1vEFpwSYRoC4G9CuGe5qhdTNhU"
		cPathLogo += "YV79CXL0BYOmcvJpLLR6Si0k/jEQvKZBipJk2ESYN2Ch8W4bZ1lFu8txIxaiOnwFoediQVNI9CchjDVgrZxfCv+PkKjHo4ReD4MwJchgcsv6NadDA8mjgaAMNiG3wh3tbqEAfqGgKTOSrUyAxrNB0h1JMxNHYst57pUpib/AvVdNEbV0aJGb4WvDbySJW03F7yGEu+oK"
		cPathLogo += "BE1GU/DLBGicXKS06OEOhTtC4u+wyMqqyYV2Yc8E1jQNGqJDVgt+hpasy/oCrHiDdWGgse/KJkFzWdD9gjYgfkglINmSysy+EEBzBwm3u8lG1wY/cc1uYWnE3ij1q/kfNiNziWPgpQle1n8uaOR4TCjXF0dmx6LLdtToa5WTm9oqwJgpnllpIH753kyCJfvUbbCHdPam"
		cPathLogo += "saSLarawY2N3THbVoKAWJ4RyJ9HVyIqk3oGNKqsBcx33e2AfPhe0SYujaWc3j4dpN6QA95SK7gyp4aGsHa/btqRuZlPNHJTs0bcx2bLVNndVU1Wj816Rektvkls5fQVJ0fcqUjaxGgI5t97uvujY2OrGYr73knJhPW41En2QwqeC9r5qznf9fn/npB9c15wP3JKLDCX9"
		cPathLogo += "0s7dxjsKY7fkn07SdJZedf3BnZMUp1xt/fvr77oW/7SRVaPr17OIPbJfGNrXVQmtgCqhFVAltAKqhFZAldAKqBJaAVVCK6BKaAVUCa2AKqEVUCW0AqqEVkD9KaEVT6l/3oLu7ytPr4YH7SrUZd5z6kpox4r7FrxYbU/+m0x6O1LeY+pKaMfqJf/JgMeqhHas8p3gXkL7"
		cPathLogo += "FKrnPxmwhHZ2Zf1TMiW0T6TX/Oc5ltDOrnxOfwntU0h0WFwJ7TPr+sQOZAntPXST/0DwEtrZ9fOkfn8J7X2UemBLCe0T6kE/nYksob2X6vv28ESjrYT2fqp/f24bGQ7cKaF9Ll0+7H/my4qW0M6g/wMDyniXLheYowAAAABJRU5ErkJggg=="

	// Logo do Itau 
	Case cCodBanco == "341"

		cPathLogo += "/9j/4AAQSkZJRgABAQEAYABgAAD/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAEAAAAAAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwM"
		cPathLogo += "DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAByAdwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAk"
		cPathLogo += "M2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAA"
		cPathLogo += "AAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmq"
		cPathLogo += "srO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACi"
		cPathLogo += "iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAGlsE0bufahxiuP+N3x48K/s4/DTVvGHjjW9P8ADXhfQ4hLe6jeybIogWVFA4JZ3ZlVUUFnchVBJAojGUpKMVdsmU1FXkdgzYNG5vSvzF8U/wDB19+zvoHiK9srHwb8Z/ENnaymOLUrDRbCO2vFH8ca3F9F"
		cPathLogo += "MoPpJEjeqis//iLV+AX/AETX48f+CrR//llXsRyDMWrqjL7jh/tbBr/l4vvP1Mor8tR/wdpfAE/803+O3/gq0f8A+WVH/EWl8Af+ib/Hb/wVaP8A/LKj/V/M/wDnxL7hf2tg/wDn4vvP1JZsCjdz/Wvy2P8AwdofAFj/AMk2+PH/AIKtH/8AllXVfBf/AIOif2bvit45"
		cPathLogo += "tNF1ax+I3w6t72VYI9V8UaXappyOxwBJJa3Nw0S5IzJIqogO5mVVZhnUyPMKabnRkreRcM0wknaNRfefpAOlFVbHVY9QtYpoWjmhmUOkkbbkZSMgg9CD6+4qzuryzuunqhaKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAC"
		cPathLogo += "iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAGuevtX4c/8HUXxl1rxJ+0J8PPhfulj8N6LoK+K2jSbEd3e3M9zaq7ptwGhhtpQjbicXUo+Xq37iOeGr8J/wDg5ZsY5/8AgoT4cYjLf8IDYLn2/tDVK+t4Gw8K+b04TV1r+R8nxtip"
		cPathLogo += "YfLJTg7O6Py9/wCEcYH/AFXT36Uf8IySP9WfzrvP7Ljx0pf7Lj/u1/R/1CKWx+BrNZo4IeGdv8H60f8ACMcfc/Wu9/sqH+7R/Zkf+RR9RiP+2JnCDw4V/wCWf/j1CeHP3gYx8Dn3/Pr7cf8A167o6XFnpR/ZkY/h/HFH9nwelhxzaonc/bb/AINl/j9q3xL/AGKNW8E6"
		cPathLogo += "xNfXknwx1o2OnyzMJFi0+eMTQQqxO/EcnnqFbhI/KVTtAVP0oxmvyr/4NdrZbb4YfF5V+VTrFgQM9P8AR36V+qxTkV/MPFGHhQzWtTgtOb/gn9D8M4iVfLaVSXVAXw1Ak3dKbKN0J9q/ln/4KEf8HGX7ZfwJ/b3+N3gnwp8Ym0vwv4Q8fa9oukWZ8J6HP9ks7bUZ4YY/"
		cPathLogo += "MksmkfaiKu52ZjjJJJJrwT3z+pymGXb6V/IKf+Doz9uoH/kuX/ll+Hv/AJBrqPhN/wAHXf7aXgLxauoax4+8N+ObVV+fTtb8JafFavyOS1jFbTZxkcSgYJ6cEAH9aoORRXxn/wAEXP8AgsF4b/4K8/s43/iax0T/AIRLxh4VvxpniTQDerdraO6s9vcwyABnt5kVsF0V"
		cPathLogo += "lkimTDCMSP8AZeeKAFooJpAc0ALRRQDmgAoozRmgAooJxRmgAopN1LQAUUE0ZoAKKKKAGs+DTTMwHTknAzx/n/61LIny/wBK/mC/4KK/8HCX7YPwE/4KW/Fz4d+E/jA2leEfDPjq+0fTLL/hFNDuGtLWO6ZI4/Nls2kbauAGdmY4ySSSSAf0/g5WmNNtcLjrWV418baX"
		cPathLogo += "8MvBmseINcvIdO0PQLObUdQvJchLW3hjaSSRsZOFRSxx2H4V+Wn7Kn/By5o//BQf/grF8Pfgn8JfClxa/DrVX1WTVfEeujbfauLbTbuaMWtsrYt4zJCj+ZKzSOhCmKE5yAfrIDkUU1TgfrTqACijNGeKACmGQjt3pJpTGCfl4Hevwx/4ORv+Cv8A8YPDP7aXgX9m/wDZ"
		cPathLogo += "k8ReJNM8a2PlTeIf+EeiWW/1HULwL9i01QULfJA3nMEYo32uPdhojgA/c4yEA/d4Gakr5H/4JKfsq/Gr9nn4CR6h+0F8WvE3xO+J3iRIrjULa6vVm03w2oDEWtsEAV5Pn/ezchmUKmEXc/1urZWgBaazFadXy9/wVk/4Kh+Ef+CUX7LNx8RPE+mXPiG+vL1NI0LQ7a5F"
		cPathLogo += "vNq986u6xmQq3lRKiO7y7X2gDCMzKrAH06Z8Ee/680ef+HOBx/n8q/kn+Mf/AAcl/ttftc+N47Hwz40uPCzSN59poHgTQo4TmNJGbaxWa8kXYWZlaVkxGGKgruFL4Z/8HGv7cn7Kfj+G18QfEHVNa+yzC5vPD/jjQoZluw0eAkjGOO8jjKlWAimjyfmBOTkA/rpByKK+"
		cPathLogo += "Of8AgjP/AMFe/Cv/AAVv/Z1u/Emm6evhvxl4VnjsPFXh83H2j7BNIGMM8T4Ba2mEchRmCkNFKhB2bm+xgcigAoopsjsqnaM0AIZGB6Cmi4zjv61+Df8Awcnf8F//AIyfsfftuab8JfgL40g8H/8ACH6JDdeKrgaJZahLc6hdhZ44D9st5VVIrUwSBocbmvHD5KAD6R/4"
		cPathLogo += "NgP+CvPjz/gpb8HfiDoPxc16DxF8R/AWpw3K6klhb2LX2mXSMIgYreOOLfFNFMpZVGUliBGRuYA/VgHIopFPy0tABRRRQAUUUUAFFFFAEbdK/Br/AIOb9cXS/wDgoN4d3sI1X4fWDlj0H/Ex1P8A/XX7yyNwfpX8+v8AwdXXv2T/AIKA6GucBvhlYk55/wCYjq39QPyr"
		cPathLogo += "6bhHFPDY/wBvHeMZP7kz5XjDDKvgPZS2bX5nyZ8Xfgr8RPgBaWdx458F+JfCMOoSNFaSatYPapcuoDMilwAWVSCcZxkdc0z4nfB/x98FNI0zUPGHhDxF4XsdaJWwn1Kxe3jvCFDHyywG/Csrcdjmv0Z/4L3/AA30P4wfEr9nfwz4n8daV8N9B1bXvEYu/E2pqklppapp"
		cPathLogo += "aSK0ivLEp3PGseTIvLqcscAx/wDBcn4PeCvF37LPgXxJr3xW8P8Ag6X4b6VqeqeH7O7giaTx5N9hhCWtqWuI9rN5SYKCbHnrhWGN3yuUfSZxWIr5dTxVFR+sTqRla7sotpNeba1XTfY8nFeFNCMK0qUm+SKa21bV9T8uf+EmOM/1pB4mYj/a7jd0r62+BP8AwSV8Pz/s"
		cPathLogo += "zeHfin8bvjJofwg0HxZBBc6RbXqwQM0U6mS38ye4lRBNLCDKIERmEYyzBg6JxX/BQf8A4JoH9jn4RaH8TPCvj7S/iR8OfEFzFaxX9vHGssDTIzQSB4ZJYbiCTYQJY3GGdBtOQx/YMN46cMVsxWWxrS5m3FNpqLkt0ns35HxdTw5zGnh/rLhdWvvrb0PBtGvr7xHrVnp2"
		cPathLogo += "n2txfahqE8draW0CNJNdTSOEjjRVBLMzsqgAEksB3re+Kfw+8XfA3xBDpPjPw9rHhbVbm3+1xWWqW5trl4d7IJPLb5gpZWAY4B2t1wa9m/aZ/ZJ17/gll4L+D3xe8M/EqPVPEni+6RtMjbwhbbdGmk083Akxcy3MMzorFFLQgg4kBUquMXTP2ItZ/aA/Yj+Jf7W3jD4r"
		cPathLogo += "avq3iS1uby51Szv9D+03OpNbNDGqi6W4jSGNQyqkSW5jiRAirgADGp4wYR1aOOpVY/U5SdPmd+Z1G7JJdrnRHgOfs5UJJ+2Sul05e5+kn/BrHf8A9ofC/wCMLc/LrNgP/JeSv1fY/LX5F/8ABprdm5+EnxoYnP8AxPNP/wDSZzX66LyK+J4rqKpmtaa7/oj9O4Ypezy2"
		cPathLogo += "lDsv1GyjETV/F1+3I0n/AA/B+MG0tu/4XlrGMc8/29NjHv2Ff2jT/wCqav4mf+CoOgXXin/grR+0RpenxrJfal8W/Edrbxl1TzJJNYuVVdzEAZJHJIA3cmvnz3j+2ZOB3/Gvyd/4O3dR+CZ/4JueILXxdN4P/wCFwNc6bJ4IimeH+3iVvoftJhXPnfZxatdbyQYgXXPz"
		cPathLogo += "lM/jMf8Ag1z/AG6u3wN/8vPw/wD/ACfXmX7Vf/BEj9qf9iD4dN4u+JPwf17RvDNu2251Oxu7LWLawGQA1w9jNN5CFiBvl2rkgA5IFAH6Wf8ABkb8N/FR+LHxy8YRyXFv4JXSNP0adGklSK/1FppJoyq48uRoIVl3EtujF2gAIlYj9VP+Cwv/AAWW8Bf8Ehfg5peq+IdJ"
		cPathLogo += "uvFnjDxRI8Xh/wANWl4tq995e3zZZZmVjDAgdQZBG5LMoCnkj4g/4NO/+CpHw3+J/wALpf2cYfAnhX4W+MPD8U2u2aaQ8wt/GoLKLm5c3EkszXqL5e8PK+YkHlLHFB5cf0//AMFmf+CYX7H/AO0ddw/Fb9pXxNL4BvLewPhy28RTeMG0tcBJp4beCG4Z4HmTE8qRRxEu"
		cPathLogo += "TIXWQDAAPye8Yf8AB6h+0dda7O2h/DP4I6dpL7Tb29/ZapeXEY2gEtKl9CrZbcRiNcAgc43H7C/4JJf8Hadj+1x8e/DHws+M3gHTfBOveMruLTNH8RaBcyyaXNfSBUit5raYtLCJZsokglkAaWNWVVDTUeB/+Dij9gz/AIJwfszaZ8JfhFo/jb4heH9HsBZr/Z3hmOxT"
		cPathLogo += "X5jbqsl1fyXgtTJNPgCaTyCSxO2MptFfgxrHxh03xt/wUFl8eeBdFb4d6Vqnj/8At/QNK0uYW58NRSagJ7eGB4QgjMIKKpjCBCi7duBgA/sC/wCCrP7bmrf8E9v+CfPxA+MuiaHp3iHVPB8di8GnX0zxW9x9o1C2tDuZPm+UTlhjqVA4zX5e/scf8HiuneP7H4haz8Zv"
		cPathLogo += "BPh7wjpXhXQlvNGstCv5LjU/EeoPPHFHZxJKQuNpkdpOFRUyewb7a/4Oa49n/BDX47f9cdI/9Pmn1+HH/Bqh+w74D/bY/wCChmqn4jaHYeKdB8AeGLjXYNH1GCO5sdQu2nt7aL7RDIrLLGizSvsOAXWMnIUqwB7L41/4PWPjnfeP2n8N/CX4S6X4X84MNP1FtR1G/EW4"
		cPathLogo += "kr9qjuII923A3fZ8AgttI+Ufrf8A8ETP+C3fhX/gsB8NvEH2fw9J4I8e+CzANb0Oa9F1DJFNvEd1aylUaSImNgylA0bFVJIZHc/4OFf2XvCXx2/4JD/FxNZ0uxa58B6BJ4i0C6FlG82kXFliX9wSMxiSONoW2kfu5GGD0P4yf8GZOpXC/wDBVHxXapcTR28/w41F5Ykk"
		cPathLogo += "KpKVv9N2lgOGxubGc4ycUAfv/wD8FHP+ClXw3/4JifAC78e/Ea+ZUYm30jR7R0bUteusA+RbxsRnaDl3YhY15J5AP4T/ABQ/4PUvjtq3iqSTwb8JPhFoOjMD5dnrQ1LWLtDvYgmeG5tVPyFBxEMlWbgMFXif+DwP9pLUPin/AMFSbXwH9q1D+xfhT4as7aGylRFhS8vE"
		cPathLogo += "F5PNFhiTvhktEZmCnNvjbhQ7/uV/wQ0/Yg8Ffsbf8E1vhfa+F9LtLfVvGnhrTfEfiXUvKX7VrN7dW6zsZZAqlo4/OMcSn7iKBySzMAfGn/BIf/g680L9tD40aH8MfjF4P0r4d+LPEkkNloutaXeSyaPqd8+EW2kilDSWrSSECMmSVWLhCVIBf9hdV8RWug6Jc6lf3EFj"
		cPathLogo += "Y2ML3FzPcSLHFbxoCzO7sQqqFBJJOAASTjmvyQ/aD/4NBPhN8ef2wPGXxGh+I3iLwP4Z8UatBq1v4W8NaTBb/wBkuQDeCK4kaQDzZd8kQWFVgL7QrgKB1H/B1D+0d4i/ZH/4JDW3hLSdd8QX2qfEXU7HwXf69LNHBe3loLeW4u3maBI033S25jlWKNI2WeVdqqQhAPCf"
		cPathLogo += "+Chn/B5N4d+GfjHVfDP7PvgKz8dSabI9u3ivxFdPDpM8qll3W1rCVmuISdpEjSwk8gJgh6+dfg9/wesfHDR/Gsc3jr4QfCjxJoHlurWOgSahol60n8BFxNPeIFHdfJJOeCK6D/g0C/4JoeBf2hNa8efHXx54d0nxR/whep2+heF7G/hS6tLG/wDLFzPetC4IMsSvbLCx"
		cPathLogo += "zsZ5GGXVWT9sP+Cjv/BPHwH/AMFHv2YfEfgHxtouk3t9c6fcJoGtXFilxfeG71gpiuraTKuhEscRdVdVlRWjfKMwIBR/4Jpf8FUvhZ/wVS+DM3iz4a6hKt5pMkdtr+g6hti1Tw/M6bkE0YYhopAG8uZC0cmyRQ2+ORU+lK/kJ/4NzP2rvEP7If8AwV9+HekQ3t7Do/xA"
		cPathLogo += "1Q+C/ENjbhZI74XBaK3LBmUDyrvyn8wHcqhwAwYo39ekbl0yaAFflD9K/iy/4K6c/wDBZn48f9lN1P8A9LWr+01/uH6V/Fl/wVz/AOUzHx4/7Kbqf/pa1AH9CX/BzX/wVG17/gnX+zlofhvR/Cuj+JIPjdp2veG72W9upYZNOj+yxR+ZEIxhm/0pj82Puj1yP5vf+CbH"
		cPathLogo += "7d2qf8E2v2wfC/xh0XQLDxNqXhaG9hh0+9uZIbeYXNpLbNuZMnCiYtj1x9a/sA/4KX/DvQfGn7Cvxiuta0XSdXn0nwJr01i97ZRXDWcn9nzHfGXU7G+VeR/dHpX8wf8AwbDeGtL8d/8ABaT4U6TrWm2Or6ZcWmuedaX1ulxBLjR7xl3I4KnBUEZHBA9KAP6DP+COP/BX"
		cPathLogo += "yb/goh+wR40+OnxE0nw78OtP8Ea7qFhqH2a8eSztrKzsra6kuZHkwVwszk9sIPWvzT/a9/4PVfFUfj6/s/gZ8J/DEWg2dzsttX8aSXN1PqcI3fvPsttJB5G7gqDLIQFyeW2p+23x8/YX+F/7Qv7N/iX4T694VtbXwD4o2vqGl6G8mjiV1dJFfdaGNiweKI4OQ3lgMGHy"
		cPathLogo += "1+UPwJ+Lf/BLX/gh3+0F4h8XeB/iRdePvGmo2dtb2semsPF0WgwlHErWN7DAII3m3ATbrl3HCKEUspAPnf4I/wDB658ZdM8awyfEX4RfDHxBobMBJD4be/0e8RcHLLJPPdIxGVIGwZ2kZG4Efvf+xX+2X4L/AG/v2YfC/wAV/h9dXNx4b8VW7SRRXkPk3ljNG7RzW08e"
		cPathLogo += "SFlilR0O1mRtoZGdGV2/mI/4OE/+CwHwj/4Kz+LvBmpfDn4X6z4U1Hwn9ohvfEmt29pb6prNvIkHlW8qQNIdkTrMU3zMBvJUKZGFfrJ/wZqaveax/wAEn/EEF1eXlzb6V8R9Ut7OKWdnS1iNjp0pjjUnCIZJZX2rgb5HbG4k0AeGft0/8HavxG/ZL/bW+Jfwp0/4R+B9"
		cPathLogo += "Y0/wP4lutDgvbnU7qOW5jilKB3C5AbA5xxnpX7Y2HwP8H6d4yk8RWnhXwzb+IJJHlfVE0uFb13dSHYzBd5LKcMScsCwOa/jj/wCC0Tf8bjP2gO+34g6gOf8Arua/tIBwW+v+FAH4mf8ABV//AIOk/iB/wTr/AG//AIh/BvRvhb4P8SaZ4NewWDUr3ULmG4m+0afa3h3q"
		cPathLogo += "vy8NOy8HkKDX7NfDXxHJ4w+Huh6xNFHBNq1hBeSRxncsbSRq5UHuAT1r+Rj/AIOeHx/wXL+OmO0ui49v+JFp1f1sfApf+LI+DeT/AMgOy5/7YJQB1lfg7/we/wDg7xBqXw+/Z51y2tb6Twtpd/rljqFwgY20F5PHYPbK/wDCJGjt7rZu5ISTHev3irzn9p/9l/wP+2L8"
		cPathLogo += "Gde+HvxE0K18R+E/EVv5F3aXC/cPVJY3HzRzRt8ySKQyMAQRxQB+FX/BsN/wWR/Zh/Y0/Zj1D4a/EZrf4Y+OrrWZby58U3Ng89p4mhfHkLLcwxs8DQAsnlzYiAw6yb5XRf0s/wCCmn7GHwj/AOC9H7F1/wCH/BfjL4b+IvEmkzRX3hTxjpd/FrMegTG4C3AEtrISYp4o"
		cPathLogo += "JYGQkoXRW2mSBCn5Z/tnf8GX3xD8LeK76++BPxJ8O+KvDu1pYdM8XM+m6vBzhIRPDE9vcEryZGFuM8be5/PP4/f8Et/2sv8AgmNdx+OvFHw68feA4/DsqTDxZod0txbaU7sIkc6hYyOtvuaVYwWdCzSBepxQB/QT/wAEI/8AggH4m/4I/wDxT8T+LdU+MGm+Mo/GGiNp"
		cPathLogo += "N/4fsvDf2WCK4jukkguVvHmaRtsSzKYxEgJuOS3loT+nqfdr8Mv+DZH/AIL7+Ov2rfjBH+z78btZPijxBdadLdeD/ElwoXULw2sIeWwufLUCdjBHJOs8mJD5MokaRmQj9zgMCgArkPjv8ZND/Z5+DHizx54mma38PeDdIuta1F02+Z5FvE0rhAzKpcquACwyxAzzXXZx"
		cPathLogo += "+Vfjt/weHftyn4G/sS6D8HdE1ZbbxD8XtREupQQyL5w0azKySBgMsglujbKD8u9Ypk+ZQ4oA/Fv9iX4AeKP+C4v/AAV0gsfEOprpd78Ttf1HxT4lv4YZJYtOtgZbudIlLhgvC28Q3fJvjGQq5rsP+CLP7RGpf8EpP+C1vh7T/Gcy6bZwa9efDXxmqXIiggWa4No7yu+B"
		cPathLogo += "5MF5HBO+4fdgJwDjH1R/waf/ALQ/7O37Eui/Fb4kfFv4reCfB/jDxFNb+GtH0/UgyX9tp8Src3EwcK37m4lkt1wMfNYkkH5cfNP/AAck+JPgr8Wf+Cit58Svgl468O+MtC+I2k21/rY0piEsNViBtpgVCIAJoooJiSWZ5WmZsZBIB/XRFLuHTocVJXx7/wAEMf28h/wU"
		cPathLogo += "G/4Jo/Dfxpfah/aHi7TbT/hG/FTvMsk39qWSiOSSUgKBJcR+Td7QOBdqOcHH2EOlABRRRQAUUUUAFFFFAEMq5Rvwr+dv/g7W1YWH/BRHw/GO/wALrA9en/Ez1ev6KJBlMetfzhf8HfVjcW//AAUj8HTzWtxHp+pfDGyto7gxkRSOmp6qZVVuhZBLEWAyQJEJxuGfa4fh"
		cPathLogo += "z4n2S3lGSXq00jzc2pqpQs+6/Bo9P/4OpboWfgj4MsfmxruucEdf9EhBOO/t756da5z/AIOStTi0n4A/szXEm3bG+ouflyuP7NsgAOefyOQe/wB2vhT/AIKGf8FZviN/wUqtvDNn440L4f6HYeFb27vrT/hHbW8hmne4jWN1kae5mVhtQY2qvfORxXpnxC/4L7/ET4tf"
		cPathLogo += "sh6t8J/E3gD4a61/aHh6bw6mveVcx3lvG9p9l+0mJndPtQQkl08tSThUQDFfkuV+FfEeW0csrRpRlPDVarkr9JvRq+9ux6eIzTCVqldOTSnGKT9O59X/ALYXwV+Cn/BPH9nr4Xx/tR3Pxq/aG8X6ys40nw/c+MdQ/sfR7mCG3+0i0j+1xR20NvHLHErl5HkL52KpxFtf"
		cPathLogo += "8FO/Fek+Lf8Ag308Ha3oPglvh3oGpahoNzpnhtrl7z+yrZrpzEpldVaQuhWXeRlhLuy2ct8maF/wcQfEBvg3oHhjxp8Jvg78UNT8KxwnTdX8S2M1y5nhi8uG8mhZmVrrO4vLE0JfewG0ksfL/wBqn/gtJ8av2zP2a5Phj46j8B31jc6lFq1zrdppk9rqkjxXb3EMQKT/"
		cPathLogo += "AGdY4wwjUCENsjXLF9ztx0vC/inGYzDVcZS96lWc5S59HFt25YpWVk1v1Ov+18BToShB6ONvPpuz7o/4L3W9xef8E8P2ZNahhabS7G909J7nIMMJm0M+VufoN5VsHPO0+wLvg7oeoaF/wbKfFK41KzmtY9e0/VtTsfNXa09q91CkcuOoVzESmcbl2sMqwJ+Xv2Xv+Dg7"
		cPathLogo += "4m/s3/ADTPhzfeC/A3j7RdBso9M0qfWDNb3MVpFjybeYxlo5kixEqfIjKka5LnDDlvjl/wAF6fjp+0X8AfH3w68V6d8OL7S/iGJ4ry6TS72O80i2k8sJbWhF1sWOLysKZUlcl3ZmdmJroj4c8WrBUsi+rx9nRxKre05vijzN7d7M5v7QwEqzxrk+b2fIlbZn6gf8Ghd/"
		cPathLogo += "9u+DXxqx/Drmm55zgm1ev2K3YFfjb/wZ2aFqUX7Nfxi16e0kXSdU8U2ljaXW9Ss81vZhp1Cg7sIs8J3EYJfAJKsF/ZAc1+sZ419dnbuvwSPOy2n7PDxj6/mOn/1TV/Fh+35qdvoX/Baz41X15MltZ2fxs1yeeZ/uxRprk7Mx9goJ98V/aZNJmI+v1FfgZ+2F/wAGgPxK"
		cPathLogo += "/af/AGtvin8SrH4weB9Ls/iF4v1bxJBZz6ZdyS2cd5ezXCROw6sqyBSRgZBryzuP04X/AIL6fscIMH9oT4f5/wCvmT/43Xh//BQv/g4z/ZC8FfsoeOLHTvHWifFrWvEmg3umWPhXSrWS6TWXmjEBiuJJITbwwkS5cz/ejWTZHMw8tvzxP/BkX8VM/wDJcPh//wCCm8/x"
		cPathLogo += "rV8F/wDBkd44m8Q28evfH7wnp+mnc0k2n+G7i8uMgcBY3miU56El/lHOGzigD5Q/4NXPhjr3jb/gtJ8OtU0mNprHwVpusaxrMgY7YbR9PnswxK54ae6gAzgEsPxi/wCDoL9pXxt8Zv8Agrv8QPCviLVtRl8O/DV7fSfDGkSSFbbSYJLK2mmkjQAfvLiRvMaQguw8tSxS"
		cPathLogo += "ONV/ox/4Jaf8EiPhV/wSe+Fl1ofgCC+1LWtdKSa74k1URtqWrOBlYyyIoit0JbZCowN3zF2LOfmX/guB/wAG2/h3/gqL8QD8T/Bniq3+HvxSa0hs9Re6sftGl+IkhXZC1x5eJYp0TannDzAY4kQx4AZQDl/2Ov8AggV+wD8Fv2R/DfxU8R3mg/E3w5c6Pb39z4+8V+IZ"
		cPathLogo += "dN0S48xDG0/2fzo7e3RpJCqxTb5IWCoXMisx/nt+P3i7wb8Qf+ClHi3XvhzZWum/D/WPiLcXnhq1tLAafBb6c+os1skduFUQoISoWPau0YGBjFfp/wDs6f8ABlP8VNU8e2//AAtf4ufD/RfDMU0bSr4SS81O/u0BzJGhure2SEkYAkxKFLZKNt2t6z+1p/wZrL4l+PDa"
		cPathLogo += "x8C/iRo3gHwdHZWf2bTtWW9vr+C7hiRJZ/PViT5kiifjAV5GCqqKooA+8/8Ag5uYt/wQ2+OnGMwaP/6e9PNfk1/wZMtu/bu+LX/Yg/n/AMTC1r9rP+ChP7EfjT9vv/glZ4g+CepeJNB0rx54q0rSrfUtaEEsmm/bLW7tLm5lVAA+yRreTaDgjeM18p/8EF/+Df3xl/wS"
		cPathLogo += "D/aO8ZeMfEXxC8M+MLXxR4b/ALEitdNsp4JYX+0wz7yZDjaFjIx1JYUAfXH/AAWtjB/4JH/tGe3gHVjj/t3evwV/4MyDn/grB4m/7Jtqf/pfplf0Wft9fs+X37Wv7FfxR+GOm6jZ6PqHjzw5eaJb3t0jPDavPGUDuF5IGc8V+dP/AAQy/wCDdPxp/wAEmP2ytT+Jev8A"
		cPathLogo += "xI8K+L9P1Lwrd6Atpp9jcW80bzXNrKshL5XaPszDrn5hQB+cX/B4J+zZffCv/gqTa+PWtdRGh/FXw3Z3UV5K6tA95ZILO4giG1SuyGOzdlYsc3Gd2DtX9yP+CFX7bfg39sj/AIJrfC2fwzq1jea34L8N6d4b8SabG4W40i+tYFt2V4t7sscnkl4nJw6EHg7lX0X/AIKO"
		cPathLogo += "f8E3fhv/AMFPPgBdeA/iNYy7Y2N1o+sWiquo+H7oDieCRgcZ4Dow2yLwRwCPwn+J3/Blb8eNO8VyR+Dfix8I9d0UBvLutb/tHSbpyHYAGCK2ukHyhTxKfmZlGQAzAH0V/wAFEf8Ag7k1j9mb9ujxl4D+Gfgn4efEnwB4XFtZW+spqk7S6heeWHu2SaImLy1d/JQKpO+B"
		cPathLogo += "n3sHCr69/wAHNvwJ8cfti/8ABFbw346bwtN4f8S+BrzTfHHiDw2l493JpNvLaSQ3ce8wI0zWzXKM7MsQCRTufuAHl/8Agk1/waZeHf2R/jBofxG+N3i7SfiR4g0Fo7zTPDen2DLodpdhT+9mecB7rY/Ma+VCAYw7BshF/Y7UtAttd0S60++ht76zvYnguIJohJDPG4Ks"
		cPathLogo += "jq2QykEgg5z3zQB/Ov8A8GgP/BS/wP8As+at44+BXxA8QaV4V/4TTU7fXvC15qMsdra3t8YxbTWTTuRiWRVtjCpOGZJFX52QP+2X/BRv/goh4B/4Jv8A7MHiL4geNNY0m0vrTT7iTQdFnvlgvPEt6oVYrW2TDO5MkkId0RhCjNI+1VYj8vf+ChH/AAZu+GfiX4x1bxL8"
		cPathLogo += "AfH0HgEao8tw3hbxBavcaXFM29wltcw5mgg3CNfLeKYqNxV8ARn5v+D3/BlR8b9b8bw2/jv4vfCfw74fEbs97oMd/rd4sg+4ot5obRCpPVvPBUchW6UAfNP/AAbd/ss61+1r/wAFiPh5rL6feXmi+Ab+Txpr97APLisHt1eS23NwPnvTbpsXJYF+NqsR/XVbpsiFfOX/"
		cPathLogo += "AATY/wCCXXwq/wCCWnwVbwf8NdLmjuNUeK517XL1/O1LxBcxx+Wsk0nRUUbtkMYWOPe5Cb5HZvpHFACP9w/Sv4sv+Cuf/KZj48f9lN1P/wBLWr+0qaXYren+fXAr8If2z/8Ag0n+I/7UX7b3xG+LVj8XvA+lWHjTxZeeIYLGfTLqSW1jmuGlEbsCAWUEAkcEg0Afr5/w"
		cPathLogo += "UNlEf7AfxzLEKB4A17J7D/iXXH+Nfy4f8GvOtWPhn/gtx8HrjULyzsY501i0ie5nWJJJpdJvI4o1JPzO8jBVUcsSAMniv65dY0m18TaPdWF9bx3VjfRPb3MEq7kmjddrKw9CpIx71/On+0//AMGV/wATrT4palJ8IPip8P8AUPB91czS2UHi1r2w1DT4WfMMDNb29wlw"
		cPathLogo += "yIQhlHl7ym4Rru2qAfbv/B21+1N4i+D3/BMObR/A/iKbTZPF3jG08I+LDptyBNFYy6fc3T2cxTLRCdY4Ay5UvE5Q7o5GVvzU/wCDZX/gk3+zv/wUvf4hX/xd1rUNc8TeE7m2Fn4GtL+TTFlsW+Z76SWMia4V5B5O2F08naS5ZpoSv6WfsD/8G2um/Cf/AIJh/EP9nr42"
		cPathLogo += "eINI8WTfELXovEaah4egeOTw1ex2sEcU1rNOoZpEkSQbzGgaN3RhiR1r4G+IX/BlZ8crHx40PhT4t/CfWPDZYAX2qpqOm35AY5P2aOC4TcFCnAn5PGeNxAOU/wCDoL4X/sq/svp8L/hD+z/oPgTR/GHhu4v7nxguggXl3Yp5dvbW9ve3rtJKZi0MzeRJKXT5pHVTMHk/"
		cPathLogo += "Qj/gzHcp/wAEqPGGMNt+JmpdO2dN0rr/AJ/KvLbr/gzO8HWf7GF/4dsPiIdT+N97qFrdR+Kr22mt9I0+BGYTWkVnHIxKuj/66UyMzxRlRCrMtfYX/BBn/gk78RP+CR3w28d+B/Fvjzw7438N+JNSt9Z0qPTbe4t2026MbQ3O4SZUrKiW2NpBBhOd2RgA/nL/AOC5Hhu9"
		cPathLogo += "8G/8Flvj9DqtpcWc0njW51BY2UeY0E5W4hcDPO+GRHUEjhx0r+u74ffte/Dj4n/s1aR8YNM8YaBF8Ndc02LV4tfvr6Ozs7eB9v8Ar5JCFhdWPlukhDI4ZWAYED8+/wDguJ/wbc6F/wAFPPiDN8UPAvii18CfFh7KG0vft9uZtJ8RCFSkTTmMGaGZI/LQzKJQY4408vID"
		cPathLogo += "D4b/AGYf+DKv4h3vxAWT4zfFrwXpPhe3eNpIPBYutQ1C+TcfMj8y8t4I7fjG2QpOMk/IcDIB+bf/AAWb/aw0H9uL/gp58YPid4XmW58M+INXjg0m5WKSEXtpaW0NnDPskAdfNjt1k2uqsu/BAPFf2Y/Ar/kiHg3/ALAdl/6TpX4fftrf8Gc2pfGn9o/XNf8AhZ468D/D"
		cPathLogo += "7wCbTTbDR9Dn025lnt1tNPtrSSSaRMCSaaaGSaSTlneZmY7mOf3R+G/h6Twj8PtC0mSZJ5NK0+CzaRFIWQxxqhYD0JBNAG3X88X/AAeBT/G34A/tN+D/ABV4b8dfFTSfhH480WG2nsbHxPex6LBrdpJKHUW6SiKF2tmtpFyg8xkmZSxWTb/Q7XkX7Z/7Efw4/b++Bepf"
		cPathLogo += "Dn4o6BB4g8Nag6XEK5MV1pl0gYRXdtMvzQzpuYBl4ZXdGDI7owB+Zn/BAX/g4n+EvxA/ZN8J/Cz43eONF+H/AMRvAdhHpUWqeI777Np3iSzh+SC4+2THy0uFjCJIk0gLsokTIdki+kP+CiX/AAX4/ZS/Z3/Zr8VSf8J98O/jNqmraVPZWXg/QNStvEMeuvMjR+RdeS0k"
		cPathLogo += "EVsQW84zMB5QYBZHZI3/ADL/AGkP+DKL4hWHimeT4SfGTwbrmkzTForfxfaXOl3NnETJhGltY7lJmVVjHmbIg7FztTaA3M/DH/gyp+Omo+IVi8ZfFr4TaDpqsn7/AERNQ1icKWAciKW3tV3BclR5nzMAMrywAPln/g2o+D+sfFn/AILRfB/+z7d5rXwtNe69qc8cRmjs"
		cPathLogo += "7a3sph5jkfdDytBEGPG+ZO+BX9RH7b3/AAUs+C//AATg0Pw/qXxm8Zf8IdYeKJ5bXTJv7Hv9RFzLEqtIuLSGYphXU/PjPbODjz7/AIJU/wDBHT4U/wDBJv4fajYeA/7U1jxF4i8v+3vEerusl9qQjLGOIBQI4YULttSMZOQXZyFI8v8A+C+v/BHjxN/wWB+Hnw80Lwz4"
		cPathLogo += "y0PwfN4K1K7v7iXU7Sa4W5WeFI1CeX0IKE8+ooA+of2NP2+fhX/wUN+FuoeMvg74pHjDw1pupyaJc3n9m3mn+XeRxQzPF5d1FFIdsdxESwUr84AJIIH8sv8AwXw/ax1j/gpB/wAFffGVn4Zhk1u00HVY/h54Rs7Cb7Z/aC207QAwkcSfabt5pU28YljGWwGP76f8Epv+"
		cPathLogo += "CTXxK/4Jdf8ABNj4pfB/SfHvhzUPiB4w1jU9Y0DxDBbzQ2ejz3Wm2lnBK6MrM7QyWxm2gbWwq5XJYfJv/BML/g01179jL9uPwH8UvH3xG8IeMNF8D3b6rbaTZaZMrzXyI32WQmX5QIptkwIG4NEuMdQAfP1r/wAGSfxYltIfO+Nnw9im2DzFTS711R8DcAxALAHgEgZA"
		cPathLogo += "zgZxXnH7YH/Bov8AFb9lL9mXxx8R4/iZ4R8Xf8IRpMutXGkWOm3UVxd28O1pjGxyNyRb3wRzsxxnI/qCtbdYolUDAXOABjGar+INGstf0W80/UbS1vtPvoWt7q2uY1khuInUq6OjAqyspIIIwQSDxQB/OJ/wZk/tqH4cftPeOvgXq2pFdN+I2nrr+hW802EGpWSt56RK"
		cPathLogo += "WA3y2rM7kKWK2KngLz+2v7bX/BXf9nz/AIJ0eMdG0D4yfED/AIQ7VvEFm2oWEH9hanqHnwK5Rn3WlvKq/MCMMQeM4xzX5U/A/wD4NJ/ih+yh+2VoHxV+HPxk8Hx2fgnxSut6FZanY3QuZbOG4LR29zKq7d0kOI5GVcAu+AeM/Tv/AAXk/wCCCPi7/gr98ZvAfibw38QP"
		cPathLogo += "Dfg6z8H6LNpcsGpWU87zvJOZQ6+XhQAMD6igD9C/2Wv2pfA/7aHwK0P4l/DfXF8SeCfEhuP7N1EWdxZ/afIuJbaX91cRxyrtlhkX5kGduRlSCfQq+a/+CRf7E+q/8E6/+Cevw/8Ag3rmt6f4k1LwadS87UbCN47e4+06ld3i7Vf5htW4VTnupNfSlABRRRQAUUUUANYZ"
		cPathLogo += "FfI3/BXX/gkv4R/4KwfAqx8Oa1qj+GPFXhm5a98N+IoLQXT6Y8iqs0LxFl8y3lVE3oHQloonBBjAP13imvEH/nV0akqU1UhuhSSasz+a26/4M9P2n1uZRB46+BEtuHxG8ms6tE8iA8EoNNYKSOcBjg8bj1qP/iD1/amKjPjb4C/L0zr2rnH/AJTP/wBdf0qmH5vvNS+X"
		cPathLogo += "XurijMVa0/wRyfUaL0sfzU/8Qef7U4P/ACO3wFxyede1c9f+4ZTT/wAGeX7VGP8AkdvgH/4PtX/+Vlf0sbKXbVf605j1n+CKWCo72P5px/wZ5ftTFf8AkdPgL/4PtX9v+oZ/nP0x0Pwr/wCDOX48ar4xhh8afFD4T+HdBGTLe6IdR1i8U/L8qwzW1qhBXd8xl4IAwckj"
		cPathLogo += "+jbZxTRAC2TWc+J8xlFxc9H5IFgqK6HlX7F/7G/gf9hH9nbw/wDDP4e6fPp/hzw/G2HuJPNu9RuHJaa6uJMDzJpXJZiAFHCoqIqIvq4TbTguBRXhSk5PmluzpSsrINvP/wBemhMU6ikMMU3yhmnUUANEQX1oMQY9/wA6dRQA3yRuz/n/ADzQ0QanUUANMSsc0GJT/hTq"
		cPathLogo += "KAG+Xx1agxg+tOooAasYUeuKPKXP8+OtOooAaYlYf4U7bxRRQA0RKD9etHkL/k06igBojUCnUUUAIUBz7+lIExTqKAG+WCKPKGc06igBohUf5/CgxgmnUUANMQNBiUn8/wBadRQA0xKQffr70CJQR7dKdRQA1Ygvr+NKFwKWigApNvNLRQA0xg/X19KQ26nrk/U0+igB"
		cPathLogo += "uz/9dBjye9OooAb5S5oWJV6cD0HQU6igAppTNOooAb5Yz3/OgJj/AD1p1FACBOPWloooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK"
		cPathLogo += "KACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/2Q=="
EndCase

If !Empty(cPathLogo)
	Decode64(cPathLogo, CDIRPDF + cCodBanco + ".png")
	cPathLogo := CDIRPDF + cCodBanco + ".png"
EndIf

Return cPathLogo

/*/{Protheus.doc} ConvMacros
	(Converte as  macros do HTML custommizado para conteúdos a serem buscados das tabelas)
	@type Static Function
	@author Calabro'
	@since 05/05/2022
	@version version
	@param cHtml, character, (Conteudo HTML a ser convertido)
	@return cHtml, character, (Conteudo HTML apos conversao)
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function ConvMacros(cHtml as character)

Local cCadastro		:= "" as character

If !AliasInDic(cAliasCadGen)
	cHtml := StrTran(cHtml, "%NOMEFANTASIA%", AllTrim(Posicione("SA1", 1, xFilial("SA1")+SF2->(F2_CLIENTE+F2_LOJA), "A1_NREDUZ")))
	cHtml := StrTran(cHtml, "%RAZAOSOCIAL%", AllTrim(SA1->A1_NOME))
	cHtml := StrTran(cHtml, "%ENDERECOCLIENTE%", AllTrim(SA1->A1_END))
	cHtml := StrTran(cHtml, "%DATAVENCIMENTO%", DToC(SE1->E1_VENCREA))
	cHtml := StrTran(cHtml, "%VALORTOTAL%", AllTrim(Transform(SE1->E1_VALOR, X3Picture("E1_VALOR"))))
	cHtml := StrTran(cHtml, "%NUMERONOTA%", AllTrim(SF2->F2_DOC))
	cHtml := StrTran(cHtml, "%SERIENOTA%", AllTrim(SF2->F2_SERIE))
	cHtml := StrTran(cHtml, "%CHAVENFE%", AllTrim(SF2->F2_CHVNFE))
	cHtml := StrTran(cHtml, "%MESANOFATURAMENTO%", Month2Str(SF2->F2_EMISSAO) + "/" + Year2Str(SF2->F2_EMISSAO))
Else

	cCadastro		:= PadR("RFINR01_HTML_BOLETO",TamSX3(cAliasCadGen + "_CADAST")[1])

	(cAliasCadGen)->(DbSetOrder(1))    // PE0_FILIAL+PE0_CADAST+PE0_CHAVE

	If (cAliasCadGen)->(DbSeek(xFilial(cAliasCadGen)+cCadastro))
		// Transforma conteudo De/Para do cadastro generico - PE0
		While (cAliasCadGen)->(!EOF()) .AND. (cAliasCadGen)->&(cAliasCadGen + "_FILIAL" + cAliasCadGen + "_CADAST") == xFilial(cAliasCadGen) + cCadastro
			cHtml := StrTran(cHtml, AllTrim((cAliasCadGen)->&(cAliasCadGen + "_CONTDE")),		&(WK_Generico():GetConteudo(cCadastro, (cAliasCadGen)->&(cAliasCadGen + "_CONTDE")		, AllTrim((cAliasCadGen)->&(cAliasCadGen + "_CONTPA")) )))
			(cAliasCadGen)->(DbSkip())
		EndDo
	EndIf
EndIf

Return cHtml

/*/{Protheus.doc} InverteMarca
	(Funcao para inverter marcacao de linha)
	@type Static Function
	@author Calabro
	@since 07/12/2022
	@version version
	@param oBrw, object, (Objeto Browse de interface de tela)
	@return Nil, Nulo
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function InverteMarca(oBrw as object, oSay1 as object, oSay2 as object)

// Verifico se marcou ou desmarcou para incrementar ou decrementar 
// quantidade e valores dos titulos selecionados
If !Marked("E1_OK")
	nQtdSel++
	nVlrSel+=SE1->E1_VLCRUZ
Else
	nQtdSel--
	nVlrSel-=SE1->E1_VLCRUZ
EndIf

// Marco o registro da SE1 com a marcacao ou desmarcacao
RecLock("SE1",.F.)
	SE1->E1_OK := If(Marked("E1_OK"), oBrw:CCODMARCA, "")
MsUnLock()

oBrw:REFRESHLINE()

Return Nil

/*/{Protheus.doc} InvAllMarcas
	(Funcao para inverter marcacao de todas as linhas)
	@type Static Function
	@author Calabro'
	@since 07/12/2022
	@version version
	@param oBrw, object, (Objeto Browse de interface de tela)
	@return Nil, Nulo
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function InvAllMarcas(oBrw as object)

Local aAreas		:= {SE1->(GetArea()), GetArea()} as array

SE1->(dbGoTop())
While SE1->(!Eof())
	InverteMarca(@oBrw)
	SE1->(dbSkip())
Enddo

AEval(aAreas, {|x| RestArea(x) })

oBrw:oBrowse:REFRESH()

Return Nil

/*/{Protheus.doc} AtuTotalizad
	(Funcao para atualizar totalizadores de tela)
	@type Static Function
	@author Calabro'
	@since 07/12/2022
	@version version
	@param oSay1, object, (Objeto de texto de quantidade de titulos selecionados)
	@param oSay2, object, (Objeto de texto de valor total dos titulos selecionados)
	@return Nil, Nulo
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function AtuTotalizad(oSay1 as object, oSay2 as object)

// Ajusto textos exibidos na tela
oSay1:SetText("Qtd Selec.: "+AllTrim(Transform(nQtdSel,"@R 999999999")))
oSay2:SetText("Vlr Selec.: "+AllTrim(Transform(nVlrSel,"@R 99,999,999.99")))

Return Nil

/*/{Protheus.doc} LimpaMark
	(Funcao para limpar todos os registros da SE1 que foram filtrados)
	@type Static Function
	@author Calabro'
	@since 07/12/2022
	@version version
	@param oBrw, object, (Objeto Browse de interface de tela)
	@return Nil, Nulo
	@example
	(examples)
	@see (links_or_references)
	/*/

Static Function LimpaMark(oBrw as object)

SE1->(DBEval(	{|| RecLock("SE1", .F.), SE1->E1_OK := "", SE1->(MsUnlock()), oBrw:REFRESHLINE()},;
				/*bFirstCondition*/,;
				{|| SE1->(!EOF())},;
				/*nCount*/,;
				/*nRecno*/,;
				.F.))

Return Nil
